### ISSUE TITLE
Check failed: FLAGS_output_reconstruction.size() > 0

### ISSUE THREAD

**Issue by libing64** [sweeneychris/TheiaSfM#104]
I compiled the project and want to try the reconstruction part.
First, I set the file path in the flag file,build_reconstruction_flags.txt, 

```
############### Input/Output ###############
# Input/output files.
# Set these if a matches file is not present. Images should be a filepath with a
# wildcard e.g., /home/my_username/my_images/*.jpg
--images=/home/xxx/source/vision/TheiaSfM/data/image/img*.png
--output_matches_file=/home/xxx/source/vision/TheiaSfM/data/image/output.matches

# If a matches file has already been created, set the filepath here. This avoids
# having to recompute all features and matches.
--matches_file=

# The calibration file indicates possibly known calibration e.g, from EXIF or
# explicit calibration. Theia attempts to extract EXIF focal lengths if calibration
# is not supplied for a given image.
--calibration_file=
--output_reconstruction=/home/xxx/source/vision/TheiaSfM/data/
```

and then try run the binary by
./bin/build_reconstruction ../applications/build_reconstruction_flags.txt, however, it always says, 

`F0827 22:49:53.168746  5073 build_reconstruction.cc:396] Check failed: FLAGS_output_reconstruction.size() > 0 (0 vs. 0) Must specify a filepath to output the reconstruction.
`
Is there an example for the build_reconstruction_flags.txt?

**Comment by sweeneychris** [comment]
Two things here. First, the output reconstruction is the base filename for any reconstructions generated (you currently have a directory listed).

The second issue is simply the way you are passing the flags file. You'll want to pass in the flags file this way:

./bin/build_reconstruction --flagfile=../applications/build_reconstructions_flags.txt

I think that should fix your issues

**Comment by sweeneychris** [comment]
More documentation is listed here, though it's a bit outdated at the moment: http://theia-sfm.org/applications.html#build-reconstruction

**Comment by libing64** [comment]
@sweeneychris Great thanks. 
Now it can run to the reconstruction part, but it always says 
`Calibration matrices are ill formed`,
What is the file format for calibration file?

**Comment by sweeneychris** [comment]
You can either comment out the line that specifies a calibration file in the build_reconstruction_flags.txt or you can use the format as describe [here](https://github.com/sweeneychris/TheiaSfM/blob/master/src/theia/io/read_calibration.h#L48)

**Comment by libing64** [comment]
@sweeneychris Geat thanks.
