### ISSUE TITLE
Different equation with paper (robust_rotation_estimator.cc)

### ISSUE THREAD

**Issue by mhsung** [sweeneychris/TheiaSfM#105]
Hi Chris,

In line261 of TheiaSfM/src/theia/sfm/global_pose_estimation/robust_rotation_estimator.cc
The equation in the code is different with the Chatterjee et al.'s ICCV 2013 paper (as written below equation 9).
According to the paper the numerator should be kSigma * kSigma.
Is this right?

**Comment by sweeneychris** [comment]
Yes, from a quick look it seems that you are correct. However, note that this should not affect performance since it will simply scale all matrices by a common scalar factor. Do you notice a performance difference if you use kSigma * kSigma in the numerator?

**Comment by mhsung** [comment]
I didn't try it yet, but I agree that it won't make any big difference. I was just curious whether it is a mistake in the paper or in the code.
