### ISSUE TITLE
About Theia data directory

### ISSUE THREAD

**Issue by WayneTimer** [sweeneychris/TheiaSfM#106]
I wonder if it is an inelegant code in CMakeLists.txt:

```
add_definitions(-DTHEIA_DATA_DIR="${CMAKE_SOURCE_DIR}/data")
```

which means I need to keep this git folder in my system even though I have fully installed it on my system.
It might be a better way to install this data directory into /etc or /usr/local/lib or other system folder instead of `${CMAKE_SOURCE_DIR}`.

**Comment by sweeneychris** [comment]
Hi sorry for the delay in responding, I have been traveling recently. Is the issue here that the data directory (and specifically the EXIF database) is not installed along with the library?

**Comment by WayneTimer** [comment]
Precisely.
When I am using Theia, I find that there are some codes specifying the data directory like
`THEIA_DATA_DIR + std::string("/image/test1.jpg");`
I searched for the definition of `THEIA_DATA_DIR` and finally got the `add_definitions()` in CMakeLists.txt as I commented above. To my poor knowledge, people usually remove the installation package after fully installed it. (Yep.. it happened to me. I could not run Theia until I re-downloaded it.)
I guess it might be better if the data directory can be installed along with the library.

**Comment by sweeneychris** [comment]
Sorry for being so delayed on this. I looked into it a bit and it looks like CMake can handle this using the configure_file command. That command will basically write c++ code that contains the path to the data file. If this is done the right way, that c++ code will be appropriately rewritten by cmake upon a "make install" and the path to the THEIA_DATA_DIR should automatically update.

**Comment by KindDragon** [comment]
> It might be a better way to install this data directory into /etc or /usr/local/lib or other system folder instead of ${CMAKE_SOURCE_DIR}.

I think better allow specifying this directory at runtime or use the relative path to theia.so/app file
