### ISSUE TITLE
why principal point is assumed to be in the center of image 

### ISSUE THREAD

**Issue by zhixy** [sweeneychris/TheiaSfM#108]
Regarding reading calibration file, the principal point is assumed in the center, and the image width and height are set to twice of the value. However, for some images, such as image whose one edge is cropped a little, this is not the truth, whether does it mean that theia cannot deal with such images correctly?

**Comment by sweeneychris** [comment]
The principal point is in the image center for the vast majority of consumer cameras, so this is a reasonable assumption. The only way in which this affects Theia for the calibration file is that the image width and height may be stored incorrectly. Those values will not affect the reconstruction process though.
