### ISSUE TITLE
OpenMP compilation problem

### ISSUE THREAD

**Issue by bugakov** [sweeneychris/TheiaSfM#110]
Hi Chris,
While building TheiaSFM we had such error:
`[ 88%] Building CXX object applications/CMakeFiles/build_1dsfm_reconstruction.dir/build_1dsfm_reconstruction.cc.o
Linking CXX executable ../bin/build_1dsfm_reconstruction
/usr/bin/ld: ../libraries/akaze/lib/libakaze.a(nldiffusion_functions.cpp.o): undefined reference to symbol 'GOMP_loop_end_nowait@@GOMP_1.0'
//usr/lib/x86_64-linux-gnu/libgomp.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [bin/build_1dsfm_reconstruction] Error 1
make[1]: *** [applications/CMakeFiles/build_1dsfm_reconstruction.dir/all] Error 2
make: *** [all] Error 2`

It runs normally when OpenMP is disabled with cmake. 

GOMP version is 4.8.4-2ubuntu1~14.04.3

**Comment by sweeneychris** [comment]
If you change the "ON" in this line to "OFF" does it compile properly (with no other modifications)?

https://github.com/sweeneychris/TheiaSfM/blob/master/libraries/akaze/CMakeLists.txt#L5

**Comment by sweeneychris** [comment]
Did my suggestion solve your problem? I have updated the line to be "OFF" in the master branch now

**Comment by bugakov** [comment]
Yes, now the compilation is OK with default parameters, without any modifications.
Thank you very much.
