### ISSUE TITLE
AKAZE module bugfix

### ISSUE THREAD

**Issue by SeyoungPyo** [sweeneychris/TheiaSfM#112]
From 'src/theia/image/descriptor/akaze_descriptor.cc' ( line 69 )
normalization must be removed.
( img_32 /= 255.0; )

Because img_32 ( FloatImage type ) is already normalized (0.0 ~ 1.0),
there will be no feature point with above line.

Thanks.

**Comment by sweeneychris** [comment]
Great catch! Could you submit a patch for this through Gerrit? http://theia-sfm.org/contributions.html

**Comment by SeyoungPyo** [comment]
Ok. I'll try it.

And, I found another typo(?) in AKAZE module. Check and confirm below..

in libraries/akaze/src/AKAZE.cpp, (Line 592)
>> kpt.angle = atan2(sumY, sumX) * (M_PI / 180.0);

I think this line must be changed to this.
>> kpt.angle = atan2(sumY, sumX) * (180.0 / M_PI);

Same on (Line 560)
Ang[idx] = atan2(resY[idx], resX[idx]) * (M_PI / 180.0);
==> Ang[idx] = atan2(resY[idx], resX[idx]) * (180.0 / M_PI);

**Comment by SeyoungPyo** [comment]
I need help to submit change.. :(
( It's my first time to use git repository. I have used TFS on windows.. )

(1) installed msysgit on my windows 7

(2) got sources with ' git clone https://review.gerrithub.io/sweeneychris/TheiaSfM '

(3) I've followed instruction for windows with below command
> curl -o .git/hooks/commit-msg http://cs.ucsb.edu/~cmsweeney/theia/commit-msg
> chmod +x .git/hooks/commit-msg

(4) Configured GerritHub HTTP Password

(5) I have changed code.

(6) When I tried to push my changes, some error occurs
> SeyoungPyo@SeyoungPyo-PC MINGW64 /e/Downloads/gitRoot/TheiaSfM (master)
> $ git push origin HEAD:refs/for/master
> Total 0 (delta 0), reused 0 (delta 0)
> remote: Processing changes: refs: 1, done
> To https://review.gerrithub.io/sweeneychris/TheiaSfM
>  ! [remote rejected] HEAD -> refs/for/master (no new changes)
> error: failed to push some refs to 'https://review.gerrithub.io/sweeneychris/The
iaSfM'
> 
> SeyoungPyo@SeyoungPyo-PC MINGW64 /e/Downloads/gitRoot/TheiaSfM (master)

**Comment by sweeneychris** [comment]
It says there are no new changes. You must commit your changes before trying to push them to the repo

**Comment by SeyoungPyo** [comment]
Thank you.
I've commited and requested code review to you.

For windows users, below contributions page contains wrong info.
"theia-sfm.org/contributions.html"


After
> curl -o .git/hooks/commit-msg http://cs.ucsb.edu/~cmsweeney/theia/commit-msg

File 'commit-msg' created, but it contains below..

>> <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
>> <html><head>
>> <title>404 Not Found</title>
>> </head><body>
>> <h1>Not Found</h1>
>> <p>The requested URL /~cmsweeney/theia/commit-msg was not found on this server.</p>
>> <hr>
>> <address>Apache/2.2.15 (CentOS) Server at cs.ucsb.edu Port 80</address>
>> </body></html>

Valid URL seems like this
> curl -o .git/hooks/commit-msg http://homes.cs.washington.edu/~csweeney/theia/commit-msg

**Comment by sweeneychris** [comment]
I have updated the docs and the website to have the correct URL now. Thanks!
