### ISSUE TITLE
Stricter focal length validation

### ISSUE THREAD

**Issue by s7orm** [sweeneychris/TheiaSfM#115]
Hello,

while playing around with some test images I encountered the following error:
`Check failed: ransac_params.error_thresh > 0 (0 vs. 0) Error threshold must be set to greater than zero`

I tracked down the issue and it turned out that the Exif:PixelXDimension and Exif:PixelYDimension attributes of the image were not available, which lead to the focal length being set to `inf` [here](https://github.com/sweeneychris/TheiaSfM/blob/ee10a9220dbdf85af161195747e56c8bfb2e5661/src/theia/sfm/exif_reader.cc#L247-L263). The infinity value passes the [sanity check](https://github.com/sweeneychris/TheiaSfM/blob/ee10a9220dbdf85af161195747e56c8bfb2e5661/src/theia/sfm/exif_reader.cc#L148-L150) but leads to the error above [further down the road](https://github.com/sweeneychris/TheiaSfM/blob/ee10a9220dbdf85af161195747e56c8bfb2e5661/src/theia/sfm/estimate_twoview_info.cc#L122-L124).

Also according to the documentation, in case the user has configured that only calibrated views should be allowed (the only_calibrated_views parameter for build_reconstruction), the image should be skipped if the focal length is invalid, but I dont think [this is the case](https://github.com/sweeneychris/TheiaSfM/blob/ee10a9220dbdf85af161195747e56c8bfb2e5661/src/theia/sfm/feature_extractor_and_matcher.cc#L197-L198) (correct me if I am wrong).

PS: The issue can be reproduced with the 1440553366_b4cb1d881b_o.jpg image from the Gendarmenmarkt 1DSfM image data set (and several others).
PS2: I am using the latest OpenImageIO version from homebrew - 1.6.13.

**Comment by sweeneychris** [comment]
Great catch and thank you so much for the detailed notes about which lines are affecting the error. I think the fix should be on [this line](https://github.com/sweeneychris/TheiaSfM/blob/ee10a9220dbdf85af161195747e56c8bfb2e5661/src/theia/sfm/exif_reader.cc#L148) where we should check that the focal lengths is not nan and not infinity (using std lib operators). Could you [submit a patch](http://theia-sfm.org/contributions.html) to fix the error with this?

**Comment by s7orm** [comment]
Sure, I will give it a go. Regarding the fix - yes, the place you mentioned would be the prime candidate, however I think that also the SetFocalLengthFromExif method has to be modified slightly: on the one hand, it appears that a return statement is missing (I am not sure whether intentional or not), but on the other hand returning `true` would prohibit [calling the fallback method](https://github.com/sweeneychris/TheiaSfM/blob/ee10a9220dbdf85af161195747e56c8bfb2e5661/src/theia/sfm/exif_reader.cc#L141-L142). So I think that some sort of validation has to take place there as well. Anyway I would submit a patch to Gerrit and we can discuss the implementation there.

**Comment by sweeneychris** [comment]
Ok I have incorporated your changes into the main repo. I also added this patch (not yet merged to the master branch) to address issue you mention with the fallback method. What do you think? Does this seem to address the issue appropriately?

**Comment by s7orm** [comment]
Oh, I guess you found the Gerrit commit. I only checked in one part, as I wanted to make sure that the change can be validated - the exif unit tests fail locally for me and I was hoping that there is a build job set up, that can take care of that. Your change seems to cover everything - I think there is still one return statement missing - I have added a comment in Gerrit.

**Comment by sweeneychris** [comment]
Awesome, thanks very much for providing feedback. I have incorporated your changes and yes, you were correct that I was missing a return in the feature extractor and matcher so I have added that as well.

https://review.gerrithub.io/#/c/299566/

**Comment by sweeneychris** [comment]
Does this latest change still fail the exif unit test for you? Note that in order to use this patch you'll have to download and apply it as a patch (it is not yet merged into the master branch).

**Comment by s7orm** [comment]
Your commit fixes the failing exif unit tests for me. Thanks!

**Comment by sweeneychris** [comment]
Yay! Closing this issue now then. Thanks so much for the report and for helping me with the proper fix.
