### ISSUE TITLE
Is Incremental SfM or Global SfM able to reconstruct 3D coordinates in world units?

### ISSUE THREAD

**Issue by taoyizhi68** [sweeneychris/TheiaSfM#118]
Or just an unknown scale size? Tried the api to estimate 3D structure from two images, it seems differ from real size. Thanks

**Comment by sweeneychris** [comment]
This is the case with any 3d reconstruction software. 3d reconstructions inherently have an ambiguous scale (you can scale the reconstruction arbitrarily and it will not affect the projective properties of the reconstruction), and you cannot recover scale unless you explicitly account for it. For instance, if you know the metric distance between two points in a scene then you can scale the reconstruction appropriately.

**Comment by taoyizhi68** [comment]
@sweeneychris I figure it out now. Thank you for your reply, really appreciate it.
