### ISSUE TITLE
Why reading calibration only support two distortion parameters?

### ISSUE THREAD

**Issue by zhixy** [sweeneychris/TheiaSfM#124]
Just a little confused that  now that fish eye camera model is supported, why still only two distortion parameters are read from file in "ReadCalibration" function? Is it out of date, or do I miss something?

**Comment by sweeneychris** [comment]
The calibration file is indeed out of date a bit. It currently only supports the pinhole camera model. This is because I could not find a simple and clean way to have a calibration file take in all possible camera types without making the file confusing and bloated.

**Comment by sweeneychris** [comment]
By the way, another very simple way to specify your own calibration is to simply populate a CameraIntrinsicsPrior object for each image your are importing. If all images have the same calibration then this is very easy. You'd basically want to populate this container: https://github.com/sweeneychris/TheiaSfM/blob/master/applications/build_reconstruction.cc#L358

**Comment by zhixy** [comment]
Yes, thank you for your kind reminding.

**Comment by sweeneychris** [comment]
I have created a new issue to track this feature. I hope to add it to Theia some time very soon! https://github.com/sweeneychris/TheiaSfM/issues/126
