### ISSUE TITLE
which version of FLANN used in Theia?

### ISSUE THREAD

**Issue by zhixy** [sweeneychris/TheiaSfM#127]
Hi,

I'm using PCL and Theia together in a project, and both of them utilize FLANN. Although I find it is 1.8.4 said in Theia, it is actually different to 1.8.4 release [here](https://github.com/mariusmuja/flann). While PCL really utilize 1.8.4 release. I believe that this is the reason why my project cannot work well, so I instead the FLANN in Theia by the offical 1.8.4 release, it works now. I wanna know that why not leave FLANN for users to install?

**Comment by sweeneychris** [comment]
I believe I pulled a version of FLANN from the repo directly because it had some critical bug fixes that were addressed since 1.8.4.
