### ISSUE TITLE
Failing make

### ISSUE THREAD

**Issue by charlescva** [sweeneychris/TheiaSfM#129]
Build Environment:
Debian 4.7.8-1~bpo8+1 (2016-10-19) x86_64 GNU/Linux
Compiled and Installed Ceres Solver 1.12.0
OIIO-dev is 1.4.14
eigen3-dev is 3.3.0 (And is the same version used to compile Ceres)
suitesparse is 4.2.1 (As recommended by Ceres 1.12.0 docs)
cmake 3.0.2
gcc (Debian 4.9.2-10) 4.9.2

Exception:

[  9%] Built target akaze
Scanning dependencies of target akaze_match
Scanning dependencies of target akaze_features
Scanning dependencies of target theia
[  9%] [  9%] Building CXX object libraries/akaze/CMakeFiles/akaze_features.dir/akaze_features.cpp.o
Building CXX object libraries/akaze/CMakeFiles/akaze_match.dir/akaze_match.cpp.o
[  9%] [  9%] Building CXX object src/theia/CMakeFiles/theia.dir/image/descriptor/akaze_descriptor.cc.o
Building CXX object src/theia/CMakeFiles/theia.dir/image/descriptor/create_descriptor_extractor.cc.o
[  9%] Building CXX object src/theia/CMakeFiles/theia.dir/image/descriptor/descriptor_extractor.cc.o
In file included from /usr/include/OpenImageIO/imagebuf.h:47:0,
                 from /home/ottch/Development/TheiaSfM/src/theia/image/image.h:39,
                 from /home/ottch/Development/TheiaSfM/src/theia/image/descriptor/akaze_descriptor.cc:44:
/usr/include/OpenImageIO/fmath.h:1301:13: error: ‘constexpr bool std::isnan(double)’ conflicts with a previous declaration
  using std::isnan;
             ^
In file included from /usr/include/features.h:374:0,
                 from /usr/include/x86_64-linux-gnu/c++/4.9/bits/os_defines.h:39,
                 from /usr/include/x86_64-linux-gnu/c++/4.9/bits/c++config.h:430,
                 from /usr/include/c++/4.9/bits/stl_algobase.h:59,
                 from /usr/include/c++/4.9/vector:60,
                 from /home/ottch/Development/TheiaSfM/src/theia/image/descriptor/akaze_descriptor.h:38,
                 from /home/ottch/Development/TheiaSfM/src/theia/image/descriptor/akaze_descriptor.cc:35:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:234:1: note: previous declaration ‘int isnan(double)’
 __MATHDECL_1 (int,isnan,, (_Mdouble_ __value)) __attribute__ ((__const__));
 ^
In file included from /usr/include/OpenImageIO/imagebuf.h:47:0,
                 from /home/ottch/Development/TheiaSfM/src/theia/image/image.h:39,
                 from /home/ottch/Development/TheiaSfM/src/theia/image/descriptor/akaze_descriptor.cc:44:
/usr/include/OpenImageIO/fmath.h:1302:13: error: ‘constexpr bool std::isinf(double)’ conflicts with a previous declaration
  using std::isinf;
             ^
In file included from /usr/include/features.h:374:0,
                 from /usr/include/x86_64-linux-gnu/c++/4.9/bits/os_defines.h:39,
                 from /usr/include/x86_64-linux-gnu/c++/4.9/bits/c++config.h:430,
                 from /usr/include/c++/4.9/bits/stl_algobase.h:59,
                 from /usr/include/c++/4.9/vector:60,
                 from /home/ottch/Development/TheiaSfM/src/theia/image/descriptor/akaze_descriptor.h:38,
                 from /home/ottch/Development/TheiaSfM/src/theia/image/descriptor/akaze_descriptor.cc:35:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:201:1: note: previous declaration ‘int isinf(double)’
 __MATHDECL_1 (int,isinf,, (_Mdouble_ __value)) __attribute__ ((__const__));
 ^
src/theia/CMakeFiles/theia.dir/build.make:54: recipe for target 'src/theia/CMakeFiles/theia.dir/image/descriptor/akaze_descriptor.cc.o' failed
make[2]: *** [src/theia/CMakeFiles/theia.dir/image/descriptor/akaze_descriptor.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /usr/include/OpenImageIO/imagebuf.h:47:0,
                 from /home/ottch/Development/TheiaSfM/src/theia/image/image.h:39,
                 from /home/ottch/Development/TheiaSfM/src/theia/image/descriptor/descriptor_extractor.cc:39:
/usr/include/OpenImageIO/fmath.h:1301:13: error: ‘constexpr bool std::isnan(double)’ conflicts with a previous declaration
  using std::isnan;
             ^
In file included from /usr/include/features.h:374:0,
                 from /usr/include/x86_64-linux-gnu/c++/4.9/bits/os_defines.h:39,
                 from /usr/include/x86_64-linux-gnu/c++/4.9/bits/c++config.h:430,
                 from /usr/include/c++/4.9/new:39,
                 from /usr/include/eigen3/Eigen/Core:66,
                 from /home/ottch/Development/TheiaSfM/src/theia/image/descriptor/descriptor_extractor.h:38,
                 from /home/ottch/Development/TheiaSfM/src/theia/image/descriptor/descriptor_extractor.cc:35:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:234:1: note: previous declaration ‘int isnan(double)’
 __MATHDECL_1 (int,isnan,, (_Mdouble_ __value)) __attribute__ ((__const__));
 ^
In file included from /usr/include/OpenImageIO/imagebuf.h:47:0,
                 from /home/ottch/Development/TheiaSfM/src/theia/image/image.h:39,
                 from /home/ottch/Development/TheiaSfM/src/theia/image/descriptor/descriptor_extractor.cc:39:
/usr/include/OpenImageIO/fmath.h:1302:13: error: ‘constexpr bool std::isinf(double)’ conflicts with a previous declaration
  using std::isinf;
             ^
In file included from /usr/include/features.h:374:0,
                 from /usr/include/x86_64-linux-gnu/c++/4.9/bits/os_defines.h:39,
                 from /usr/include/x86_64-linux-gnu/c++/4.9/bits/c++config.h:430,
                 from /usr/include/c++/4.9/new:39,
                 from /usr/include/eigen3/Eigen/Core:66,
                 from /home/ottch/Development/TheiaSfM/src/theia/image/descriptor/descriptor_extractor.h:38,
                 from /home/ottch/Development/TheiaSfM/src/theia/image/descriptor/descriptor_extractor.cc:35:
/usr/include/x86_64-linux-gnu/bits/mathcalls.h:201:1: note: previous declaration ‘int isinf(double)’
 __MATHDECL_1 (int,isinf,, (_Mdouble_ __value)) __attribute__ ((__const__));
 ^
src/theia/CMakeFiles/theia.dir/build.make:100: recipe for target 'src/theia/CMakeFiles/theia.dir/image/descriptor/descriptor_extractor.cc.o' failed
make[2]: *** [src/theia/CMakeFiles/theia.dir/image/descriptor/descriptor_extractor.cc.o] Error 1
CMakeFiles/Makefile2:4655: recipe for target 'src/theia/CMakeFiles/theia.dir/all' failed
make[1]: *** [src/theia/CMakeFiles/theia.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by sweeneychris** [comment]
As mentioned on the website, oiio should be at least v1.6. could you please
to upgrading to that version and see if these errors persist?

**Comment by charlescva** [comment]
Oversight on my part.  oiio 1.6 fixed it.

**Comment by philleer** [comment]
```-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- No preference for use of exported Eigen CMake configuration set, and no hints for include directory provided. Defaulting to preferring an installed/exported Eigen CMake configuration if available.
-- Found installed version of Eigen: /usr/lib/cmake/eigen3
-- Found Eigen: /usr/include/eigen3 (found suitable version "3.2.92", minimum required is "3.2.0")
-- Found Eigen version 3.2.92: /usr/include/eigen3
-- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
-- Found installed version of gflags: /usr/local/lib/cmake/gflags
-- Detected gflags version: 2.2.2
-- Found Gflags: /usr/local/include
-- Found Google Flags: /usr/local/include in namespace: google
-- Check for Google Log
-- No preference for use of exported glog CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported glog CMake configuration if available.
-- Failed to find installed glog CMake configuration, searching for glog build directories exported with CMake.
-- Failed to find an installed/exported CMake configuration for glog, will perform search for installed glog components.
-- Found Glog: /usr/local/include
-- Found Google Logging: /usr/local/include
-- Check for Ceres
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found installed version of Eigen: /usr/lib/cmake/eigen3
-- Found required Ceres dependency: Eigen version 3.2.92 in /usr/include/eigen3
-- Failed to find installed glog CMake configuration, searching for glog build directories exported with CMake.
-- Failed to find an installed/exported CMake configuration for glog, will perform search for installed glog components.
-- Found required Ceres dependency: glog
-- Found installed version of gflags: /usr/local/lib/cmake/gflags
-- Detected gflags version: 2.2.2
-- Found required Ceres dependency: gflags
-- Found Ceres version: 2.0.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, SchurSpecializations]
-- Found Ceres:
-- Check for OpenImageIO
CMake Error at cmake/FindOpenImageIO.cmake:59 (message):
  Failed to find OpenImageIO - Could not find OpenImageIO include directory,
  set OPENIMAGEIO_INCLUDE_DIR to directory containing OpenImageIO/imageio.h
Call Stack (most recent call first):
  cmake/FindOpenImageIO.cmake:113 (openimageio_report_not_found)
  CMakeLists.txt:162 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/cv/theiasfm/build/CMakeFiles/CMakeOutput.log".
See also "/home/cv/theiasfm/build/CMakeFiles/CMakeError.log".
```
when i run **`cmake ..`**
something went wrong as shown above, so what the problem maybe, how can i fix it? much thx!

**Comment by philleer** [comment]
And CMakeFiles/CMakeError.log looks like this
```
Determining if the pthread_create exist failed with the following output:
Change Dir: /home/cv/theiasfm/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_72617/fast"
/usr/bin/make -f CMakeFiles/cmTC_72617.dir/build.make CMakeFiles/cmTC_72617.dir/build
make[1]: Entering directory '/home/cv/theiasfm/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_72617.dir/CheckSymbolExists.c.o
/usr/bin/cc     -o CMakeFiles/cmTC_72617.dir/CheckSymbolExists.c.o   -c /home/cv/theiasfm/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_72617
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_72617.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_72617.dir/CheckSymbolExists.c.o  -o cmTC_72617 -rdynamic
CMakeFiles/cmTC_72617.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_72617.dir/build.make:97: recipe for target 'cmTC_72617' failed
make[1]: *** [cmTC_72617] Error 1
make[1]: Leaving directory '/home/cv/theiasfm/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_72617/fast' failed
make: *** [cmTC_72617/fast] Error 2

File /home/cv/theiasfm/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/cv/theiasfm/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_e38fb/fast"
/usr/bin/make -f CMakeFiles/cmTC_e38fb.dir/build.make CMakeFiles/cmTC_e38fb.dir/build
make[1]: Entering directory '/home/cv/theiasfm/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_e38fb.dir/CheckFunctionExists.c.o
/usr/bin/cc    -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_e38fb.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.5/Modules/CheckFunctionExists.c
Linking C executable cmTC_e38fb
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_e38fb.dir/link.txt --verbose=1
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_e38fb.dir/CheckFunctionExists.c.o  -o cmTC_e38fb -rdynamic -lpthreads
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_e38fb.dir/build.make:97: recipe for target 'cmTC_e38fb' failed
make[1]: *** [cmTC_e38fb] Error 1
make[1]: Leaving directory '/home/cv/theiasfm/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_e38fb/fast' failed
make: *** [cmTC_e38fb/fast] Error 2
```
my setup is ubuntu 16.04 64bit
