### ISSUE TITLE
Export of fisheye model scenes

### ISSUE THREAD

**Issue by bugakov** [sweeneychris/TheiaSfM#132]
Hello Chris,
Thanks for your library, it works fine with fisheye camera model with decent calibration.
We coudn`t yet find a way to densify the results in any MVS pipeline. Export works fine with pinhole model, but not with fisheye. Even if we undistort the scene before export.
Any suggestions please?

**Comment by sweeneychris** [comment]
As far as I know, there are no open source MVS pipelines that work on fisheye cameras. The projection model for a fisheye camera is different than a standard pinhole perspective camera and they cannot be easily reconciled by undistortion (that only removes the radial distortion -- it doesn't change the projection model).

**Comment by pmoulon** [comment]
[Micmac](https://2015.rmll.info/IMG/pdf/rmll-2015-deseilligny-v7.pdf) can work with pinhole image for SfM and MVS

**Comment by charlescva** [comment]
Confirmed, Micmac handles fisheye lense model using Tapas.  However, there was a bug in the MVS & NVM Export tools.  It was patched and I confirmed the patch works: http://forum-micmac.forumprod.com/apero2pmvs-and-apero2pnvm-t1457.html?sid=6c5513e85ebdf9c8a747005ae0d4285d
