### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by TheKiffer** [sweeneychris/TheiaSfM#140]
Hello,

First of all, apologies if this is a simple error, I am still getting acquainted with Ubuntu and cmake. Tried building in Ubuntu 16.04.1 LTS, followed the accompanying build instructions and I am running into the following error:

```
make -j2

...

[ 34%] Built target theia
Scanning dependencies of target find_common_tracks_in_views_test
[ 34%] Building CXX object src/theia/CMakeFiles/find_common_tracks_in_views_test.dir/test/test_main.cc.o
[ 34%] Building CXX object src/theia/CMakeFiles/find_common_tracks_in_views_test.dir/sfm/find_common_tracks_in_views_test.cc.o
make[2]: *** No rule to make target '/usr/lib/libf77blas.so', needed by 'bin/find_common_tracks_in_views_test'.  Stop.
CMakeFiles/Makefile2:1141: recipe for target 'src/theia/CMakeFiles/find_common_tracks_in_views_test.dir/all' failed
make[1]: *** [src/theia/CMakeFiles/find_common_tracks_in_views_test.dir/all] Error 2
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

```
I located the files within my system and the shared library is there.

```
$ locate libf77blas.so
/usr/lib/libf77blas.so
/usr/lib/libf77blas.so.3
/usr/lib/atlas-base/libf77blas.so
/usr/lib/atlas-base/libf77blas.so.3
/usr/lib/atlas-base/libf77blas.so.3.0
```
I am unsure how to move forward, is the error originating because I have two copies of the same library albeit in different locations?

Thanks,
Kris.

**Comment by sweeneychris** [comment]
Hi Kris,

Apologies for the delay. I do not have a good solution aside from either installing 1 version of blas on your system, or explicitly set the BLAS library you're using. Could you install Ceres okay?
