### ISSUE TITLE
theia::Feature

### ISSUE THREAD

**Issue by Drapegnik** [sweeneychris/TheiaSfM#141]
Hi! Please, can you explain what is the correspondence between [`theia::Feature`](https://github.com/sweeneychris/TheiaSfM/blob/master/src/theia/sfm/feature.h#L47) which we have, when extract features with `ReconstructionBuilder` and `theia::Keypoint`/(`Eigen::VectorXf` aka descriptors) which we have after `KeypointDetector` and `DescriptorExtractor`. Sorry, didn't find it in docs or comments in source code. Global problem: How I can get features (keypoint or/and descriptor) of 3d point after reconstruction. (I mean features for all 2d points, that corresponding one 3d point). Thanks!

**Comment by Drapegnik** [comment]
When I [`GetFeature`](https://github.com/sweeneychris/TheiaSfM/blob/master/src/theia/sfm/view.h#L81) of `View` for `Track` how I can compare it with some other features which I compute with [`DescriptorExtractor`](https://github.com/sweeneychris/TheiaSfM/blob/master/src/theia/image/descriptor/descriptor_extractor.h#L49)?

**Comment by sweeneychris** [comment]
The Keypoints and Eigen::VectorXf (descriptor) classes are only used for feature matching. After they are matched, only the keypoint location (i.e. theia::Feature) is stored. This is repeated for each image pair (aggregating a set of ImagePairMatch objects). The TrackBuilder class is then used for form tracks across many images.

**Comment by Drapegnik** [comment]
So, if I need to compute descriptor of 2d point which corresponding a 3d point (aka `Track`) I can create `theia::Keypoint` from `theia::Feature`, get `image_path` from `View` and compute descriptor for this keypoint, right? Or it can be made easier?

**Comment by sweeneychris** [comment]
Yes, I think that would be the best way

**Comment by Drapegnik** [comment]
Thanks! just in case: `Feature[0]` - is `x` coordinate and `Feature[1]` - is `y`?

**Comment by sweeneychris** [comment]
Exactly.

**Comment by Drapegnik** [comment]
One more question: If I can somehow limit number of extracting features? and How I can compare two descriptors? If you implement any functions for compute descriptor norm?

Thanks!

**Comment by sweeneychris** [comment]
Extracting features should be done with this handy class: https://github.com/sweeneychris/TheiaSfM/blob/master/src/theia/sfm/feature_extractor.h#L50

The descriptors are just Eigen::VectorXf. You can use the [distance tool](https://github.com/sweeneychris/TheiaSfM/blob/master/src/theia/matching/distance.h) to compute the L2 distance, or just operate directly on the descriptors as you would with normal eigen vectors.
