### ISSUE TITLE
Confusing PORSAC sampling strategy?

### ISSUE THREAD

**Issue by drinking-tea** [sweeneychris/TheiaSfM#144]
Hi Chris,

I found there is probably a mistake in how you implemented the PROSAC sampling algorithm.

According to the algorithm 1 in the original [PROSAC paper[Chum 2005]](http://cmp.felk.cvut.cz/~matas/papers/chum-prosac-cvpr05.pdf), the *if/else* statements are:

> *if* Tn' < t, sample m-1 points from U_n-1 and sample one point u_n

> *else*, sample m points from U_n.

But what you write in the `prosac_sampler.h` is exactly opposite:
```
if (t_n_prime < kth_sample_number_) {
        // Randomly sample m data points from the top n data points.
        std::vector<int> random_numbers;
        for (int i = 0; i < m; i++) {
            // Generate a random number that has not already been used.
            int rand_number;
            while (
                   std::find(random_numbers.begin(),
                             random_numbers.end(),
                             (rand_number = rand() % n)) != random_numbers.end()
                   ) {}
            
            random_numbers.push_back(rand_number);
            
            // Push the *unique* random index back.
            subset.push_back(sortedMatches[rand_number].queryIdx);
        }
    } else {
        std::vector<int> random_numbers;
        // Randomly sample m-1 data points from the top n-1 data points.
        for (int i = 0; i < m - 1; i++) {
            // Generate a random number that has not already been used.
            int rand_number;
            while (
                   std::find(random_numbers.begin(),
                             random_numbers.end(),
                             (rand_number = rand_number = rand() % (n - 1))) != random_numbers.end()
                   ) {}
            random_numbers.push_back(rand_number);
            
            // Push the *unique* random index back.
            subset.push_back(sortedMatches[rand_number].queryIdx);
        }
        // Make the last point from the nth position.
        subset.push_back(sortedMatches[n].queryIdx);
    }
```

Hope you don't mind me raise this issue, and is this a bug in your code or a wrong algorithm in the paper?

Best,
Ryan

**Comment by sweeneychris** [comment]
Hi Ryan, I'd need to take a look back through the paper to verify but I seem to remember a discussion with @vfragoso where we decided that the prosac paper had a typo and that this was the correct way to do it. 

@vfragoso can you verify the correct-ness of this code? It might be that I am misremembering.

**Comment by drinking-tea** [comment]
hi Chris, Thanks for your prompt reply! Yeah I think it's a quite simple if/else statement so it seems like you did it on purpose. Look forward to an accurate answer from vfragoso! --Best, Ryan

**Comment by vfragoso** [comment]
@drinking-tea Let me double check the paper and the code, it has been a while.

**Comment by sweeneychris** [comment]
Hi Ryan,

Thanks for such a detailed analysis!  Do you think you could do a real data experiment with this to concretely prove that the correct strategy results in (presumably) fewer iterations?  It should be *really* easy to set this up if you use one of the geometric estimators that call RANSAC methods  under the hood: https://github.com/sweeneychris/TheiaSfM/tree/master/src/theia/sfm/estimators

**Comment by vfragoso** [comment]
Hi Ryan,

I have one concern with your explanation. According to the algorithm 1 in Page 4, the first statement in Step 1 is to increase t. In your explanation above, you are not increasing and considering t=0 for the first iteration. If we follow that algorithm strictly, then in the first iteration t = 1.

I quickly scripted this in Python to understand this. This is what the plot shows: 

If T_N remains constant, then t_n_prime is larger than t, which makes t_n_prime >= t -- see the attached plot. 

![constant_t_n](https://cloud.githubusercontent.com/assets/565559/24420880/5c7a6154-13c2-11e7-9ca6-10d2c9eee59d.png)

If T_N is interpreted as the max_number of iterations, then t_n_prime can be less than t. The question is, if T_N is intended to be the max_number of iterations and if Theia uses T_N as such.

![decrease_t_n](https://cloud.githubusercontent.com/assets/565559/24420924/8f209b78-13c2-11e7-93d5-114bca05f762.png)

**Comment by drinking-tea** [comment]
Hi Chris, I am doing a project that applying PROSAC on solvePnP function.

I tried both `if/else` statements in different order quickly in my project(because the only difference is the sampling order), the algorithm in both orders quit at the 1st iteration with a correct-ish answer in most cases (90%).... **so the performance is almost same in my case**. I will try the Theia a bit later because I haven't installed it haha...

**Comment by sweeneychris** [comment]
@drinking-tea any updates on this?

**Comment by drinking-tea** [comment]
still working on the PROSAC implementation, but not this bit currently.... 

I drew the first graph provided by vfragoso by myself but still not sure. I checked another repo of prosac implementation, which is part of opencv 3.2(rho.cpp if you interested), and they have a comment in the opencv 3.2 prosac implementation following:
```
inline void   RHO_HEST_REFC::getPROSACSample(void){
    if(ctrl.i > ctrl.phEndI){
        /* FIXME: Dubious. Review. */
        rndSmpl(4, ctrl.smpl, ctrl.phNum);/* Used to be phMax */
    }else{
        rndSmpl(3, ctrl.smpl, ctrl.phNum-1);
        ctrl.smpl[3] = ctrl.phNum-1;
    }
}
```
I guess I will come back a bit later?...

**Comment by sweeneychris** [comment]
@drinking-tea I'm going to close this issue for now due to the ambiguity. feel free to reopen it if we see more evidence that the strategy is wrong.
