### ISSUE TITLE
LineEstimator Example should use the L1 or L2 error

### ISSUE THREAD

**Issue by iago-suarez** [sweeneychris/TheiaSfM#146]
Right now the RANSAC example uses a worn implementation of the LineEstimator. The error method is defined as follow:

```C++
  // Calculate the error as the y distance of the point to the line.
  double Error(const Point &point, const Line &line) const
  {
    return point.y - (line.m * point.x + line.b);
  }
```
But this leads to a measurement of the erroneous error as can be seen in the following image.
![image](https://cloud.githubusercontent.com/assets/7408877/25238790/99d260c2-25ee-11e7-94b4-b69936dfd66c.png)
On the left side we can see the original image, where noise is drawn in blue while the line points are green. On the right side the estimated model is draw with its inliers, and as you can see, all the points are classified as inliers because of the error function doesn't use the L1 or L2 norm to measure the distance. 

With the following change the results looks fine:
```C++
  // Calculate the error as the y distance of the point to the line.
  double Error(const Point &point, const Line &line) const
  {
    return std::abs(point.y - (line.m * point.x + line.b));
  }
```

Result:
![image](https://cloud.githubusercontent.com/assets/7408877/25239084/5954748a-25ef-11e7-8a2d-24285b80ae94.png)

**Comment by sweeneychris** [comment]
The two lines of code are exactly the same?

**Comment by sweeneychris** [comment]
Could you expand on what you mean? You posted the exact same code in both code snippets.

**Comment by iago-suarez** [comment]
Yes, sorry, it was a copy & paste mistake. The code above is that of the examples while the one below is code corrected.

**Comment by sweeneychris** [comment]
Could you please provide a link for the incorrect code you are referencing? I cannot find any instances of the LineEstimator which are doing what you are saying.

**Comment by iago-suarez** [comment]
Yes, of course, the error is in file:
https://github.com/sweeneychris/TheiaSfM/blob/master/docs/source/ransac.rst

I'm going to do a pull request with the little bugfix.

**Comment by sweeneychris** [comment]
Ah okay, so this is an error in the docs only, not the actual code. Thanks for the pointer! I will merge your pull request shortly.

**Comment by iago-suarez** [comment]
Yes, perfect! :ok_hand:
