### ISSUE TITLE
2D Panorama Stitching Example

### ISSUE THREAD

**Issue by skn123** [sweeneychris/TheiaSfM#149]
Hello, I was wondering if there is any example for building a 2D panorama (e.g., a monolithic IC image or a whole slide microscopy image) using TheiaSFM? The motions are purely translational with a single camera. Any help/pointers would be greatly helpful.

**Comment by sweeneychris** [comment]
Right now, Theia is only focused on geometry and so there are not any pano building or image processing algorithms in the library.
