### ISSUE TITLE
Blending map

### ISSUE THREAD

**Issue by tmac1002** [sweeneychris/TheiaSfM#150]
Hi, I used some UAV images to generate sparse point. However, the result map seemed blending. I am very confused. I just have no idea why this happened. Could you help me explain this situation or what exactly reasons caused this results. Thank you very much!
![blend_image](https://cloud.githubusercontent.com/assets/11924213/25466025/8c342b4a-2b38-11e7-9d0d-286860e9d57b.JPG)

**Comment by sweeneychris** [comment]
Please see the answers you have posted in the other forums, particularly about the radial distortion ambiguity as this is exactly what is happening.
