### ISSUE TITLE
Error compiling TheiaSfM with AKAZE

### ISSUE THREAD

**Issue by Tariq-Abuhashim** [sweeneychris/TheiaSfM#151]
Hi;  I get the following compile error:

[  0%] Building CXX object libraries/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
[  1%] Linking CXX static library ../../lib/libgtest.a
[  1%] Built target gtest
[  1%] Building CXX object libraries/gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
[  1%] Linking CXX static library ../../lib/libgtest_main.a
[  1%] Built target gtest_main
[  1%] Building CXX object libraries/akaze/CMakeFiles/akaze.dir/src/AKAZE.cpp.o
[  1%] Building CXX object libraries/akaze/CMakeFiles/akaze.dir/src/convolution.cpp.o
[  1%] Building CXX object libraries/akaze/CMakeFiles/akaze.dir/src/fed.cpp.o
[  1%] Building CXX object libraries/akaze/CMakeFiles/akaze.dir/src/nldiffusion_functions.cpp.o
/home/tariq/Dev/TheiaSfM/libraries/akaze/src/nldiffusion_functions.cpp: In function ‘void libAKAZE::halfsample_image(const RowMatrixXf&, libAKAZE::RowMatrixXf&)’:
/home/tariq/Dev/TheiaSfM/libraries/akaze/src/nldiffusion_functions.cpp:256:45: error: no match for ‘operator-=’ (operand types are ‘Eigen::internal::enable_if<true, Eigen::IndexedView<Eigen::Matrix<float, 1, -1>, Eigen::internal::SingleRange, double> >::type {aka Eigen::IndexedView<Eigen::Matrix<float, 1, -1>, Eigen::internal::SingleRange, double>}’ and ‘double’)
     y_kernel_mul(y_kernel_clamped_size - 1) -=
                                             ^
In file included from /home/tariq/Dev/eigen/build/include/eigen3/Eigen/Core:438:0,
                 from /home/tariq/Dev/eigen/build/include/eigen3/Eigen/Dense:1,
                 from /home/tariq/Dev/TheiaSfM/libraries/akaze/src/convolution.h:38,
                 from /home/tariq/Dev/TheiaSfM/libraries/akaze/src/nldiffusion_functions.cpp:28:
/home/tariq/Dev/eigen/build/include/eigen3/Eigen/src/Core/MatrixBase.h:161:14: note: candidate: template<class OtherDerived> Derived& Eigen::MatrixBase<Derived>::operator-=(const Eigen::MatrixBase<OtherDerived>&) [with OtherDerived = OtherDerived; Derived = Eigen::IndexedView<Eigen::Matrix<float, 1, -1>, Eigen::internal::SingleRange, double>]
     Derived& operator-=(const MatrixBase<OtherDerived>& other);
              ^
/home/tariq/Dev/eigen/build/include/eigen3/Eigen/src/Core/MatrixBase.h:161:14: note:   template argument deduction/substitution failed:
/home/tariq/Dev/TheiaSfM/libraries/akaze/src/nldiffusion_functions.cpp:256:45: note:   mismatched types ‘const Eigen::MatrixBase<Derived>’ and ‘double’
     y_kernel_mul(y_kernel_clamped_size - 1) -=
                                             ^
In file included from /home/tariq/Dev/eigen/build/include/eigen3/Eigen/Core:438:0,
                 from /home/tariq/Dev/eigen/build/include/eigen3/Eigen/Dense:1,
                 from /home/tariq/Dev/TheiaSfM/libraries/akaze/src/convolution.h:38,
                 from /home/tariq/Dev/TheiaSfM/libraries/akaze/src/nldiffusion_functions.cpp:28:
/home/tariq/Dev/eigen/build/include/eigen3/Eigen/src/Core/MatrixBase.h:479:46: note: candidate: template<class OtherDerived> Derived& Eigen::MatrixBase<Derived>::operator-=(const Eigen::ArrayBase<OtherDerived>&) [with OtherDerived = OtherDerived; Derived = Eigen::IndexedView<Eigen::Matrix<float, 1, -1>, Eigen::internal::SingleRange, double>]
     template<typename OtherDerived> Derived& operator-=(const ArrayBase<OtherDerived>& )
                                              ^
/home/tariq/Dev/eigen/build/include/eigen3/Eigen/src/Core/MatrixBase.h:479:46: note:   template argument deduction/substitution failed:
/home/tariq/Dev/TheiaSfM/libraries/akaze/src/nldiffusion_functions.cpp:256:45: note:   mismatched types ‘const Eigen::ArrayBase<Derived>’ and ‘double’
     y_kernel_mul(y_kernel_clamped_size - 1) -=
                                             ^
In file included from /home/tariq/Dev/eigen/build/include/eigen3/Eigen/Core:437:0,
                 from /home/tariq/Dev/eigen/build/include/eigen3/Eigen/Dense:1,
                 from /home/tariq/Dev/TheiaSfM/libraries/akaze/src/convolution.h:38,
                 from /home/tariq/Dev/TheiaSfM/libraries/akaze/src/nldiffusion_functions.cpp:28:
/home/tariq/Dev/eigen/build/include/eigen3/Eigen/src/Core/DenseBase.h:293:14: note: candidate: template<class OtherDerived> Derived& Eigen::DenseBase<Derived>::operator-=(const Eigen::EigenBase<OtherDerived>&) [with OtherDerived = OtherDerived; Derived = Eigen::IndexedView<Eigen::Matrix<float, 1, -1>, Eigen::internal::SingleRange, double>]
     Derived& operator-=(const EigenBase<OtherDerived> &other);
              ^
/home/tariq/Dev/eigen/build/include/eigen3/Eigen/src/Core/DenseBase.h:293:14: note:   template argument deduction/substitution failed:
/home/tariq/Dev/TheiaSfM/libraries/akaze/src/nldiffusion_functions.cpp:256:45: note:   mismatched types ‘const Eigen::EigenBase<Derived>’ and ‘double’
     y_kernel_mul(y_kernel_clamped_size - 1) -=
                                             ^

**Comment by sweeneychris** [comment]
What version of Eigen are you using? I recommend using the latest stable release.

**Comment by Tariq-Abuhashim** [comment]
I've just checked, I have the latest Eigen installed.
-- Found Eigen version 3.3.90:
I removed Eigen, and downloaded it again using : hg clone https://bitbucket.org/eigen/eigen/
Then, I recompiled Ceres, and received the same error when compiling Theia.
Should I compile Ceres as static or shared library? I did compile both as static.

**Comment by sweeneychris** [comment]
This is the latest stable release of Eigen: http://bitbucket.org/eigen/eigen/get/3.3.3.tar.bz2

**Comment by sweeneychris** [comment]
Static or shared should work fine for Ceres.

**Comment by Tariq-Abuhashim** [comment]
Thanks, I passed that error now, but then I get this error:

-----------------------------------------------------
Scanning dependencies of target theia
[  9%] Building CXX object src/theia/CMakeFiles/theia.dir/image/descriptor/akaze_descriptor.cc.o
In file included from /home/tariq/Dev/TheiaSfM/src/theia/image/descriptor/akaze_descriptor.cc:44:0:
/home/tariq/Dev/TheiaSfM/src/theia/image/image.h:67:29: error: ‘OpenImageIO’ does not name a type
   explicit FloatImage(const OpenImageIO::ImageBuf& image);
                             ^
/home/tariq/Dev/TheiaSfM/src/theia/image/image.h:67:50: error: expected unqualified-id before ‘&’ token
   explicit FloatImage(const OpenImageIO::ImageBuf& image);
                                                  ^
-----------------------------------------------------

So, I checked the OIIO name space, in OIIOversion.h. I had:  
#define OIIO_NAMESPACE_BEGIN namespace OpenImageIO_v1_8 {
I pulled this version from github at https://github.com/OpenImageIO/oiio

I fixed this issue, similarly, by replacing the most recent 1.8 version of OpenImageIO with the current stable one 1.7.14 and it all compiled successfully.

so, I am closing this issue.

Thank you.
