### ISSUE TITLE
triangulate for 1DSFM data

### ISSUE THREAD

**Issue by logmove** [sweeneychris/TheiaSfM#157]
Hi,
I have a solution for camera poses of 1DSFM data. Can I input the poses into Theia and do triangulation? E.g., can I replace the Theia's pose solution somewhere and use the input one for subsequent reconstruction?
Thanks a lot for any help.

**Comment by sweeneychris** [comment]
What format is your pose data in? If it is in e.g., Bundler file format then you can simply read in the bundle file as a Theia reconstruction and use this class to estimate the 3d points: https://github.com/sweeneychris/TheiaSfM/blob/master/src/theia/sfm/estimate_track.h#L54

**Comment by logmove** [comment]
@sweeneychris The format is simply a set of rotation and translation for each camera, returned by motion averaging algorithm, and I want to do triangulation for those points in the tracks.txt included in 1DSFM dataset. What is the easiest way to do so using Theia? Thanks.

**Comment by sweeneychris** [comment]
You can read in the tracks for the 1dsfm dataset using [this function](https://github.com/sweeneychris/TheiaSfM/blob/master/src/theia/io/read_1dsfm.h), then you'll want to populate the camera poses in the reconstruction with your input data. Each view in the reconstruction will have a name associated with the image filename in the 1dsfm dataset, so you can easily search for the associated views and set their camera poses. After that, you can use the function I linked above to estimate tracks.
