### ISSUE TITLE
Use Theia as external library

### ISSUE THREAD

**Issue by logmove** [sweeneychris/TheiaSfM#158]
Hi,
I have install Theia successfully, and would like to use it in my project. But when I try to include it in CMAKE
using `FIND_PACKAGE(THEIA REQUIRED)
INCLUDE_DIRECTORIES(${THEIA_INCLUDE_DIRS})`.
It reports errors as following:
![image](https://user-images.githubusercontent.com/29305317/27250882-c9524384-536c-11e7-8356-434807b78b47.png)
Could any one help? Thanks!

**Comment by sweeneychris** [comment]
Try using find_package(Theia) instead of THEIA
