### ISSUE TITLE
Reconstruction comparison gives worse performance than shown in the website

### ISSUE THREAD

**Issue by logmove** [sweeneychris/TheiaSfM#163]
Hi Chris,

I have run the build_1dsfm_reconstruction.cc and compared it to bundle.out using compare_reconstructions.cc. It seems the positions errors are always larger than those you shown in http://www.theia-sfm.org/performance.html.
The following is an example from Alamo. The median error 1.969149 is far larger than 0.37. For NYC_Library, the median error is 6.339193, also larger than 0.85. I also observed that, when converting bundle to theia reconstruction, not all points are restored.  In Alamo data, only 60845 point are read but from bundle.out we  known there are 239139 points. Can you see what is the problem? Thanks.

I0619 16:51:14.877007 17578 compare_reconstructions.cc:212] Number of cameras:
	Reconstruction 1: 761
	Reconstruction 2: 578
	Number of Common cameras: 556
I0619 16:51:14.877190 17578 compare_reconstructions.cc:225] Number of 3d points:
	Reconstruction 1: 60845
	Reconstruction 2: 156807
I0619 16:51:14.881799 17578 compare_reconstructions.cc:124] Rotation difference when aligning orientations:
Mean = 0.036277
Median = 0.014145
Histogram:
< 1.000000 = 555
[1.000000 - 2.000000) = 0 
[2.000000 - 5.000000) = 1 
[5.000000 - 10.000000) = 0 
[10.000000 - 15.000000) = 0 
[15.000000 - 20.000000) = 0 
[20.000000 - 45.000000) = 0 
I0619 16:51:14.923058 17578 compare_reconstructions.cc:170] Pose error:
Rotation Error:
Mean = 0.040236 
Median = 0.019529
Histogram:
< 1.000000 = 555
[1.000000 - 2.000000) = 0 
[2.000000 - 5.000000) = 1 
[5.000000 - 10.000000) = 0 
[10.000000 - 15.000000) = 0 
[15.000000 - 20.000000) = 0 
[20.000000 - 45.000000) = 0 

Position Error:
Mean = 2.971440 
Median = 1.969149
Histogram:
< 1.000000 = 97
[1.000000 - 5.000000) = 421 
[5.000000 - 10.000000) = 21 
[10.000000 - 50.000000) = 13 
[50.000000 - 100.000000) = 4 
[100.000000 - 1000.000000) = 0 
I0619 16:51:14.923220 17578 compare_reconstructions.cc:176] Focal length errors: 
Mean = 0.016828
Median = 0.007073
Histogram:
< 0.010000 = 336
[0.010000 - 0.050000) = 189 
[0.050000 - 0.200000) = 26 
[0.200000 - 0.500000) = 3 
[0.500000 - 1.000000) = 2 
[1.000000 - 10.000000) = 0 
[10.000000 - 100.000000) = 0

**Comment by logmove** [comment]
Hi Chris,
The configuration file I used is this: http://theia-sfm.org/build_1dsfm_reconstruction_flags.txt.

**Comment by sweeneychris** [comment]
If you play with the robust alignment threshold (it is one of the command line flags) then you'll get the website results. I usually used a threshold of 1.0 or 2.0
