### ISSUE TITLE
make error in image.cc

### ISSUE THREAD

**Issue by Feywell** [sweeneychris/TheiaSfM#164]
**## I have a trouble when I make theiaSFM.
as shown:**
/home/feywell/TheiaSfM-master/src/theia/image/image.cc: In member function ‘theia::FloatImage theia::FloatImage::ComputeGradient() const’:
/home/feywell/TheiaSfM-master/src/theia/image/image.cc:291:3: error: ‘abs’ is not a member of ‘OpenImageIO::v1_3::ImageBufAlgo’
   OpenImageIO::ImageBufAlgo::abs(gradient_x, gradient_x);
   ^
/home/feywell/TheiaSfM-master/src/theia/image/image.cc:291:3: note: suggested alternatives:
In file included from /usr/include/c++/4.8/cstdlib:72:0,
                 from /usr/include/c++/4.8/ext/string_conversions.h:41,
                 from /usr/include/c++/4.8/bits/basic_string.h:2815,
                 from /usr/include/c++/4.8/string:52,
                 from /usr/include/c++/4.8/bits/locale_classes.h:40,
                 from /usr/include/c++/4.8/bits/ios_base.h:41,
                 from /usr/include/c++/4.8/ios:42,
                 from /usr/include/c++/4.8/istream:38,
                 from /usr/include/c++/4.8/sstream:38,
                 from /usr/include/c++/4.8/complex:45,
                 from /usr/include/eigen3/Eigen/Core:28,
                 from /home/feywell/TheiaSfM-master/src/theia/image/image.h:38,
                 from /home/feywell/TheiaSfM-master/src/theia/image/image.cc:35:
/usr/include/stdlib.h:775:12: note:   ‘abs’
 extern int abs (int __x) __THROW __attribute__ ((__const__)) __wur;
            ^
In file included from /usr/include/eigen3/Eigen/Core:28:0,
                 from /home/feywell/TheiaSfM-master/src/theia/image/image.h:38,
                 from /home/feywell/TheiaSfM-master/src/theia/image/image.cc:35:
/usr/include/c++/4.8/complex:595:5: note:   ‘std::abs’
     abs(const complex<_Tp>& __z) { return __complex_abs(__z.__rep()); }
     ^
In file included from /usr/include/eigen3/Eigen/Core:368:0,
                 from /home/feywell/TheiaSfM-master/src/theia/image/image.h:38,
                 from /home/feywell/TheiaSfM-master/src/theia/image/image.cc:35:
/usr/include/eigen3/Eigen/src/Core/GlobalFunctions.h:50:3: note:   ‘Eigen::abs’
   EIGEN_ARRAY_DECLARE_GLOBAL_UNARY(abs,scalar_abs_op)
   ^
In file included from /usr/include/boost/ratio/ratio.hpp:36:0,
                 from /usr/include/boost/chrono/duration.hpp:41,
                 from /usr/include/boost/chrono/time_point.hpp:33,
                 from /usr/include/boost/thread/lock_types.hpp:22,
                 from /usr/include/boost/thread/pthread/thread_data.hpp:12,
                 from /usr/include/boost/thread/thread_only.hpp:17,
                 from /usr/include/boost/thread/thread.hpp:12,
                 from /usr/include/boost/thread.hpp:13,
                 from /usr/include/OpenImageIO/thread.h:64,
                 from /usr/include/OpenImageIO/imagebufalgo.h:45,
                 from /home/feywell/TheiaSfM-master/src/theia/image/image.cc:38:
/usr/include/boost/ratio/detail/mpl/abs.hpp:44:8: note:   ‘boost::mpl::abs’
 struct abs
        ^
/home/feywell/TheiaSfM-master/src/theia/image/image.cc:293:3: error: ‘abs’ is not a member of ‘OpenImageIO::v1_3::ImageBufAlgo’
   OpenImageIO::ImageBufAlgo::abs(gradient_y, gradient_y);
   ^
/home/feywell/TheiaSfM-master/src/theia/image/image.cc:293:3: note: suggested alternatives:
In file included from /usr/include/c++/4.8/cstdlib:72:0,
                 from /usr/include/c++/4.8/ext/string_conversions.h:41,
                 from /usr/include/c++/4.8/bits/basic_string.h:2815,
                 from /usr/include/c++/4.8/string:52,
                 from /usr/include/c++/4.8/bits/locale_classes.h:40,
                 from /usr/include/c++/4.8/bits/ios_base.h:41,
                 from /usr/include/c++/4.8/ios:42,
                 from /usr/include/c++/4.8/istream:38,
                 from /usr/include/c++/4.8/sstream:38,
                 from /usr/include/c++/4.8/complex:45,
                 from /usr/include/eigen3/Eigen/Core:28,
                 from /home/feywell/TheiaSfM-master/src/theia/image/image.h:38,
                 from /home/feywell/TheiaSfM-master/src/theia/image/image.cc:35:
/usr/include/stdlib.h:775:12: note:   ‘abs’
 extern int abs (int __x) __THROW __attribute__ ((__const__)) __wur;
            ^
In file included from /usr/include/eigen3/Eigen/Core:28:0,
                 from /home/feywell/TheiaSfM-master/src/theia/image/image.h:38,
                 from /home/feywell/TheiaSfM-master/src/theia/image/image.cc:35:
/usr/include/c++/4.8/complex:595:5: note:   ‘std::abs’
     abs(const complex<_Tp>& __z) { return __complex_abs(__z.__rep()); }
     ^
In file included from /usr/include/eigen3/Eigen/Core:368:0,
                 from /home/feywell/TheiaSfM-master/src/theia/image/image.h:38,
                 from /home/feywell/TheiaSfM-master/src/theia/image/image.cc:35:
/usr/include/eigen3/Eigen/src/Core/GlobalFunctions.h:50:3: note:   ‘Eigen::abs’
   EIGEN_ARRAY_DECLARE_GLOBAL_UNARY(abs,scalar_abs_op)
   ^
In file included from /usr/include/boost/ratio/ratio.hpp:36:0,
                 from /usr/include/boost/chrono/duration.hpp:41,
                 from /usr/include/boost/chrono/time_point.hpp:33,
                 from /usr/include/boost/thread/lock_types.hpp:22,
                 from /usr/include/boost/thread/pthread/thread_data.hpp:12,
                 from /usr/include/boost/thread/thread_only.hpp:17,
                 from /usr/include/boost/thread/thread.hpp:12,
                 from /usr/include/boost/thread.hpp:13,
                 from /usr/include/OpenImageIO/thread.h:64,
                 from /usr/include/OpenImageIO/imagebufalgo.h:45,
                 from /home/feywell/TheiaSfM-master/src/theia/image/image.cc:38:
/usr/include/boost/ratio/detail/mpl/abs.hpp:44:8: note:   ‘boost::mpl::abs’
 struct abs
        ^
In file included from /home/feywell/TheiaSfM-master/src/theia/image/image.cc:39:0:
/home/feywell/TheiaSfM-master/src/theia/image/image.cc: In member function ‘void theia::FloatImage::MedianFilter(int)’:
/home/feywell/TheiaSfM-master/src/theia/image/image.cc:308:9: error: ‘median_filter’ is not a member of ‘OpenImageIO::v1_3::ImageBufAlgo’
   CHECK(OpenImageIO::ImageBufAlgo::median_filter(image_, image_, patch_width));
         ^
[  8%] Building CXX object src/theia/CMakeFiles/theia.dir/io/read_bundler_files.cc.o
make[2]: *** [src/theia/CMakeFiles/theia.dir/image/image.cc.o] error1
make[2]: *** Waiting for unfinished tasks...
make[1]: *** [src/theia/CMakeFiles/theia.dir/all] error 2
make: *** [all] error 2

I hope you can answer my confusion.
Thank you!

**Comment by sweeneychris** [comment]
Please use the OpenImageIO v1.6 or more recent, as mentioned on the website: http://theia-sfm.org/building.html

**Comment by Feywell** [comment]
@sweeneychris  Thank you!
 I find I have a wrong version of OpenImageIO. I'm trying to update it.
Thank you very much!
