### ISSUE TITLE
Bug in uncalibrated twoview - estimation

### ISSUE THREAD

**Issue by alexlocher** [sweeneychris/TheiaSfM#173]
Hi Chris
I finally upgraded to the newest Theia - Version ;) - thanks a lot for all the effort and time you are putting in this great library! 
I just found an issue in the un-calibrated twoview estimation: When normalizing the feature correspondences, the cameras focal lenght is set to a medium FOV. As a result all features are normalized by this focal lenght. The sampson threshold on the other hand is not normalized by this focal lenght (since its uncalibrated...) as a result the geometric veryfication is completely broken :grimacing: 

Here is a possible fix:

_in estimate_twoview_info.cc line 73_
```c++
  Camera camera1, camera2;
  camera1.SetFromCameraIntrinsicsPriors(prior1);
  camera2.SetFromCameraIntrinsicsPriors(prior2);
  // reset focal lengths in uncalibrated case, otherwise the ransac thresholds are wrong
  if (!prior1.focal_length.is_set || !prior2.focal_length.is_set){
    camera1.SetFocalLength(1.0);
    camera2.SetFocalLength(1.0);
  }
  normalized_correspondences->reserve(correspondences.size());
```

**Comment by sweeneychris** [comment]
You're totally right! Great catch, and thanks for the bug report. I uploaded your fix to the main repo now: https://github.com/sweeneychris/TheiaSfM/commit/9edf81a8835927fa77c3781fa8fe1116bab3c37a
