### ISSUE TITLE
Application convert_nvm_file causes SegmentaionFault

### ISSUE THREAD

**Issue by benjaminsmithWVU** [sweeneychris/TheiaSfM#174]
Hi,

I ran into an issue when running the convert_nvm_file application that Theia has. When trying to convert nvm models to Theia reconstructions, the application results in a Segmentation fault. I have a database of 72 models, and it seems to SegFault on seemingly all of them (or at least, the dozen or so I have tried). Below is the output received when running this application.

I have traced down the source of this Segmentation fault, and have created a temporary fix. The issue stems from  import_nvm_file.cc in the ImportNVMFile function. 
Line 140: `const TrackId track_id = reconstruction->AddTrack(features);`
when a track has the same view twice, the track_id becomes 4294967295, unsigned int max

Line 141: `Track* track = reconstruction->MutableTrack(track_id);`
Results with track being 0

Line 142: `track->SetEstimated(true);`
Then this causes the segmentation fault due to 'is_estimated_' being nonexistent

This segmentation fault can be avoided by encompassing with an if statement as such (in comments)
```
  // Add all tracks to the reconstruction and set the 3d position.
  for (int i = 0; i < vsfm_reconstruction.point_data.size(); i++) {
    Eigen::Vector4f point(vsfm_reconstruction.point_data[i].xyz[0],
                          vsfm_reconstruction.point_data[i].xyz[1],
                          vsfm_reconstruction.point_data[i].xyz[2],
                          1.0);
    Eigen::Vector3i color(vsfm_reconstruction.point_colors[3 * i],
                          vsfm_reconstruction.point_colors[3 * i + 1],
                          vsfm_reconstruction.point_colors[3 * i + 2]);
    const auto& features = FindOrDie(tracks, i);
    const TrackId track_id = reconstruction->AddTrack(features);
    Track* track = reconstruction->MutableTrack(track_id);
    // Ensure that even if track was added it does not segfault.
    //if (track != 0) {
      track->SetEstimated(true);
      *track->MutablePoint() = point.cast<double>();
      *track->MutableColor() = color.cast<uint8_t>();
    //}
  }
```

However, this is less than ideal, and I do not know if it has other repercussions such as missing tracks. I would not think that the segmentation fault should occur in general even if a track already exists - and I am not sure that the track should even already exist. Is this fault an issue within Theia or the NVM models themselves?

Thank you.

> Loading cameras/points: /path/to/model.nvm
107 cameras; 1421 3D points; 14586 projections
I0711 12:54:43.590102   575 import_nvm_file.cc:96] Adding view 49605543_541236890.jpg to the reconstruction.
I0711 12:54:43.590229   575 import_nvm_file.cc:96] Adding view 05948761_5129341717.jpg to the reconstruction.
I0711 12:54:43.590253   575 import_nvm_file.cc:96] Adding view 36131601_12522641.jpg to the reconstruction.
I0711 12:54:43.590271   575 import_nvm_file.cc:96] Adding view 21881860_5284125707.jpg to the reconstruction.
I0711 12:54:43.590288   575 import_nvm_file.cc:96] Adding view 05966051_25379828.jpg to the reconstruction.
I0711 12:54:43.590308   575 import_nvm_file.cc:96] Adding view 20347250_1353298031.jpg to the reconstruction.
I0711 12:54:43.590334   575 import_nvm_file.cc:96] Adding view 06637841_2619475895.jpg to the reconstruction.
I0711 12:54:43.590350   575 import_nvm_file.cc:96] Adding view 06087940_1877655223.jpg to the reconstruction.
I0711 12:54:43.590366   575 import_nvm_file.cc:96] Adding view 06277431_8078721537.jpg to the reconstruction.
I0711 12:54:43.590381   575 import_nvm_file.cc:96] Adding view 06674530_4150804947.jpg to the reconstruction.
I0711 12:54:43.590396   575 import_nvm_file.cc:96] Adding view 06608521_120178878.jpg to the reconstruction.
I0711 12:54:43.590416   575 import_nvm_file.cc:96] Adding view 92654977_7011794349.jpg to the reconstruction.
I0711 12:54:43.590432   575 import_nvm_file.cc:96] Adding view 35415938_6089061446.jpg to the reconstruction.
I0711 12:54:43.590448   575 import_nvm_file.cc:96] Adding view 36563006_583864874.jpg to the reconstruction.
I0711 12:54:43.590463   575 import_nvm_file.cc:96] Adding view 36708263_156070087.jpg to the reconstruction.
I0711 12:54:43.590478   575 import_nvm_file.cc:96] Adding view 36265660_5395861234.jpg to the reconstruction.
I0711 12:54:43.590493   575 import_nvm_file.cc:96] Adding view 79591223_2148944246.jpg to the reconstruction.
I0711 12:54:43.590508   575 import_nvm_file.cc:96] Adding view 07538171_3264650654.jpg to the reconstruction.
I0711 12:54:43.590523   575 import_nvm_file.cc:96] Adding view 20377329_6866607614.jpg to the reconstruction.
I0711 12:54:43.590538   575 import_nvm_file.cc:96] Adding view 35411386_2916903845.jpg to the reconstruction.
I0711 12:54:43.590553   575 import_nvm_file.cc:96] Adding view 07664792_4950657491.jpg to the reconstruction.
I0711 12:54:43.590569   575 import_nvm_file.cc:96] Adding view 07821224_3037126354.jpg to the reconstruction.
I0711 12:54:43.590584   575 import_nvm_file.cc:96] Adding view 36030418_11387052795.jpg to the reconstruction.
I0711 12:54:43.590605   575 import_nvm_file.cc:96] Adding view 64909810_3036539539.jpg to the reconstruction.
I0711 12:54:43.590621   575 import_nvm_file.cc:96] Adding view 20226075_4906597565.jpg to the reconstruction.
I0711 12:54:43.590637   575 import_nvm_file.cc:96] Adding view 20341584_13961076165.jpg to the reconstruction.
I0711 12:54:43.590652   575 import_nvm_file.cc:96] Adding view 20828328_8776138916.jpg to the reconstruction.
I0711 12:54:43.590667   575 import_nvm_file.cc:96] Adding view 20934508_1470709058.jpg to the reconstruction.
I0711 12:54:43.590682   575 import_nvm_file.cc:96] Adding view 36779331_9549583791.jpg to the reconstruction.
I0711 12:54:43.590697   575 import_nvm_file.cc:96] Adding view 21612422_4465415247.jpg to the reconstruction.
I0711 12:54:43.590710   575 import_nvm_file.cc:96] Adding view 21629862_1808025680.jpg to the reconstruction.
I0711 12:54:43.590725   575 import_nvm_file.cc:96] Adding view 21737587_25379717.jpg to the reconstruction.
I0711 12:54:43.590739   575 import_nvm_file.cc:96] Adding view 36743958_5245009019.jpg to the reconstruction.
I0711 12:54:43.590754   575 import_nvm_file.cc:96] Adding view 93761383_6977045136.jpg to the reconstruction.
I0711 12:54:43.590768   575 import_nvm_file.cc:96] Adding view 21772192_4202528290.jpg to the reconstruction.
I0711 12:54:43.590782   575 import_nvm_file.cc:96] Adding view 48867705_4508160594.jpg to the reconstruction.
I0711 12:54:43.590796   575 import_nvm_file.cc:96] Adding view 21841750_306879392.jpg to the reconstruction.
I0711 12:54:43.590811   575 import_nvm_file.cc:96] Adding view 34693823_5112980665.jpg to the reconstruction.
I0711 12:54:43.590826   575 import_nvm_file.cc:96] Adding view 21985332_12113196946.jpg to the reconstruction.
I0711 12:54:43.590839   575 import_nvm_file.cc:96] Adding view 92254881_3211407701.jpg to the reconstruction.
I0711 12:54:43.590853   575 import_nvm_file.cc:96] Adding view 21992962_4254933066.jpg to the reconstruction.
I0711 12:54:43.590867   575 import_nvm_file.cc:96] Adding view 49633888_197568437.jpg to the reconstruction.
I0711 12:54:43.590881   575 import_nvm_file.cc:96] Adding view 22234709_1440870643.jpg to the reconstruction.
I0711 12:54:43.590895   575 import_nvm_file.cc:96] Adding view 34637970_2645665653.jpg to the reconstruction.
I0711 12:54:43.590909   575 import_nvm_file.cc:96] Adding view 49489680_3735766644.jpg to the reconstruction.
I0711 12:54:43.590924   575 import_nvm_file.cc:96] Adding view 49635243_6819727746.jpg to the reconstruction.
I0711 12:54:43.590939   575 import_nvm_file.cc:96] Adding view 35027952_9899512864.jpg to the reconstruction.
I0711 12:54:43.590961   575 import_nvm_file.cc:96] Adding view 35269753_4102880199.jpg to the reconstruction.
I0711 12:54:43.590978   575 import_nvm_file.cc:96] Adding view 35312948_12721955114.jpg to the reconstruction.
I0711 12:54:43.590993   575 import_nvm_file.cc:96] Adding view 36132438_3396711096.jpg to the reconstruction.
I0711 12:54:43.591008   575 import_nvm_file.cc:96] Adding view 36744416_3921137323.jpg to the reconstruction.
I0711 12:54:43.591022   575 import_nvm_file.cc:96] Adding view 49596187_3930713316.jpg to the reconstruction.
I0711 12:54:43.591037   575 import_nvm_file.cc:96] Adding view 50307941_5349240359.jpg to the reconstruction.
I0711 12:54:43.591049   575 import_nvm_file.cc:96] Adding view 50886497_2440446287.jpg to the reconstruction.
I0711 12:54:43.591063   575 import_nvm_file.cc:96] Adding view 50937237_85807053.jpg to the reconstruction.
I0711 12:54:43.591078   575 import_nvm_file.cc:96] Adding view 51213319_9725989335.jpg to the reconstruction.
I0711 12:54:43.591092   575 import_nvm_file.cc:96] Adding view 63321350_4235096954.jpg to the reconstruction.
I0711 12:54:43.591106   575 import_nvm_file.cc:96] Adding view 63357427_7278834966.jpg to the reconstruction.
I0711 12:54:43.591120   575 import_nvm_file.cc:96] Adding view 63383705_2030183875.jpg to the reconstruction.
I0711 12:54:43.591133   575 import_nvm_file.cc:96] Adding view 63437117_2459667446.jpg to the reconstruction.
I0711 12:54:43.591147   575 import_nvm_file.cc:96] Adding view 63585920_7640997514.jpg to the reconstruction.
I0711 12:54:43.591161   575 import_nvm_file.cc:96] Adding view 94083842_2909938682.jpg to the reconstruction.
I0711 12:54:43.591174   575 import_nvm_file.cc:96] Adding view 63948572_3962343208.jpg to the reconstruction.
I0711 12:54:43.591188   575 import_nvm_file.cc:96] Adding view 63963177_2062835847.jpg to the reconstruction.
I0711 12:54:43.591203   575 import_nvm_file.cc:96] Adding view 64022465_8776051244.jpg to the reconstruction.
I0711 12:54:43.591217   575 import_nvm_file.cc:96] Adding view 64593270_7914894836.jpg to the reconstruction.
I0711 12:54:43.591230   575 import_nvm_file.cc:96] Adding view 64832831_3100244299.jpg to the reconstruction.
I0711 12:54:43.591244   575 import_nvm_file.cc:96] Adding view 64979229_4228291949.jpg to the reconstruction.
I0711 12:54:43.591259   575 import_nvm_file.cc:96] Adding view 65027389_2030168985.jpg to the reconstruction.
I0711 12:54:43.591272   575 import_nvm_file.cc:96] Adding view 93541173_6279783404.jpg to the reconstruction.
I0711 12:54:43.591286   575 import_nvm_file.cc:96] Adding view 65063735_257279659.jpg to the reconstruction.
I0711 12:54:43.591300   575 import_nvm_file.cc:96] Adding view 77524000_182881928.jpg to the reconstruction.
I0711 12:54:43.591315   575 import_nvm_file.cc:96] Adding view 77534467_6293753994.jpg to the reconstruction.
I0711 12:54:43.591328   575 import_nvm_file.cc:96] Adding view 77572440_3242933628.jpg to the reconstruction.
I0711 12:54:43.591342   575 import_nvm_file.cc:96] Adding view 78263405_3483872567.jpg to the reconstruction.
I0711 12:54:43.591356   575 import_nvm_file.cc:96] Adding view 77594310_1360164609.jpg to the reconstruction.
I0711 12:54:43.591370   575 import_nvm_file.cc:96] Adding view 77594466_3037373940.jpg to the reconstruction.
I0711 12:54:43.591384   575 import_nvm_file.cc:96] Adding view 77667418_3094402807.jpg to the reconstruction.
I0711 12:54:43.591398   575 import_nvm_file.cc:96] Adding view 77724307_3804285469.jpg to the reconstruction.
I0711 12:54:43.591413   575 import_nvm_file.cc:96] Adding view 78122934_4702542080.jpg to the reconstruction.
I0711 12:54:43.591426   575 import_nvm_file.cc:96] Adding view 78778061_337029918.jpg to the reconstruction.
I0711 12:54:43.591439   575 import_nvm_file.cc:96] Adding view 78179323_4769718542.jpg to the reconstruction.
I0711 12:54:43.591454   575 import_nvm_file.cc:96] Adding view 78430097_5377535767.jpg to the reconstruction.
I0711 12:54:43.591469   575 import_nvm_file.cc:96] Adding view 78804941_2852087394.jpg to the reconstruction.
I0711 12:54:43.591483   575 import_nvm_file.cc:96] Adding view 79081330_203558056.jpg to the reconstruction.
I0711 12:54:43.591497   575 import_nvm_file.cc:96] Adding view 79085269_2148939860.jpg to the reconstruction.
I0711 12:54:43.591511   575 import_nvm_file.cc:96] Adding view 79318823_1064442145.jpg to the reconstruction.
I0711 12:54:43.591534   575 import_nvm_file.cc:96] Adding view 79414617_4202524392.jpg to the reconstruction.
I0711 12:54:43.591564   575 import_nvm_file.cc:96] Adding view 79494896_222636840.jpg to the reconstruction.
I0711 12:54:43.591583   575 import_nvm_file.cc:96] Adding view 79531619_4471109530.jpg to the reconstruction.
I0711 12:54:43.591598   575 import_nvm_file.cc:96] Adding view 79596794_7704682658.jpg to the reconstruction.
I0711 12:54:43.591612   575 import_nvm_file.cc:96] Adding view 79631808_4470354201.jpg to the reconstruction.
I0711 12:54:43.591627   575 import_nvm_file.cc:96] Adding view 79650600_5215389440.jpg to the reconstruction.
I0711 12:54:43.591641   575 import_nvm_file.cc:96] Adding view 91731237_3036539665.jpg to the reconstruction.
I0711 12:54:43.591655   575 import_nvm_file.cc:96] Adding view 91843843_609202159.jpg to the reconstruction.
I0711 12:54:43.591670   575 import_nvm_file.cc:96] Adding view 91894230_6235974684.jpg to the reconstruction.
I0711 12:54:43.591684   575 import_nvm_file.cc:96] Adding view 92458724_4687101186.jpg to the reconstruction.
I0711 12:54:43.591716   575 import_nvm_file.cc:96] Adding view 92494954_4465415763.jpg to the reconstruction.
I0711 12:54:43.591730   575 import_nvm_file.cc:96] Adding view 92826379_5856156700.jpg to the reconstruction.
I0711 12:54:43.591744   575 import_nvm_file.cc:96] Adding view 92906247_174191543.jpg to the reconstruction.
I0711 12:54:43.591759   575 import_nvm_file.cc:96] Adding view 93326214_2459661986.jpg to the reconstruction.
I0711 12:54:43.591774   575 import_nvm_file.cc:96] Adding view 93365371_6060374774.jpg to the reconstruction.
I0711 12:54:43.591789   575 import_nvm_file.cc:96] Adding view 93376263_3861316263.jpg to the reconstruction.
I0711 12:54:43.591802   575 import_nvm_file.cc:96] Adding view 93465732_6060375014.jpg to the reconstruction.
I0711 12:54:43.591817   575 import_nvm_file.cc:96] Adding view 93545934_5315436898.jpg to the reconstruction.
I0711 12:54:43.591831   575 import_nvm_file.cc:96] Adding view 93835793_6059825407.jpg to the reconstruction.
I0711 12:54:43.591845   575 import_nvm_file.cc:96] Adding view 93891631_8684053031.jpg to the reconstruction.
W0711 12:54:43.593525   575 reconstruction.cc:294] Cannot add a track that contains the same view twice to the reconstruction.
Segmentation fault (core dumped)

**Comment by sweeneychris** [comment]
This commit should catch it: https://review.gerrithub.io/#/c/370397/

If your tracks contain the same view twice, then you need to catch that in your own code since the Track class is highly dependent on having one observation per image. But this commit should prevent a segfault at least
