### ISSUE TITLE
Incremental Reconstruction Initialization Criterion reasoning

### ISSUE THREAD

**Issue by an-kumar** [sweeneychris/TheiaSfM#176]
I'm looking at the OrderViewPairsByInitializationCriterion in the Incremental Reconstruction pipeline. In it, the comments say that you are looking for the view pair that is least well-modelled for by a homography (though it is constrained such that the view pair still have at least some threshold of verified matches). What is the reasoning for this? Is there a good reason to believe that view pairs that are poorly modelled by a homography are particularly good for initializing a reconstruction?

Thanks!

**Comment by sweeneychris** [comment]
A homography will accurately describe the motion between two views in one of two scenarios 1) rotation-only motion (or very small baseline) 2) the correspondences may be approximated as lying on a single plane. The first is actually a special case of the second with the plane at infinity. 

For initializing incremental sfm, you want a pair of views that exhibits strong parallax and has a large enough baseline between the views that 3d points can be accurately triangulated. That won't be the case for rotation-only or small baseline motion, so we compare the homography inliers vs essential matrix inliers to determine which pairs of views have enough parallax for stable initialization.
