### ISSUE TITLE
sim_tansform_partial_rotation_test failed when "cmake test", but passed when is run alone.

### ISSUE THREAD

**Issue by Tariq-Abuhashim** [sweeneychris/TheiaSfM#177]
Result of    make test
99% tests passed, 1 tests failed out of 94
Total Test time (real) =  57.67 sec
The following tests FAILED:
	 70 - sim_transform_partial_rotation_test (Failed)
Errors while running CTest
Makefile:61: recipe for target 'test' failed
make: *** [test] Error 8

Result of    ./bin/sim_transform_partial_rotation_test
[==========] Running 5 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 5 tests from SimTransformPartialRotationTest
[ RUN      ] SimTransformPartialRotationTest.Basic
[       OK ] SimTransformPartialRotationTest.Basic (0 ms)
[ RUN      ] SimTransformPartialRotationTest.NoRotation
[       OK ] SimTransformPartialRotationTest.NoRotation (0 ms)
[ RUN      ] SimTransformPartialRotationTest.NoTranslation
[       OK ] SimTransformPartialRotationTest.NoTranslation (0 ms)
[ RUN      ] SimTransformPartialRotationTest.NoiseTest
[       OK ] SimTransformPartialRotationTest.NoiseTest (0 ms)
[ RUN      ] SimTransformPartialRotationTest.IncorrectAxisTest
[       OK ] SimTransformPartialRotationTest.IncorrectAxisTest (3 ms)
[----------] 5 tests from SimTransformPartialRotationTest (3 ms total)

[----------] Global test environment tear-down
[==========] 5 tests from 1 test case ran. (4 ms total)
[  PASSED  ] 5 tests.

**Comment by sweeneychris** [comment]
This is quite odd, but I would not worry about it much if you are just using the SfM pipelines -- this function is not used in any pipelines currently so you may safely proceed.
