### ISSUE TITLE
EstimateSimilarityTransformation2D3D() not working

### ISSUE THREAD

**Issue by cdcseacave** [sweeneychris/TheiaSfM#183]
EstimateSimilarityTransformation2D3D functionality, implementing your paper _gDLS: A Scalable Solution to the Generalized Pose And Scale_, doesn't seem to work. The integrated test is working only for the one hard-coded similarity transformation, and the functionality doesn't seem to be used anywhere in the entire library.

Can you pls confirm that it is not working or am I testing it wrong?

**Comment by sweeneychris** [comment]
I am very confident this algorithm works. The code has been used in several
of my own publications and has been used by other researchers successfully:
https://arxiv.org/abs/1702.08601

The way that the similarity transformation is applied is slightly different
than normal so please pay attention to the setup.

**Comment by cdcseacave** [comment]
What puzzles me is why the synthetic test fails when altering the hard-coded similarity transformation. The camera and correspondences setup seems general.

**Comment by cdcseacave** [comment]
I can confirm it is working also with random similarity transformations; all I needed to do is a clean-up and rebuild of the project.
