### ISSUE TITLE
Problems related to OpenImageIO while compiling Theia

### ISSUE THREAD

**Issue by saihv** [sweeneychris/TheiaSfM#184]
I am trying to run 'make' on Theia after gathering all the dependencies. According to FindOpenImageIO.cmake, it looks like the OIIO include directory needs to be the one that contains `OpenImageIO/imageio.h`, so I ran the `make` command with the flag `-DOPENIMAGEIO_INCLUDE_DIR=<oiio_path>/src/include/ `. While `cmake` succeeds with this, `make` fails with the message:

`/home/sai/software/libraries/oiio-Release-1.7.17/src/include/OpenImageIO/imageio.h:58:25: fatal error: oiioversion.h: No such file or directory`

`oiioversion.h` is located in an altogether different directory inside the OIIO folders (build/include) and it seems like there is no link between both imageio.h and oiioversion.h. I've tried with both the stable 1.8 release and a stable 1.7 release of OIIO. was hoping someone could point out what I am doing wrong while configuring OIIO. Thanks!

**Comment by sweeneychris** [comment]
Did you install the OpenImageIO library or just build it? If you installed it then all the necessary files and libs should be automatically found by Theia.

**Comment by saihv** [comment]
Apologies for the late reply: you're right, I did forget the install step in OpenImageIO: it worked after I manually updated `PATH` and `LD_LIBRARY_PATH` with the `bin` and `lib` folders from OIIO. Thank you!
