### ISSUE TITLE
./bin/sim_transform_partial_rotation_test failed

### ISSUE THREAD

**Issue by kevin0932** [sweeneychris/TheiaSfM#185]
"""
[==========] Running 5 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 5 tests from SimTransformPartialRotationTest
[ RUN      ] SimTransformPartialRotationTest.Basic
[       OK ] SimTransformPartialRotationTest.Basic (0 ms)
[ RUN      ] SimTransformPartialRotationTest.NoRotation
[       OK ] SimTransformPartialRotationTest.NoRotation (0 ms)
[ RUN      ] SimTransformPartialRotationTest.NoTranslation
[       OK ] SimTransformPartialRotationTest.NoTranslation (0 ms)
[ RUN      ] SimTransformPartialRotationTest.NoiseTest
[       OK ] SimTransformPartialRotationTest.NoiseTest (1 ms)
[ RUN      ] SimTransformPartialRotationTest.IncorrectAxisTest
/home/kevin/devel_lib/SfM/TheiaSfM/src/theia/sfm/pose/sim_transform_partial_rotation_test.cc:144: Failure
Value of: matched_transform
  Actual: false
Expected: true
/home/kevin/devel_lib/SfM/TheiaSfM/src/theia/sfm/pose/sim_transform_partial_rotation_test.cc:144: Failure
Value of: matched_transform
  Actual: false
Expected: true
/home/kevin/devel_lib/SfM/TheiaSfM/src/theia/sfm/pose/sim_transform_partial_rotation_test.cc:144: Failure
Value of: matched_transform
  Actual: false
Expected: true
/home/kevin/devel_lib/SfM/TheiaSfM/src/theia/sfm/pose/sim_transform_partial_rotation_test.cc:144: Failure
Value of: matched_transform
  Actual: false
Expected: true
/home/kevin/devel_lib/SfM/TheiaSfM/src/theia/sfm/pose/sim_transform_partial_rotation_test.cc:144: Failure
Value of: matched_transform
  Actual: false
Expected: true
/home/kevin/devel_lib/SfM/TheiaSfM/src/theia/sfm/pose/sim_transform_partial_rotation_test.cc:144: Failure
Value of: matched_transform
  Actual: false
Expected: true
/home/kevin/devel_lib/SfM/TheiaSfM/src/theia/sfm/pose/sim_transform_partial_rotation_test.cc:144: Failure
Value of: matched_transform
  Actual: false
Expected: true
/home/kevin/devel_lib/SfM/TheiaSfM/src/theia/sfm/pose/sim_transform_partial_rotation_test.cc:144: Failure
Value of: matched_transform
  Actual: false
Expected: true
/home/kevin/devel_lib/SfM/TheiaSfM/src/theia/sfm/pose/sim_transform_partial_rotation_test.cc:144: Failure
Value of: matched_transform
  Actual: false
Expected: true
/home/kevin/devel_lib/SfM/TheiaSfM/src/theia/sfm/pose/sim_transform_partial_rotation_test.cc:144: Failure
Value of: matched_transform
  Actual: false
Expected: true
/home/kevin/devel_lib/SfM/TheiaSfM/src/theia/sfm/pose/sim_transform_partial_rotation_test.cc:144: Failure
Value of: matched_transform
  Actual: false
Expected: true
/home/kevin/devel_lib/SfM/TheiaSfM/src/theia/sfm/pose/sim_transform_partial_rotation_test.cc:144: Failure
Value of: matched_transform
  Actual: false
Expected: true
/home/kevin/devel_lib/SfM/TheiaSfM/src/theia/sfm/pose/sim_transform_partial_rotation_test.cc:144: Failure
Value of: matched_transform
  Actual: false
Expected: true
/home/kevin/devel_lib/SfM/TheiaSfM/src/theia/sfm/pose/sim_transform_partial_rotation_test.cc:144: Failure
Value of: matched_transform
  Actual: false
Expected: true
/home/kevin/devel_lib/SfM/TheiaSfM/src/theia/sfm/pose/sim_transform_partial_rotation_test.cc:144: Failure
Value of: matched_transform
  Actual: false
Expected: true
/home/kevin/devel_lib/SfM/TheiaSfM/src/theia/sfm/pose/sim_transform_partial_rotation_test.cc:144: Failure
Value of: matched_transform
  Actual: false
Expected: true
/home/kevin/devel_lib/SfM/TheiaSfM/src/theia/sfm/pose/sim_transform_partial_rotation_test.cc:144: Failure
Value of: matched_transform
  Actual: false
Expected: true
/home/kevin/devel_lib/SfM/TheiaSfM/src/theia/sfm/pose/sim_transform_partial_rotation_test.cc:144: Failure
Value of: matched_transform
  Actual: false
Expected: true
/home/kevin/devel_lib/SfM/TheiaSfM/src/theia/sfm/pose/sim_transform_partial_rotation_test.cc:144: Failure
Value of: matched_transform
  Actual: false
Expected: true
/home/kevin/devel_lib/SfM/TheiaSfM/src/theia/sfm/pose/sim_transform_partial_rotation_test.cc:144: Failure
Value of: matched_transform
  Actual: false
Expected: true
/home/kevin/devel_lib/SfM/TheiaSfM/src/theia/sfm/pose/sim_transform_partial_rotation_test.cc:144: Failure
Value of: matched_transform
  Actual: false
Expected: true
/home/kevin/devel_lib/SfM/TheiaSfM/src/theia/sfm/pose/sim_transform_partial_rotation_test.cc:144: Failure
Value of: matched_transform
  Actual: false
Expected: true
/home/kevin/devel_lib/SfM/TheiaSfM/src/theia/sfm/pose/sim_transform_partial_rotation_test.cc:144: Failure
Value of: matched_transform
  Actual: false
Expected: true
/home/kevin/devel_lib/SfM/TheiaSfM/src/theia/sfm/pose/sim_transform_partial_rotation_test.cc:144: Failure
Value of: matched_transform
  Actual: false
Expected: true
/home/kevin/devel_lib/SfM/TheiaSfM/src/theia/sfm/pose/sim_transform_partial_rotation_test.cc:144: Failure
Value of: matched_transform
  Actual: false
Expected: true
/home/kevin/devel_lib/SfM/TheiaSfM/src/theia/sfm/pose/sim_transform_partial_rotation_test.cc:144: Failure
Value of: matched_transform
  Actual: false
Expected: true
[  FAILED  ] SimTransformPartialRotationTest.IncorrectAxisTest (2 ms)
[----------] 5 tests from SimTransformPartialRotationTest (3 ms total)

[----------] Global test environment tear-down
[==========] 5 tests from 1 test case ran. (4 ms total)
[  PASSED  ] 4 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] SimTransformPartialRotationTest.IncorrectAxisTest

 1 FAILED TEST
"""

It is shown that Theia was built successfully but I met the above test failure. Does it matter if I want to use the Global SfM Pipeline? Thanks a lot!

**Comment by sweeneychris** [comment]
No, this module is not used in the SfM pipelines

**Comment by kevin0932** [comment]
@sweeneychris  Thanks a lot for your confirmation.

Besides the above test failure, I also met with two other failure tests:

16 - normalized_graph_cut_test (Failed)

"""

  [==========] Running 3 tests from 1 test case.
  [----------] Global test environment set-up.
  [----------] 3 tests from NormalizedGraphCut
  [ RUN      ] NormalizedGraphCut.SimpleGraph
  unknown file: Failure
  C++ exception with description "ncv must satisfy nev < ncv <= n, n is the size of matrix" thrown in the test body.
  [  FAILED  ] NormalizedGraphCut.SimpleGraph (0 ms)
  [ RUN      ] NormalizedGraphCut.SimpleGraph1
  unknown file: Failure
  C++ exception with description "ncv must satisfy nev < ncv <= n, n is the size of matrix" thrown in the test body.
  [  FAILED  ] NormalizedGraphCut.SimpleGraph1 (1 ms)
  [ RUN      ] NormalizedGraphCut.FullyConnected
  [       OK ] NormalizedGraphCut.FullyConnected (24 ms)
  [----------] 3 tests from NormalizedGraphCut (25 ms total)

  [----------] Global test environment tear-down
  [==========] 3 tests from 1 test case ran. (25 ms total)
  [  PASSED  ] 1 test.
  [  FAILED  ] 2 tests, listed below:
  [  FAILED  ] NormalizedGraphCut.SimpleGraph
  [  FAILED  ] NormalizedGraphCut.SimpleGraph1

   2 FAILED TESTS

"""

From a previous post, it was caused by a moved file, which was not reflected in the theia.h file. But I used the current master branch, which seems that the corresponding patch has been merged. Are there any other potential causes? Also from #81 , you mentioned that "I would not worry about the normalized graph cut error for now -- it is not used within the SfM pipelines at all". So in SfM pipeline, is it still not used at all?

------------------------------------------------------------------------------------------

25 - optimize_relative_position_with_known_rotation_test (Failed)

"""

[==========] Running 4 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 4 tests from OptimizeRelativePositionWithKnownRotationTest
[ RUN      ] OptimizeRelativePositionWithKnownRotationTest.NoNoise
/home/kevin/devel_lib/SfM/TheiaSfM/src/theia/sfm/bundle_adjustment/optimize_relative_position_with_known_rotation_test.cc:120: Failure
Expected: (translation_error) < (kTolerance), actual: 1.20742e-06 vs 1e-06
GT Position = -0.39246780705331663  -0.1863477902851354 -0.90069058032301408
Estimated position = -0.39246780705331658 -0.18634779028513543 -0.90069058032301386
[  FAILED  ] OptimizeRelativePositionWithKnownRotationTest.NoNoise (0 ms)
[ RUN      ] OptimizeRelativePositionWithKnownRotationTest.PixelNoise
[       OK ] OptimizeRelativePositionWithKnownRotationTest.PixelNoise (1 ms)
[ RUN      ] OptimizeRelativePositionWithKnownRotationTest.TranslationNoise
[       OK ] OptimizeRelativePositionWithKnownRotationTest.TranslationNoise (0 ms)
[ RUN      ] OptimizeRelativePositionWithKnownRotationTest.PixelAndTranslationNoise
[       OK ] OptimizeRelativePositionWithKnownRotationTest.PixelAndTranslationNoise (0 ms)
[----------] 4 tests from OptimizeRelativePositionWithKnownRotationTest (1 ms total)

[----------] Global test environment tear-down
[==========] 4 tests from 1 test case ran. (1 ms total)
[  PASSED  ] 3 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] OptimizeRelativePositionWithKnownRotationTest.NoNoise

 1 FAILED TEST

"""

For this test failure, it seems that the estimated result just differs a little from the expected values. Will it make a big difference when I use it for later reconstruction?

Thank you so much for your time and great help!
