### ISSUE TITLE
Pixel To Camera Reprojection is not normalized

### ISSUE THREAD

**Issue by dbs4261** [sweeneychris/TheiaSfM#186]
After using the camera class to reconstruct a dense point cloud using calculated normals I realized that the vectors generated by PinholeCameraModel::PixelToCameraCoordinates (and every method that calls that function) do not have a magnitude of 1. This is especially confusing in the camera class with the method named PixelToUnitDepthRay as the resulting vector is not a unit vector! This could either be a bug or just a poor naming convention.

**Comment by sweeneychris** [comment]
As explained with the method
<https://github.com/sweeneychris/TheiaSfM/blob/master/src/theia/sfm/camera/camera.h#L140>,
this method creates a ray with projective depth of 1 so PixelTo*UnitDepth*Ray
makes perfect sense.
