### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by yonelay11** [sweeneychris/TheiaSfM#189]
Hello 
![te](https://user-images.githubusercontent.com/34397817/34030721-8c7377d0-e19c-11e7-8491-1519209bcd46.png)

I'm a new user to TheiaSfM. When I try to build within the CMake, I occur this error. Actually, I don't know how to build this. They show this error...
The C compiler identification is MSVC 19.0.24210.0
The CXX compiler identification is MSVC 19.0.24210.0
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
No preference for use of exported Eigen CMake configuration set, and no hints for include directory provided. Defaulting to preferring an installed/exported Eigen CMake configuration if available.
Failed to find installed Eigen CMake configuration, searching for Eigen build directories exported with CMake.
Found exported Eigen build directory: D:/CMake/Eigen3.3.3/build
CMake Error at cmake/FindEigen.cmake:89 (message):
  Failed to find Eigen - Could not find file:
  D://include/eigen3/Eigen/src/Core/util/Macros.h containing version
  information in Eigen install located at: D://include/eigen3.
Call Stack (most recent call first):
  cmake/FindEigen.cmake:219 (eigen_report_not_found)
  CMakeLists.txt:108 (find_package)

Configuring incomplete, errors occurred!
See also "D:/CMake/TheiaSfM/build/CMakeFiles/CMakeOutput.log".
**Let's me know where am I wrong and how to fix?**
sorry for my english in advance.

**Comment by sweeneychris** [comment]
The errors are given right in the output you've provided:

Failed to find Eigen - Could not find file:
D://include/eigen3/Eigen/src/Core/util/Macros.h containing version

Try to fix this by installing Eigen. I'm less familiar with how to do this for Windows unfortunately.

**Comment by charlescva** [comment]
https://stackoverflow.com/questions/21314893/what-is-the-default-search-path-for-find-package-in-windows-using-cmake

Review above.

**Comment by yonelay11** [comment]
Thank You for your reply @sweeneychris @charlescva. I wll try for your advice.

**Comment by yonelay11** [comment]
hello, recently I solve the D://include/eigen3/Eigen/src/Core/util/Macros.h containing version issue.
Now i occur this error.
**No preference for use of exported Eigen CMake configuration set, and no hints for include directory provided. Defaulting to preferring an installed/exported Eigen CMake configuration if available.
Found installed version of Eigen: D:/dev/eigen-3.3.3f/build
-- Found Eigen version 3.3.3: D://include/eigen3
No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
Failed to find installed gflags CMake configuration, searching for gflags build directories exported with CMake.
Failed to find an installed/exported CMake configuration for gflags, will perform search for installed gflags components.
Looking for C++ include shlwapi.h
Looking for C++ include shlwapi.h - found
Performing Test GFLAGS_IN_GOOGLE_NAMESPACE
CMake Error at D:/CMake/TheiaSfM/build/CMakeFiles/CMakeTmp/CMakeLists.txt:14 (target_link_libraries):
  Syntax error in cmake code at

    D:/CMake/TheiaSfM/build/CMakeFiles/CMakeTmp/CMakeLists.txt:14

  when parsing string

    D:\dev\gflags\dir_build\include\gflags

  Invalid character escape '\d'.


CMake Error at C:/Program Files/CMake/share/cmake-3.9/Modules/CheckCXXSourceCompiles.cmake:64 (try_compile):
  Failed to configure test project build system.
Call Stack (most recent call first):
  cmake/FindGflags.cmake:165 (check_cxx_source_compiles)
  cmake/FindGflags.cmake:512 (gflags_check_gflags_namespace_using_try_compile)
  CMakeLists.txt:132 (find_package)


Configuring incomplete, errors occurred!
See also "D:/CMake/TheiaSfM/build/CMakeFiles/CMakeOutput.log".
See also "D:/CMake/TheiaSfM/build/CMakeFiles/CMakeError.log".**

and in CMakeError.log, they said ** D:\CMake\TheiaSfM\build\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [D:\CMake\TheiaSfM\build\CMakeFiles\CMakeTmp\cmTC_915b4.vcxproj]

**. I'm waiting for your reply.

**Comment by holynski** [comment]
> when parsing string
> D:\dev\gflags\dir_build\include\gflags
> Invalid character escape '\d'.

This means that CMake is taking the "\d" from "D:\dev" to mean a type of escape sequence. This is because the Windows CMake GUI doesn't play well with backslashes '\'. Make sure all your paths have regular slashes '/' in their filepaths.
