### ISSUE TITLE
Using Theia with two images only

### ISSUE THREAD

**Issue by oleg-alexandrov** [sweeneychris/TheiaSfM#19]
I tried to use Theia with two images only, and it failed. It looks to me that there should be no fundamental issue why it should be so (unlike say OpenMVG whose basic unit is the triplet). I had to modify just three lines of code for Theia to work with two images, which amounted to just relaxing some checks (https://github.com/oleg-alexandrov/TheiaSfM/commit/d7c850824c21272b39a78ccb73b0765fe53d8e1e). So I am just wondering if the current situation is intentional, or just a minor oversight.

**Comment by sweeneychris** [comment]
Can you verify it creates a valid reconstruction with just 2 images? I seem to remember changing it to require 3 images a while ago because some algorithm broke without that check...

**Comment by oleg-alexandrov** [comment]
I verified that the obtained rotation matrix (from first camera to the second) looked very, very similar to what I was getting with two other approaches. The translation vector was somewhat different (even when taking into account that true scale is never known) but not unreasonably so. This could be easily verified on your side as well, look at two vs three image reconstruction.

**Comment by sweeneychris** [comment]
Great! I don't see any reason to keep requiring 3 views. Could you submit a patch?

**Comment by oleg-alexandrov** [comment]
The whole Gerritt thingy makes me nervous. :) I submitted a pull request on github, can you work with that?

**Comment by sweeneychris** [comment]
Gerrit is able to grab GitHub pull requests :)

The patch is submitted. Thanks very much! https://github.com/sweeneychris/TheiaSfM/commit/1a726263bf1a8ffbdd9dfd63ae427aec3f557369
