### ISSUE TITLE
Compilation error - exhaustive_sampler.cc

### ISSUE THREAD

**Issue by jackhenderson101** [sweeneychris/TheiaSfM#190]
When compiling on windows, I get an error when trying to compile [exhaustive_sampler.cc](https://github.com/sweeneychris/TheiaSfM/blob/master/src/theia/solvers/exhaustive_sampler.cc)
 
The `bool ExhaustiveSampler::Sample(std::vector<int>* subset)` function doesn't return a value, when the return type is bool.
Is it safe just to include a `return true` at the end of the function?

**Comment by kupferb** [comment]
Am having the same problem.
Any verified comments?

**Comment by sweeneychris** [comment]
Fixed! https://github.com/sweeneychris/TheiaSfM/commit/d749a2c25831b7a9c82a9461583516281344ea63
