### ISSUE TITLE
Can't find CeresConfig.cmake and ceres-config.cmake

### ISSUE THREAD

**Issue by yonelay11** [sweeneychris/TheiaSfM#191]
-- Check for Ceres
CMake Error at CMakeLists.txt:152 (find_package):
  By not providing "FindCeres.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Ceres", but
  CMake did not find one.

  Could not find a package configuration file provided by "Ceres" with any of
  the following names:

    CeresConfig.cmake
    ceres-config.cmake

  Add the installation prefix of "Ceres" to CMAKE_PREFIX_PATH or set
  "Ceres_DIR" to a directory containing one of the above files.  If "Ceres"
  provides a separate development package or SDK, be sure it has been
  installed.

**Comment by tv12345** [comment]
How did you solve this issue ?
