### ISSUE TITLE
Cmake Error when using theia as a third party library

### ISSUE THREAD

**Issue by AIBluefisher** [sweeneychris/TheiaSfM#192]
Hi, @Meekohi 

When I use theia as a third party library, I got an error in cmake. Error messages are showed below:

------------------------------------------------------------------------------------------------------------------------------------
CMake Error at /usr/local/share/Theia/TheiaTargets.cmake:34 (message):
  Some (but not all) targets in this export set were already defined.

  Targets Defined: flann_cpp_s

  Targets not yet defined:
  akaze;flann_cpp;statx;stlplus3;vlfeat;visual_sfm;theia

Call Stack (most recent call first):
  /usr/local/share/Theia/TheiaConfig.cmake:205 (include)
  software/ClusterAlign/CMakeLists.txt:3 (find_package)

-------------------------------------------------------------------------------------------------------------------------------------

the 3rd line of software/ClusterAlign/CMakeLists.txt is _**find_package(Theia REQUIRED)**_

I have no idea of what happened! I build theia-sfm successfully in Ubuntu 16.04 LTS. May you help me?
Thank you very much!

**Comment by Meekohi** [comment]
Oof, I'm not a `cmake` expert by any means unfortunately! Best of luck.

**Comment by sweeneychris** [comment]
Did you run an install command for Theia? Something like

sudo make install

If Theia is installed but your ClusterAlign CMake cannot find Theia, then
usually it's just a matter of pointing ClusterAlign to the directory that
Theia is installed in.

Chris

**Comment by AIBluefisher** [comment]
I find that a flann_cpp_s has existed in my project, so it conflicts with this previous one. But I still have no idea of how to solve this problem.

**Comment by AIBluefisher** [comment]
Problem has been solved! 
I comment the line 53:
_**_add_library(flann_cpp_s STATIC IMPORTED)_**_

and modified the line 19
**foreach(_expectedTarget akaze flann_cpp flann_cpp_s statx stlplus3 vlfeat visual_sfm theia)**
to 
**foreach(_expectedTarget akaze flann_cpp statx stlplus3 vlfeat visual_sfm theia)**

 in /usr/local/share/Theia/TheiaTargets.cmake.
Now every thing goes well in my project. But I am not sure if there will be other problems.
