### ISSUE TITLE
Confused about similarity transformation

### ISSUE THREAD

**Issue by AIBluefisher** [sweeneychris/TheiaSfM#195]
Hi, @sweeneychris 
I have 3D-3D correspondences (P_left, P_right) that P_left and P_right are actually same points but located in different coordinate system. Then I used gdls algorithm to to compute rotation, translation and scale, after that, I use the equation P_right^' = scale * rotation * P_left + translation to align the left scene to the right and I get the data below:
![selection_002](https://user-images.githubusercontent.com/18096136/35423664-ea5352d6-0289-11e8-8c34-e0b26ee1bb9d.png)
Is the results accurate or correct? It seems P_right and P_right^' are not located in same coordinate or near the same location, so I doubt if the results are correct and is there any reason for what's wrong with it.

**Comment by sweeneychris** [comment]
gdls is for 2D-3D correspondences. You'll want to use the 3d-3d alignment
algorithm:
https://github.com/sweeneychris/TheiaSfM/blob/master/src/theia/sfm/transformation/align_point_clouds.h

Chris

**Comment by AIBluefisher** [comment]
You're right, but I compute the similarity transformation through 2D-3D correspondences, I give 3D-3D correspondences here just want to see if the transformation accurate enough.

**Comment by sweeneychris** [comment]
I'm not sure I understand what you are asking?

Note that gdls has a special form of similarity transformation that does
not match your description above.

Chris
