### ISSUE TITLE
Triangulation: design matrix initialization

### ISSUE THREAD

**Issue by kupferb** [sweeneychris/TheiaSfM#196]
In the function  TriangulateNViewSVD
 the design matrix initialization is made in the for loop 
 
 ```
  for (int i = 0; i < points.size(); i++) { 
     design_matrix.block<3, 4>(3 * i, 0) = -poses[i].matrix(); 
     design_matrix.block<3, 1>(3 * i, 4 + i) = points[i].homogeneous(); 
   } 
```
so there are many uninitialized entries (e.g., design_matrix(3,4),design_matrix(4,4),...) 
When running in Windows these entries are garbage values, which I think causes the SVD to fail,
are the matrix should be initialized to zeros before the for loop in order to prevent this?

**Comment by sweeneychris** [comment]
You're exactly correct -- there should be line to set the design matrix to zero first. Could you submit a change to fix this? http://theia-sfm.org/contributions.html

**Comment by kupferb** [comment]
Well, I have tried but got "You are not alllowed to perform this operation","To push into this reference you need Push rights"

**Comment by sweeneychris** [comment]
Did you pull the repository from github? You'll want to pull it from Gerrit as described on the webpage.
