### ISSUE TITLE
OpenImageIO 1.8 not supported (at least on Mac OS X)

### ISSUE THREAD

**Issue by wxs** [sweeneychris/TheiaSfM#198]
If I compile Theia on Mac OS X with Homebrew installed OpenImageIO (1.8.8) I get the following error

TheiaSfM/src/theia/image/image.h:67:29: error: use of undeclared identifier 'OpenImageIO'
  explicit FloatImage(const OpenImageIO::ImageBuf& image);

This appears to be an API change in OpenImageIO. I can solve the issue by installing an older version of OpenImageIO from source. (1.7.17), but it's probably a relatively simple change to Theia to get up to date.

**Comment by sweeneychris** [comment]
Does this PR fix your issue? https://github.com/sweeneychris/TheiaSfM/pull/200

**Comment by imkaywu** [comment]
@wxs, @sweeneychris, I got the same error trying to build theia from source code. could you please explain a bit more how is this issue solved? any help is appreciated.
