### ISSUE TITLE
Python API

### ISSUE THREAD

**Issue by grozail** [sweeneychris/TheiaSfM#199]
Will it be and if yes, when?
Would be perfect to have it also in anaconda :)
Thanks in advance for your attention.

**Comment by holynski** [comment]
I'm not aware of any Python wrappers in development, but you could pretty easily develop your own.

Take a look at Boost.Python (http://www.boost.org/doc/libs/1_66_0/libs/python/doc/).

You can use it to write minimal wrappers in C++ that can be exposed to Python.

**Comment by sweeneychris** [comment]
I have no plans to add a python interface but would welcome any pull
requests that implement it.

Chris
