### ISSUE TITLE
Failed tests

### ISSUE THREAD

**Issue by Meekohi** [sweeneychris/TheiaSfM#2]
A couple tests fail on 95adca5e0178c7a6d47a4a150674aefad06f9341
```
The following tests FAILED:
	 33 - filter_view_pairs_from_relative_translation_test (Failed)
	 40 - four_point_focal_length_test (Failed)
Errors while running CTest
```

**Comment by sweeneychris** [comment]
Hi Mike,

Thanks for reporting the issue. What OS and compiler are you using? It
seems that the filtering translations test only fails for clang in Mac... I
still need to investigate why that is.

I'm actually in holiday right now and don't have my computer. Would you
mind if I merge these when I'm back in a week? Don't let that stop you from
reporting any bugs or errors though!

**Comment by Meekohi** [comment]
OSX 10.10.2 and `Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)`

No rush on merging anything, I was just running through a fresh install and wanted to help future people get over a few of the speedbumps.

**Comment by sweeneychris** [comment]
Can you see if this commit fixes it? https://github.com/sweeneychris/TheiaSfM/commit/906a71ec6613500ae8ecb89e0e04de9e6f7b9ee3

That patch has all tests passing for me on Apple and Linux both GCC and Clang

**Comment by Meekohi** [comment]
Hey sorry for the long delay. Those two test now pass, however a new one fails:

```
The following tests FAILED:
	 41 - four_point_focal_length_test (Failed)
Errors while running CTest
```

**Comment by Meekohi** [comment]
and for what it is worth, master (118734442b3674805f3cbc2939c7bb23262044b9) passes all of those but fails.

```
The following tests FAILED:
	 38 - estimate_rotations_robust_test (Failed)
Errors while running CTest
```

**Comment by sweeneychris** [comment]
I believe all tests are passing at the current HEAD. I have tried with gcc 4.8 and apple clang on 2 different Macs and a ubuntu machine. Can you let me know if you are still getting errors?

**Comment by Meekohi** [comment]
I can confirm all tests pass.
```
$ uname -a
Darwin Michaels-iMac.local 14.1.0 Darwin Kernel Version 14.1.0: Thu Feb 26 19:26:47 PST 2015; root:xnu-2782.10.73~1/RELEASE_X86_64 x86_64
$ clang -v
Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.1.0
Thread model: posix
```
