### ISSUE TITLE
Most convenient way to display a FloatImage

### ISSUE THREAD

**Issue by jianweike** [sweeneychris/TheiaSfM#203]
Hi, all, 

I am new to TheiaSfM. I guess I can display an FloatImage using OpenGL and GLUT, but are there any existing methods in Theia that can be used to display an image read as FloatImage?

Thank you all in advanced. 
Jianwei

**Comment by sweeneychris** [comment]
Sorry, there is no native image viewer to theia. But you can always write out the FloatImage and view the image in your file browser.

**Comment by jianweike** [comment]
I see. Thank you for your response.
