### ISSUE TITLE
Example code of sfm using Theia

### ISSUE THREAD

**Issue by jianweike** [sweeneychris/TheiaSfM#204]
Hi, I am just new to Theia. I found Theia is a very good resource for SfM task. Although the documentation of the library is really detailed, I didn't find any example codes for SfM. It would be very nice if you can provide some example codes for performing simple SfM over a small image collection.

Thank you.

**Comment by sweeneychris** [comment]
The applications directory contains numerous examples. The
build_reconstruction app should work out of the box for an image collection
as well. Further, almost every file has unit tests which can double as a
sort of example.

**Comment by jianweike** [comment]
Thanks for your quick response. I will take a look at it.
