### ISSUE TITLE
Triangulation Question

### ISSUE THREAD

**Issue by astaranowicz** [sweeneychris/TheiaSfM#207]
The input to TriangulateNView is the poses and the corresponding pixel points. 
The output is the 3D point. 
Is the input poses  K[R|t] or just [R|t]?

I thought the intrinsic matrix (K) has to be taken into account as the 3D-2D projection formula is:
 u=K[R|t] X  where u is the pixel point and X is the 3D point.  
But from the example: TheiaSfM/src/theia/sfm/triangulation/triangulation_test.cc it seems only the rotation and translation make up the pose.

**Comment by sweeneychris** [comment]
I believe either will work (the second just assumes K == Identity) as long as you use the same formulation for the image points

**Comment by astaranowicz** [comment]
This means that the K[R|t] would be used because different cameras are being used, while [R|t] is the same camera moving in the 3D space.

**Comment by astaranowicz** [comment]
To continue this question: what is the logic behind and is there somewhere I can read on how you obtained the function: FindOptimalImagePoints in the triangulation.

The comments in the function is as follows:
// Given either a fundamental or essential matrix and two corresponding images
// points such that ematrix * point2 produces a line in the first image,
// this method finds corrected image points such that
// corrected_point1^t * ematrix * corrected_point2 = 0.

However, the function doesn't seem to hold for a Fundamental matrix composed of 2 different cameras with 2 different calibration matrices.
