### ISSUE TITLE
FindGFlags.cmake missing INCLUDE(CheckIncludeFileCXX)

### ISSUE THREAD

**Issue by bvanevery** [sweeneychris/TheiaSfM#21]
CMake 3.2.3 fails with error, unknown command CHECK_INCLUDE_FILE_CXX.  An INCLUDE statement is necessary to use commands in CMake modules, it's not automatic.  FIx is trivial, put  INCLUDE(CheckIncludeFileCXX) in FindGFlags.cmake.

**Comment by sweeneychris** [comment]
This patch should fix it: https://review.gerrithub.io/#/c/238275/
