### ISSUE TITLE
Angle comparison error in `PairwiseRotationError`

### ISSUE THREAD

**Issue by Anstow** [sweeneychris/TheiaSfM#212]
In the class `PairwiseRotationError` the error between two axis angle rotation vectors is computed by finding the linear distance. This is incorrect and runs into trouble when the angles are near +pi and -pi. I wrote my own test to reproduce this error. An attempt at a test for this has been made but this test passes.

Suggested fix: Compute the rotation between the axis angle vectors as an axis angle vector and "compare" this to the zero vector.

**Comment by sweeneychris** [comment]
Yes, this is a known limitation of the angle-axis (and all non-quaternion) representation of rotations. Feel free to submit a PR for your suggested fix and I'll be happy to review it

**Comment by Anstow** [comment]
Fixed in:
https://github.com/sweeneychris/TheiaSfM/pull/214
