### ISSUE TITLE
statx library conflicts with new statx function in linux

### ISSUE THREAD

**Issue by Anstow** [sweeneychris/TheiaSfM#213]
When building TheiaSfM on linux (arch linux) I get a conflict between the namespace statx (from the library) and a statx function included (indirectly) via gtest. I think that the below discuses the introduction of the function into glibc which may be of some use.

https://www.phoronix.com/scan.php?page=news_item&px=Glibc-Statx-Support

**Comment by vfragoso** [comment]
Although I was not able to reproduce this, I have a PR fixing this. It just simply changes the namespace to libstatx. I hope this fixes this issue. I'll send this PR soon.
