### ISSUE TITLE
Rockdb breaking feature detection: "could not insert feature into database"

### ISSUE THREAD

**Issue by fraessig** [sweeneychris/TheiaSfM#219]
Hi, i recently put together a simple script that is supposed to automate the Reconstruction Process from a video to a meshed 3D Object. It featured the sfm pipeline from theia.

It worked great until a few days ago when the database storing was added. Even Datasets that worked previously now fail during the feature extraction with the following error. 
![grafik](https://user-images.githubusercontent.com/44864582/48192090-22278a80-e347-11e8-9942-756b45ab0bb5.png)
This happens no matter what images i use but the point at which it fails is different from every dataset, However eventually it will fail no matter what.

Is there something that changed the workflow with this update like a new parameter in the flagfile that needs to be adapted or something along these lines that i am missing?

I am using the WSL on Win10 with Ubuntu btw.

**Comment by sweeneychris** [comment]
No flags parameters should need to be changed. The --matching_working_directory option will now use that directory for the DB.

Are you using multiple threads? Can you verify that the DB successfully adds any features?

**Comment by fraessig** [comment]
Yes, i was using 4 threads but reducing that to 1 or 2 does not bring any changes.
And im not sure if actually adds the features to a database, my matching working directory after the error looks like this. 
![grafik](https://user-images.githubusercontent.com/44864582/48260963-cd0a7800-e41d-11e8-864f-61cb9a25aecf.png)

It seems like it did write something into the 000003.log file (this on is getting bigger during the process) but i dont know if thats already the database or not since i dont know how its supposed to look like in a successful try. 
I also tried this on a different System with newer hardware but i still got the same error.

**Comment by sweeneychris** [comment]
If you look okay and of the log files is there any useful output? I think those are texts. The DB itself will be written to sst files when it is flushed to disk (which might not be right away).

If you run the rocksdb unit test does it pass? If it does, the next thing I would try is to rm the matching working directory before running it again.

**Comment by fraessig** [comment]
So looking through the logfile didnt showed anything useful at first however i saw that the version of rocksdb was compiled somewhere around 2017. 
I used apt-get install for most of the dependencies since this is just more convient and it worked for all of them so i just did that for rocksdb as well.  However the Version of rocksdb you get from that seems to be quite old. 
But trying to compile rocksdb from source gave me a few errors as well and i dont have the time right now to resolve all of them.
So for now i will use the last 0.8 version instead but compiling rocksdb from source should fix the issue, i think.
You should propably note that in the documentation or the building guide somewhere.
