### ISSUE TITLE
FindEigen.cmake does not detect eigen3 directory on Windows

### ISSUE THREAD

**Issue by bvanevery** [sweeneychris/TheiaSfM#22]
It simply doesn't search obvious installed Windows paths for it.  For instance, C:/Program Files/... on a 64-bit system.  There's a note in FindEigen.cmake: "# TODO: Add standard Windows search locations for Eigen."  I'm making note of it in the bug tracker, so that it is known that others are actually encountering this behavior when they try to build Theia on Windows.  It's actually the very 1st impression of the Theia build, that this doesn't work.

Fortunately it is semi-easy to work around by specifying the directory.  "Semi" because the directory that must be specified is actually "C:/Program Files/Eigen/include/eigen3", which is counterintuitive for an INCLUDE directory.  Usually an INCLUDE would just be "C:/Program Files/Eigen/include", although unfortunately this library is using subdirectories for versioning.

**Comment by sweeneychris** [comment]
Before I start making patches... are you 100% sure you have a standard-ish build system? Ceres uses the same FindEigen.cmake and is *very* well tested for windows systems so I am surprised that this bug is happening

**Comment by sweeneychris** [comment]
Also, you should be able to set EIGEN_INCLUDE_DIR_HINT to the installed dir and have that fix the problems

**Comment by bvanevery** [comment]
My Eigen installs at "C:/Program Files/Eigen", which is standard for a 64-bit system, as most Windows systems are nowadays.  If it were 32-bit it would go under "C:/Program Files (x86)/Eigen".

Respectfully.. the TODO comment exists in TheiaSfM/cmake/FindEigen.cmake .  Although it doesn't have to be the true source of the error, it is reasonable to take it at face value and start there.  ceries-solver's FindEigen.cmake has exactly the same comment and fails exactly the same way. 

You may be borrowing from a code base that basically doesn't work on Windows, given that ceres-solver has the gflags namespace detection problem as well.  It would not be the first time, over the years, that I've run into *.cmake modules that are "quite rusty", even in the official CMake distro.  Especially, actually; open source library projects often don't have the discipline to stay on top of official *.cmake modules as they change their own libs.  This is why people tend to have their own /cmake subdirectories and their own versions of Find*.cmake routines, to fend off the bugs.  I'm sure you've found that out already.

EIGEN_INCLUDE_DIR_HINT is just another way to work around the lack of detection, same as manually specifying the directory.  The point of the bug report is to make note of the lack of detection, in what should be a pretty trivial detection case.

People who use ceres-solver on Windows, probably just specify directories manually and never file bug reports about it.  Because, they probably don't care about builds, or the impressions builds leave on new users.

**Comment by bvanevery** [comment]
I filed an upstream bug with ceres-solver.

**Comment by sweeneychris** [comment]
Ha not sure about the italics but it gives your comments a certain amount of sass ;)

Thanks for uploading the issue to Ceres. I am not at all a CMake expert and the issue is compounded by the fact that I don't have access to a Windows machine. Hopefully they'll have the correct solution that I can patch in!

**Comment by sweeneychris** [comment]
Actually... can you see if the HEAD of the repo works for you now? I added a check to ${CMAKE_INSTALL_PREFIX} which may catch the windows case...

**Comment by bvanevery** [comment]
Doesn't work.  I noticed you didn't include the /include/ part of the path, which would be needed.  But I tried a few permutations like that just now, and it didn't start working.  I'll actually have to understand what I'm doing, <sigh>.  I don't even have a Fortran compiler working for the Lapack that ceres-solver wants....

**Comment by sweeneychris** [comment]
I see that Ceres has just uploaded new versions of FindEigen, FindGlog, and FindGflags. Can you confirm that those all work for your machine? If so, I will pull them over to Theia's Cmake and hopefully this will solve the issues!

**Comment by bvanevery** [comment]
Yep, 'cuz I'm the guy that prodded them to do it and tested their stuff.
:-)

**Comment by sweeneychris** [comment]
Awesome! Ok here is my patch. Could I bother you again to try this and confirm it works for you? You'll need to remove CMakeCache.txt and probably do a make clean

https://review.gerrithub.io/#/c/240098/

**Comment by bvanevery** [comment]
Eigen, gflags, and glog are all detected now on Windows!

**Comment by sweeneychris** [comment]
Thanks for testing, Brandon!
