### ISSUE TITLE
FindGflags.cmake does not detect gflags directory or namespace.

### ISSUE THREAD

**Issue by bvanevery** [sweeneychris/TheiaSfM#23]
I'm using Windows 7, Visual Studio 2013 Community Edition, CMake 3.2.3.  My gflags installation is in the standard place for a 64-bit Windows system, "C:/Program Files/gflags". FindGflags.cmake should be able to identify the directory without problem, as it is trivially easy to find, but it does not. The file contains a comment, "# TODO: Add standard Windows search locations for gflags." Although that may not be the source of the error, it seems reasonable to take it at face value.

Assuming one manually specifies the location of the gflags include directory and library file, gflags namespace detection is attempted. However on Windows it fails. I suspect that gflags has changed and the namespace testing is now inadequate.

The CMake modules appear to be derived from the Ceres Solver project, and their modules exhibit the same behavior.  I have filed upstream bugs with them.

The "stock" gflags_declare.h defines the namespace is "google", so I have manually specified that in the CMake GUI to try to continue the build.  I don't know if that's going to prove to be behaviorally correct though.  Gflags has some weird implementation notes about using a hybrid of google and gflags namespace behavior.  I really don't care to understand this presently; it looks like a "troubled" library.

Ceres Solver doesn't actually require gflags in order to be built.  Is it possible for TheiaSfM to implement the same behavior, to not have this as a showstopper?

**Comment by sweeneychris** [comment]
Fixed with  https://review.gerrithub.io/#/c/240098/
