### ISSUE TITLE
The equation in "triangulation make easy" is different with the code

### ISSUE THREAD

**Issue by volcanoh** [sweeneychris/TheiaSfM#247]
https://github.com/sweeneychris/TheiaSfM/blob/d2112f15aa69a53dda68fe6c4bd4b0f1e2fe915b/src/theia/sfm/triangulation/triangulation.cc#L92

In the paper, the equation is `epipolar_line1 -= e_submatrix * lambda * epipolar_line2; `
Which is wrong?

**Comment by sweeneychris** [comment]
I doubled checked the math and I believe my impl is correct. Feel free to try a correction and LMK if the results improve, but i believe the unit test should ensure this is the optimal method
