### ISSUE TITLE
DLS Pnp solver Macaulay Matrix creation

### ISSUE THREAD

**Issue by inspirit** [sweeneychris/TheiaSfM#25]
Hello,

i was trying to use DLS pose estimator and got BUS error in SSE store instructions at this line:
https://github.com/sweeneychris/TheiaSfM/blob/master/src/theia/sfm/pose/dls_impl.cc#L342
Seems like the matrix is too big and Eigen fail to set it to Zero values using SSE...

by replacing matrix type with ```MatrixXd``` i was able to successfully use the method.

also here: ```double indices[1968]``` seems to be a mistake in array type. obviously it should be ```int```

**Comment by sweeneychris** [comment]
Thanks for finding these issues. I have had many other users use this function without issue. Could you try this patch and let me know if it works? I am not 100% sure that it needs to be a dynamic matrix.

https://review.gerrithub.io/#/c/240087/

**Comment by inspirit** [comment]
changing to ```setZero()``` doesn't fix the issue still crashing

**Comment by sweeneychris** [comment]
Darn!

Would you mind supplying me the following information? Just want to make sure I have the proper fix for it:  Eigen version, compiler version, OS,

**Comment by inspirit** [comment]
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.4.0
Eigen 3.2.5

**Comment by sweeneychris** [comment]
Very odd... exact same as me! Let me play around a bit and see if I can track down the real root of the error. Like I said, I'm not 100% positive it is a dynamic vs fixed-size matrix issue so I want to be sure before changing all the code for the dls solvers

**Comment by sweeneychris** [comment]
Ok my research hasn't provided any useful information, so I've changed all the DLS code to use dynamic matrices. Can you confirm this updated patch works for you?

https://review.gerrithub.io/#/c/240087/2/

**Comment by inspirit** [comment]
yes this way it works without any problems. i wonder why u changed other matrices also? such as
```Matrix<double, 27, 27>``` to dynamic? in my tests only changing 120x120 Matrix to dynamic already worked.

**Comment by sweeneychris** [comment]
I read on the Eigen website that there isn't really any benefit to having fixed sized matrices beyond a certain point and actually the eigensolver's implementation is better for dynamic sized matrices that are larger.

Thanks for the bug report! Closing this issue, but please let me know if there are other issues that arise or you are having trouble with the library.
