### ISSUE TITLE
Have a problem understanding smth

### ISSUE THREAD

**Issue by inspirit** [sweeneychris/TheiaSfM#28]
Hello,

I'm currently playing with different SLAM frameworks and experimenting with different initialization
steps when we don't know anything about world yet.
It seems to be a bit similar to incremental reconstruction that is implemented in Thiea so i wanted to
try similar approaches in my SLAM experiments. But i have troubles understanding some steps:
1. first initial frame is Identity of course.
2. we match all next frames to first and try to estimate relative pose.
3. after we successfully estimate we triangulate initial map and continue extending it based on all new frames etc.

so i was trying to use Theia to estimate this initial map from 2 frames and relative pose. Theia is using 5pt Relative Pose estimator which returns multiple pose variants and we filter them after. 
this includes computation of Essential matrix, decomposing it and filtering...
First question i got is why here:
https://github.com/sweeneychris/TheiaSfM/blob/master/src/theia/sfm/pose/essential_matrix_utils.cc#L82
we have to invert positions for candidate poses?

in my example i'm estimating Essential matrix from normalized correspondences where feature1 is in first identity frame and feature2 is in next frame. so i should get Essential from first to second frame. I thought that decomposing this Essential will give me ```[R|t]``` from first to second frame, but then when we filter this poses to find best one we modify them, what is the reason for that?

**Comment by sweeneychris** [comment]
What do you mean "invert positions for candidate poses"? 

The essential matrix decomposition gives *relative translations* whereas that function returns *positions*. That is, the positions of camera 2 relative to camera 1 in the coordinate system of camera 1. For 2-view geometry Theia always uses the relative position rather than the relative translation.

**Comment by inspirit** [comment]
thanx for the explanation. by "invert i mean" converting from translation to position, sorry.
i also noticed that you use different matrix during Essential decomposition (compared to other sources i saw doing essential decomposition):
https://github.com/sweeneychris/TheiaSfM/blob/master/src/theia/sfm/pose/essential_matrix_utils.cc#L59

in other examples i saw it defined differently:
```0,-1, 0```
```1,  0, 0```
```0,  0, 0```

**Comment by sweeneychris** [comment]
Yes, glad you follow! The implementation of the decomposition is based off of this paper: "An Efficient Solution to the Five-Point Relative Pose Problem" by David Nister (Section 3.1 and appendix)

Please feel free to add comments (even if code doesn't change) and submit a patch if you feel it will help future folks in understanding the code. 

Can we close this "issue" then?

**Comment by inspirit** [comment]
thanx
