### ISSUE TITLE
Line segments as features for low textured reconstruction

### ISSUE THREAD

**Issue by inspirit** [sweeneychris/TheiaSfM#30]
Any plans on implementing Line Segments in addition to corner/blob based features to improve robustness in low texture environment? I see a lot of attention recently payed to this topic, even though its not new and there were quite a bunch of good papers on the subject in past 3 years.
for example: https://aerial.icg.tugraz.at/papers/hofer_bmvc2014.pdf

**Comment by sweeneychris** [comment]
I would love for LSD to be integrated into Theia. Do you know of a high quality open-source implementation? I do not think I will have the time to implement it from scratch.

**Comment by inspirit** [comment]
well LSD source is open and public. it is C based implementation however i dont see any difficulties in translating it into smth more object oriented c++ style...

**Comment by sweeneychris** [comment]
True... but the other issue is that line-based SfM pipelines requires new solvers for relative and absolute pose unless you use point features extracted from the line segments. If you want a line-based SfM pipeline then that would require an entirely new pipeline to Theia

**Comment by inspirit** [comment]
yeah thats what i was suspecting. its not a trivial task

**Comment by sweeneychris** [comment]
Can we close this issue since it seems the question was answered?

**Comment by inspirit** [comment]
sure, thanx for the info
