### ISSUE TITLE
CMake OPTIMO_BUILD_TESTING unbuildable on Linux

### ISSUE THREAD

**Issue by bvanevery** [sweeneychris/TheiaSfM#31]
I'm using a Linux Mint 17.2 installation.  I've acquired numerous dependencies and everything says it'll build, except the option OPTIMO_BUILD_TESTING.  Turning it on generates an error:

CMake Error at libraries/optimo/CMakeLists.txt:69 (ADD_SUBDIRECTORY):
  add_subdirectory given source "libraries/gtest" which is not an existing
  directory.

Looking at some of the CMakeLists.txt files, I suspect is has to do with conditional inclusion of the gtest directory, evaluation order, and some kind of lack of dependency in variable evaluation / definition.  For instance TheiaSfM/libraries/CMakeLists.txt contains:

IF (${BUILD_TESTING})
  ADD_SUBDIRECTORY(gtest)
ENDIF (${BUILD_TESTING})

**Comment by sweeneychris** [comment]
Line 66 shows that OPTIMO_BUILD_TESTING is set to OFF.  Do you know why your build ever reaches line 69 if this is the case?

**Comment by bvanevery** [comment]
Went and read the CMake docs just to be sure, but I was right about how Option works.
OPTION(OPTIMO_BUILD_TESTING "Enable testing" OFF)
merely sets the *initial* value of the variable to OFF.  It can be changed via the CMake GUI, which I did, to ON.  Thus on the next Configuration run after such options have been set, program flow continues through the IF statement.  Assuming ADD_SUBDIRECTORY works as designed and we haven't found a CMake 2.8 bug, then something is wrong with the ENABLE_TESTING() macro.  Directory globbing has often been a cause of such errors, due to differences of when globbing runs vs. configuring stuff, but I have no idea if that sentiment is applicable here.

I will try installing the latest greatest CMake directly from Kitware's website, to see if that changes anything.  Linux Mint has a rather old copy in the repo.  Bit annoying, that, and I thought about changing to a different distro with more aggressive lib versioning, but Mint is what came through in my last HD crisis.  Happened to have it on a USB stick still.

**Comment by bvanevery** [comment]
Error exists with CMake 3.3.0 as well.

**Comment by sweeneychris** [comment]
I'm a bit tied up with work at the moment, but perhaps you'd like to submit a patch to fix this?

**Comment by bvanevery** [comment]
Not really right now.  Tied up in my own ways.  Haven't learned how to
actually do anything with Theia yet, although I have read some of the
documentation.  My CMake skills aren't what they used to be, so I've
avoided digging around to find the answer.  I figure if I ever get to the
point where I actually need this solved, then I'll do something about it.
Meanwhile, it's worth filing bugs since I did at least expend the effort to
find it.

**Comment by sweeneychris** [comment]
Fixed with this massive commit. I wrapped all my cmake fixings into this one patch: https://review.gerrithub.io/#/c/243009/

**Comment by bvanevery** [comment]
Confirmed fixed; it builds.
