### ISSUE TITLE
Error on opening image

### ISSUE THREAD

**Issue by mojovski** [sweeneychris/TheiaSfM#34]
When  I try to open this image
https://copy.com/8lGcgDwqBQLgX2R3
I receive this error code:
```
[CImg] *** CImgIOException *** [instance(0,0,0,0,(nil),non-shared)] CImg<float>::load(): Failed to recognize format of file '/media/eugen/DATAPART1/SensorDaten/ReineBilder/RAG/sfm/all_left_images/1571720.jpg'.
terminate called after throwing an instance of 'cimg_library::CImgIOException'
  what():  [instance(0,0,0,0,(nil),non-shared)] CImg<float>::load(): Failed to recognize format of file '/media/eugen/DATAPART1/SensorDaten/ReineBilder/RAG/sfm/all_left_images/1571720.jpg'.
Aborted (core dumped)
```
The command I executed was:
```
./match_descriptors --input_imgs=$data/*.jpg --img_output_dir=$data/theia_matches --num_threads=14 --descriptor=SIFT --matcher=brute_force --lowes_ratio=0.8 -logtostderr -v 3
```

**Comment by sweeneychris** [comment]
Are you sure that you have libjpeg (libjpeg-dev on ubuntu) installed?

**Comment by mojovski** [comment]
yepp :)

**Comment by sweeneychris** [comment]
Let me try to cook up a patch that fixes this. This issue of image
libraries and converting file types is frequently occurring so I'd like to
solve it once and for all.

**Comment by sweeneychris** [comment]
Could you try this patch? It should fix the problem such that CMake will complain if you don't have the proper libraries installed, and will ask you to install ImageMagick. Please run:

rm CMakeCache.txt
cmake ..
make

and etc. from the build directory after you add this patch. Please let me know if this works!

**Comment by sweeneychris** [comment]
Hi,

Have you been able to try this patch yet?

**Comment by sweeneychris** [comment]
I believe this issue has been solved with: https://review.gerrithub.io/#/c/246786

Please re-open the issue if it still persist!

**Comment by mojovski** [comment]
Sorry, will try it this week.
