### ISSUE TITLE
Improve number of geometrically verified features

### ISSUE THREAD

**Issue by sweeneychris** [sweeneychris/TheiaSfM#35]
After performing feature matching and 2-view geometry estimation, we run bundle adjustment on the inlier features. However, we currently do not re-evaluate the bundle-adjusted pose to determine if more inliers can be found. We need to do an analysis on this to make sure that the number of inliers reliably increases and that this procedure is stable.

**Comment by pmoulon** [comment]
Why not call that guided matching.
Following an hypothesis model you look for inliers.

**Comment by sweeneychris** [comment]
Guided matching performs a search for feature matches along the epipolar
lines. I am only suggesting that we recompute which matches are inliers
based on the new relative pose after bundle adjustment.

**Comment by sweeneychris** [comment]
Done with https://github.com/sweeneychris/TheiaSfM/commit/1d7e6e9d9ffeda3ebbe7f2da85e02c8648477b7c
