### ISSUE TITLE
Compilation error: non-existing Eigen function Eigen::internal::tridiagonal_qr_step<>

### ISSUE THREAD

**Issue by kmhofmann** [sweeneychris/TheiaSfM#40]
When trying to build TheiaSfm (v0.5 tag; but the same issue appears on the most current commit 20c5433), I am experiencing a compiler error due to incorrect use of an internal Eigen function:

    In file included from /theia/src/theia/sfm/global_pose_estimation/linear_position_estimator.cc:47:
    In file included from /theia/libraries/spectra/include/SymEigsSolver.h:20:
    /theia/libraries/spectra/include/LinAlg/TridiagEigen.h:93:13: error: no matching function for call to 'tridiagonal_qr_step'
                Eigen::internal::tridiagonal_qr_step<Eigen::ColMajor>(maind, subd, start, end, evecs.data(), n);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /theia/libraries/spectra/include/LinAlg/TridiagEigen.h:46:9: note: in instantiation of member function 'Spectra::TridiagEigen<double>::compute' requested here
            compute(mat);
            ^
    /theia/libraries/spectra/include/SymEigsSolver.h:308:30: note: in instantiation of member function 'Spectra::TridiagEigen<double>::TridiagEigen' requested here
            TridiagEigen<Scalar> decomp(fac_H);
                                 ^
    /theia/libraries/spectra/include/SymEigsSolver.h:514:9: note: in instantiation of member function 'Spectra::SymEigsSolver<double, 0, theia::SparseSymShiftSolveLDLT>::retrieve_ritzpair' requested here
            retrieve_ritzpair();
            ^
    /theia/src/theia/sfm/global_pose_estimation/linear_position_estimator.cc:257:8: note: in instantiation of member function 'Spectra::SymEigsSolver<double, 0, theia::SparseSymShiftSolveLDLT>::compute' requested here
      eigs.compute();
           ^
    /usr/local/include/eigen3/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h:740:13: note: candidate template ignored: invalid explicitly-specified argument for template parameter 'RealScalar'
    static void tridiagonal_qr_step(RealScalar* diag, RealScalar* subdiag, Index start, Index end, Scalar* matrixQ, Index n)

A function from Eigen::internal should probably not be used in client code. I did not test which Eigen versions prior to 3.2.6 still perform a correct template instantiation, but the function template in question seems to have been changed a long time ago to take a scalar type as first template argument instead of a storage order (see Eigen commit 3bc00df9c229 from 2011?)

Platform is Mac OS X; all dependencies (Eigen, Ceres, etc.) have been installed via Homebrew to /usr/local.
Since Eigen is a multiplatform header-only library, I do not expect this issue to be platform specific.

Partial CMake output:

    - The C compiler identification is AppleClang 7.0.0.7000176
    - The CXX compiler identification is AppleClang 7.0.0.7000176
    …
    - Found Eigen: /usr/local/include/eigen3 (found suitable version "3.2.6", minimum required is "3.2.0") 
    - Found Eigen version 3.2.6: /usr/local/include/eigen3

**Comment by kmhofmann** [comment]
This very small change seems to fix compilation, but I did not check for correctness:

    diff --git a/libraries/spectra/include/LinAlg/TridiagEigen.h b/libraries/spectra/include/LinAlg/TridiagEigen.h
    index 20270b9..d26185e 100644
    --- a/libraries/spectra/include/LinAlg/TridiagEigen.h
    +++ b/libraries/spectra/include/LinAlg/TridiagEigen.h
    @@ -90,7 +90,7 @@ public:
                 while(start > 0 && subd[start - 1] != 0)
                     start--;
     
    -            Eigen::internal::tridiagonal_qr_step<Eigen::ColMajor>(maind, subd, start, end, evecs.data(), n);
    +            Eigen::internal::tridiagonal_qr_step(maind, subd, start, end, evecs.data(), n);
             }
     
             if(info > 0)

**Comment by sweeneychris** [comment]
Thanks for the detailed bug report and proposed fix! I am using Eigen 3.2.5 with the current repo and have no issues... let me track down the author of Spectra and see what he has in mind to fix this.

**Comment by sweeneychris** [comment]
By the way, this is the function in the Eigen master branch: https://bitbucket.org/eigen/eigen/src/af48a2d79e699f1f79e3a0cc9ca6b65efb5a6d1a/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h?at=default&fileviewer=file-view-default#SelfAdjointEigenSolver.h-797

The StorageOrder is indeed the correct first template argument. I think your compiler is getting confused about one of the RealScalar* parameters being passed into the function. See this issue in StackOverflow: http://stackoverflow.com/questions/8629839/c-candidate-template-ignored-invalid-explicitly-specified-argument-for-templ

**Comment by sweeneychris** [comment]
If you specify all template parameters in the file, does this fix the issue?

diff --git a/libraries/spectra/include/LinAlg/TridiagEigen.h b/libraries/spectra/include/LinAlg/TridiagEigen.h
index 20270b9..82faa84 100644
--- a/libraries/spectra/include/LinAlg/TridiagEigen.h
+++ b/libraries/spectra/include/LinAlg/TridiagEigen.h
@@ -90,7 +90,7 @@ public:
             while(start > 0 && subd[start - 1] != 0)
                 start--;
 
-            Eigen::internal::tridiagonal_qr_step<Eigen::ColMajor>(maind, subd, start, end, evecs.data(), n);
+            Eigen::internal::tridiagonal_qr_step<Eigen::ColMajor, Scalar, Scalar, int>(maind, subd, start, end, evecs.data(), n);
         }

**Comment by kmhofmann** [comment]
It seems that the StorageOrder template argument indeed disappeared in the 3.2 branch, from 3.2.6 onwards: https://bitbucket.org/eigen/eigen/src/c58038c56923e0fd86de3ded18e03df442e66dfb/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h?at=3.2.6&fileviewer=file-view-default
It's quite easy to switch between different tags in the Bitbucket file viewer.

This is the commit that changed it: https://bitbucket.org/eigen/eigen/commits/4458e97cf524cb2e78851175be53640b4b405191

According to the commit message there, it was backported from the default branch. This can't be completely true, since 'hg blame' reveals that the `template <...>` line was last changed in November 2010: https://bitbucket.org/eigen/eigen/annotate/af48a2d79e699f1f79e3a0cc9ca6b65efb5a6d1a/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h?at=default&fileviewer=file-view-default

I don't know what the supposed future implementation will look like. It could very well be that they will differ between 3.2 and 3.3 branch. The underlying problem is that the Spectra library is using an internal function (from the Eigen::internal namespace), for which the underlying implementation as well as the interface may change at any time.

**Comment by sweeneychris** [comment]
Yes, you are correct. I suppose this is always going to be an issue with using the internal functions.

I've copied those functions out and put them into the header file within Theia. Could you try this patch and confirm it fixes the problem?

https://review.gerrithub.io/#/c/252459

**Comment by yixuan** [comment]
Sorry for the trouble here...
I think @kmhofmann  is correct, probably I should not directly use the internal functions in Eigen. If needed I could copy/derive some code from Eigen so that it does not break when API changes.

**Comment by sweeneychris** [comment]
@yixuan I think this patch will do the trick. Let me know if you have a better solution: https://review.gerrithub.io/#/c/252459

**Comment by yixuan** [comment]
That's great!
I'll apply this patch to Spectra later, and add necessary copyright information since we are copying code from Eigen.
You may also want to apply the recent updates from Spectra which fixed some numerical stability issues.

**Comment by sweeneychris** [comment]
@yixuan Ok sounds great. Can you post here once you've incorporated that into Spectra? Then I'll just copy all the new spectra code into Theia :)

**Comment by yixuan** [comment]
No problem!

**Comment by kmhofmann** [comment]
@sweeneychris @yixuan I can confirm that the latest repo head fixes the compilation issue. Thanks for the quick fix!
