### ISSUE TITLE
Add CameraIntrinsicsGroup to Views

### ISSUE THREAD

**Issue by sweeneychris** [sweeneychris/TheiaSfM#41]
For datasets where we know that multiple images may come from one camera, it is advisable to optimize the camera intrinsics explicitly as a single set of camera intrinsics parameters (rather than each image with its own intrinsics). To this effect, we can add a `uint32_t CameraIntrinsicsGroupId` to the View class and possibly an `unordered_map<CameraIntrinsicsGroupId, unordered_set<ViewId> >` to the Reconstruction class.

During BA, we can only optimize one set of camera intrinsics per group. This involves several steps:
1. For each group, initialize the camera intrinsics so that they are the same (median values?)
2. Choose a camera within the group that will be the representative camera intrinsics for the group (first available)
3. Set all optimized views to be the updated camera intrinsics

Questions
1. How does this work for partial BA during incremental SfM?
2. Is there a better way to initialize intrinsics before BA?
3. Is it sufficient to only consider camera intrinsics groups during BA? Are there other places it should be considered?

**Comment by MikeUnverferth** [comment]
In many cases, all of the images come from the same camera. For these cases would it still make the most sense to use groups (one group) as described above or would it be simpler to add a parameter to ReconstructionEstimatorOptions to just specify that for BA when setting up the Ceres problem? If this would be simple, any guidance on how to do it would be appreciated.

Any thoughts on when or if this enhancement might be implemented?

**Comment by sweeneychris** [comment]
This option will definitely be implemented, but probably not until February at the earliest. I am finishing my PhD thesis at the moment and do not have time to implement it until I am finished defending my thesis. 

Having all images from the same camera is really a special case of having any number of cameras with shared intrinsics. To do it right, it only makes sense to implement the case for any number of cameras. If you have more input on how the API should look, I welcome the suggestions

**Comment by pmoulon** [comment]
Why not consider each image (view) have a id related to an intrinsic group (as it is done in OpenMVG)?
It allows to use shared or not shared intrinsic easily.
https://github.com/openMVG/openMVG/blob/master/src/openMVG/sfm/sfm_view.hpp#L26

**Comment by sweeneychris** [comment]
I would like to keep the ``Camera`` class as a stand-alone class that will always know its own intrinsics since ``Camera`` does not depend on ``View`` or ``Reconstruction`` information so it is a useful class on its own. In my opinion the ``Camera`` class should not need knowledge of a ``Reconstruction`` in order to retrieve its intrinsic parameters.

Shared intrinsics are only necessary for bundle adjustment, since they cannot be easily used for two-view matching or other steps of the pipelines. So there is little need to add logic for shared intrinsics throughout the entire system

**Comment by MikeUnverferth** [comment]
Any idea when this might be available? In a lot of the reconstructions I have run the derived intrinsics vary quite widely and I believe this is causing significant distortion in the result especially at the edges of the model.

**Comment by sweeneychris** [comment]
@stoyanovd has made a first attempt at this. Unfortunately, I have been really busy and haven't had time to do a proper code review. 

One thing you can do to help improve results is provide a calibration file beforehand if possible. Alternatively you can modify the code a bit to constrain the movement of camera intrinsics during BA. For instance, you can add some lower and upper bounds [here](https://github.com/sweeneychris/TheiaSfM/blob/master/src/theia/sfm/bundle_adjustment/bundle_adjustment.cc#L137) so that each intrinsic parameter can only change by e.g. 10% of its value (i.e. set lower and upper bounds at 0.9 * val and 1.1 * val). This should help constrain the intrinsic parameters but you may have to play with what % will give the best results

**Comment by sweeneychris** [comment]
https://github.com/sweeneychris/TheiaSfM/commit/fccd05ffe298d3f883448f319379906fe0338c2b

Done!
