### ISSUE TITLE
Triangulation enhancement

### ISSUE THREAD

**Issue by nosleduc** [sweeneychris/TheiaSfM#43]
Did you read this article "Fury of the Swarm: Efficient and Very Accurate Triangulation for Multi-View
Scene Reconstruction" to improve triangulation ?

**Comment by sweeneychris** [comment]
I have briefly read this article and the authors' related works. The papers, in my own opinion, do not give very convincing results that they are better than alternative methods like the DLT or midpoint algorithms for triangulation (no direct comparison given). For SfM in Theia, we apply nonlinear optimization to 3D points after initial estimation with the midpoint algorithm (see here: https://github.com/sweeneychris/TheiaSfM/blob/master/src/theia/sfm/estimate_track.cc#L204). Note that we only optimize the 3D point, so it is not bundle adjustment at this point (that happens later)

I can't say I have ever had triangulation + refinement give unsatisfactory accuracy or efficiency in SfM... Are you finding Theia's triangulation to be inadequate? I'm always open to suggestions

**Comment by nosleduc** [comment]
I've not already tested your library. I discovered your library last week.
I've tested the article with a Nelder-Mead simplex instead of particle swarm optimisation. I compared it with the OpenCV triangulation method (I think it is a DLT method in OpenCV) and the results were less sensitive to errors.
I was wondering if you have tested by your own

**Comment by sweeneychris** [comment]
No I have not. As mentioned, triangulation plus nonlinear optimization afterwards has been great for me. But if you are worried about robustness to outliers, then you can always alter the code to use a robust cost function like Huber during the triangulation nonlinear optimization.
