### ISSUE TITLE
Compilation fails due to array index out of bounds

### ISSUE THREAD

**Issue by hovren** [sweeneychris/TheiaSfM#46]
Trying to compile, I get this error (both on current master, and v0.5):

    /home/hannes/Source/TheiaSfM/src/theia/image/keypoint_detector/sift_detector.cc: In member function     ‘virtual bool theia::SiftDetector::DetectKeypoints(const FloatImage&, std::vector<theia::Keypoint>*)’:
    /home/hannes/Source/TheiaSfM/src/theia/image/keypoint_detector/sift_detector.cc:103:33: error: array subscript is above array bounds [-Werror=array-bounds]
         keypoint.set_orientation(angles[j]);
                                 ^

This seems strange, because I can't see how the compiler could have any idea what `num_angles` will contain, since it is calculated by `vl_sift_calc_keypoint_orientations()`.
Adding `--Wno-array-bounds` to the CXX_FLAGS made it compile but this seems like the wrong way to go.

I am using Fedora 23 (x64) with GCC 5.1.1

**Comment by sweeneychris** [comment]
You're right this seems to be a pretty bizarre compiler error. I looked into `vl_sift_calc_keypoint_orientations()` and the function will only return a maximum of 4 angles, so it does seem bizarre that the compiler is getting mad.

I'm going to look into it more. Hopefully there is a minimal solution to the problem
