### ISSUE TITLE
new global algorithm

### ISSUE THREAD

**Issue by daleydeng** [sweeneychris/TheiaSfM#50]
Hi, is there any plan to add new start of art SfM algorithm, proposed by Ping Tan?

Global Structure-from-Motion by Similarity Averaging, 
Zhaopeng Cui, Ping Tan,
International Conference on Computer Vision (ICCV), Santiago, Chile, Dec. 2015.

**Comment by sweeneychris** [comment]
Unfortunately, I do not have plans to add this algorithm at this time as I am finishing my degree at the moment. It would be great if you can add this algorithm to Theia!

**Comment by daleydeng** [comment]
Ok, I'll try when i'm free, thanks for the released excellent library

**Comment by nosleduc** [comment]
Any progress on that ?

**Comment by daleydeng** [comment]
the author of their paper said he will release their code soon, waiting for that~

**Comment by sweeneychris** [comment]
@daleydeng awesome! I'm looking forward to seeing it in Theia's pipeline:)

Why don't you shoot me and email once you start implementing the similarity averaging within Theia so I can help you plan the integration? It helps me a lot if you use Gerrit for submitting new changes.

**Comment by daleydeng** [comment]
@sweeneychris:  allright, I'll check the paper and theia source code in more detail, when I'm have a plan and ready I'll shoot you!

**Comment by sweeneychris** [comment]
I'm going to close this issue for now. Feel free to reopen it if an implementation comes online
