### ISSUE TITLE
Optimizing the Viewing Graph for Structure-from-Motion

### ISSUE THREAD

**Issue by daleydeng** [sweeneychris/TheiaSfM#52]
I've also read your excellent paper  "Optimizing the Viewing Graph for Structure-from-Motion" in ICCV15, will it be avaliable in this library?

**Comment by sweeneychris** [comment]
Unfortunately, I do not have plans to integrate the method into Theia. It requires some large changes to the reconstruction pipeline that would disrupt the current methods too much.

**Comment by rakshith95** [comment]
Hello @sweeneychris , 
Is the code for the "Optimizing the Viewing Graph for Structure-from-Motion" available anywhere? I wasn't able to find it.
