### ISSUE TITLE
OpenGV enhancement

### ISSUE THREAD

**Issue by daleydeng** [sweeneychris/TheiaSfM#53]
I've seen opengv is another good solution to fundamental minimal problem, such as PnP, Relative Pose problem for both central and non-central cameras. They use bearing vector instead of pixel which could represent more calibrated camera models, such as fisheye, panorama, stereo rig and etc.I think its another direction of enhancement~~

Personally, I'm working on a reconstruction project based on streetview panoramas, so camera model is relevent~

http://laurentkneip.github.io/opengv/

**Comment by sweeneychris** [comment]
Theia has minimal solvers for pretty much all of the same sorts of problems, including the case where IMU data is available: https://github.com/sweeneychris/TheiaSfM/tree/master/src/theia/sfm/pose

The interfaces to those functions often uses bearing vectors, so you should be able to utilize these methods appropriately.

**Comment by daleydeng** [comment]
All right, I'll checkit out~~
