### ISSUE TITLE
Installation: Fail to find ImageMagick error

### ISSUE THREAD

**Issue by himanshub43** [sweeneychris/TheiaSfM#55]
Hi,
I am to install Theia on my laptop( Mac OSX). However I'm getting the following error during compilation, even after installing ImageMagick(/opt/local/include) and all other dependencies. Please help me zero-down where I'm going wrong.
 Thanks in advance.
<img width="1030" alt="screen shot 2016-01-15 at 04 18 11" src="https://cloud.githubusercontent.com/assets/6290745/12340707/8826f81e-bb42-11e5-8166-17bed5eabe4e.png">

**Comment by sweeneychris** [comment]
It seems to be looking for the executable commands "mogrify" and "convert" that are provided by ImageMagick. Are you sure those commands are working?

**Comment by sweeneychris** [comment]
Was your problem solved? If so, I would like to ask that you close this issue.

**Comment by himanshub43** [comment]
Sure, thanks for the help.
