### ISSUE TITLE
File format for feature and matches files

### ISSUE THREAD

**Issue by nosleduc** [sweeneychris/TheiaSfM#56]
Hi 

I would like to test the build_reconstruction application provided in theia.
I have the image points, the matches and the camera parameters
How can I write them into the feature/matches/calibration files ?

**Comment by sweeneychris** [comment]
Thanks for the interest in the library. You can find methods to read and
write all of those things in this directory:
https://github.com/sweeneychris/TheiaSfM/tree/master/src/theia/io

If you just fill the relevant data structs then you can call those methods
to write the data to a file.

Chris

**Comment by nosleduc** [comment]
Can I make only a match file without feature and calibration files to run buid_reconstruction ?

If yes, there is my code to write the match file. Does it seems correct because when I'm trying to use the build_reconstruction application I have the following message:

I0126 21:37:15.530659 1970696192 track_builder.cc:124] 9797 tracks were created. 0 features were dropped because they formed inconsistent tracks, and 0 features were dropped because they formed singleton tracks.
I0126 21:37:15.545860 1970696192 reconstruction_builder.cc:317] Attempting to reconstruct 10 images from 45 two view matches.
I0126 21:37:15.545912 1970696192 global_reconstruction_estimator.cc:170] Filtering the intial view graph.
I0126 21:37:15.545977 1970696192 global_reconstruction_estimator.cc:173] Insufficient view pairs to perform estimation.
F0126 21:37:15.545986 1970696192 build_reconstruction.cc:375] Check failed: reconstruction_builder.BuildReconstruction(&reconstructions) Could not create a reconstruction.




struct Pt{
    bool detected = false;
    Eigen::Vector2d pt;
};

void writeMatches(const std::vector<std::vector<Pt> > &points,
                  const std::vector<std::string> & view_names,
                  const std::string & filename,
                  double focal,
                  int width, int height,
                  int nbRows, int nbCols){

    std::vector<theia::CameraIntrinsicsPrior> camera_intrinsics_prior;
    theia::CameraIntrinsicsPrior params;
    params.aspect_ratio.value = 1.0;
    params.aspect_ratio.is_set = true;
    params.focal_length.value = focal;
    params.focal_length.is_set = true;
    params.image_width = width;
    params.image_height = height;
    params.principal_point[0].value = width/2;
    params.principal_point[0].is_set = true;
    params.principal_point[1].value = height/2;
    params.principal_point[1].is_set = true;
    params.skew.value = 0.0;
    params.skew.is_set = true;
    params.radial_distortion[0].value = 0.0;
    params.radial_distortion[1].value = 0.0;
    params.radial_distortion[0].is_set = false;
    params.radial_distortion[1].is_set = false;
    for(size_t i = 0; i < view_names.size(); ++i)
        camera_intrinsics_prior.push_back(params);


    std::vector<theia::ImagePairMatch> matches;
    for(size_t i = 0; i < view_names.size(); ++i){
        const auto  & pts1 = points[i];
        for(size_t j = i + 1; j < view_names.size(); ++j){
            const auto  & pts2 = points[j];
            int count = 0;

            for(int y = 0; y < nbRows; ++y){
                for(int x = 0; x < nbCols; ++x){
                    const auto & pt1 = pts1[y * nbCols + x];
                    const auto & pt2 = pts2[y * nbCols + x];
                    if (pt1.detected && pt2.detected){
                        ++count;
                    }
                }
            }

            if (count >= 16){
                count = 0;
                theia::ImagePairMatch match;
                match.image1 = view_names[i];
                match.image2 = view_names[j];

                for(int y = 0; y < nbRows; ++y){
                    for(int x = 0; x < nbCols; ++x){
                        const auto & pt1 = pts1[y * nbCols + x];
                        const auto & pt2 = pts2[y * nbCols + x];
                        if (pt1.detected && pt2.detected){
                            ++count;
                            theia::FeatureCorrespondence mat;
                            mat.feature1 = pt1.pt;
                            mat.feature2 = pt2.pt;
                            match.correspondences.push_back(mat);
                        }
                    }
                }
                matches.push_back(match);
            }
        }
    }

    theia::WriteMatchesAndGeometry(filename, view_names, camera_intrinsics_prior, matches);
}

**Comment by sweeneychris** [comment]
It seems you are not setting the filename vector at all? This needs to include all names from the view_names vector that you want to be estimated with SfM.

**Comment by nosleduc** [comment]
It is a small piece of my code. It is just a function
the filename, the view_names are set before calling this function.
I think I've found the solution. The matches needs to be checked before writing them into files.
I've added the following code

 theia::VerifyTwoViewMatchesOptions options;
                std::vector<int> result;
                theia::VerifyTwoViewMatches(options, params, params, match.correspondences, &match.twoview_info, &result);
              
I thought that the build_reconstruction application would check it for me.

I'm testing the global and the incremental structure from motion and I've some strange results.
With a few pictures the result is correct but if I'm adding more pictures the number of points decreases.

**Comment by sweeneychris** [comment]
Ah, yes that makes sense good catch with the matches.

SfM is very finicky process, but incremental and global methods each have their advantages. Usually global SfM is less robust to challenging scenes, but it often helps both methods if you use a robust cost function for BA for difficult scenes. You can try adjusting this option: https://github.com/sweeneychris/TheiaSfM/blob/master/applications/build_reconstruction_flags.txt#L99

If you send me the dataset to my email I can help you adjust the flagfile for optimal results

**Comment by nosleduc** [comment]
I've already changed it to huber.
I will send you some data files to test after testing by my own

**Comment by sweeneychris** [comment]
I think this issue has been resolved (as it pertains to the matching and feature file formats). Can we close it?
