### ISSUE TITLE
Error with export_reconstruction_to_pmvs

### ISSUE THREAD

**Issue by nuernber** [sweeneychris/TheiaSfM#57]
I got this error when trying to use pmvs:

> No vis.dat although specified to initVisdata2:
> /...../pmvs_working_dir/vis.dat

After changing the option "useVisData" from 1 to 0, pmvs ran successfully.

**Comment by sweeneychris** [comment]
This is indeed an error -- can you submit the trivial patch?

**Comment by nuernber** [comment]
I pushed it to gerrithub just now.

**Comment by sweeneychris** [comment]
https://github.com/sweeneychris/TheiaSfM/commit/62cda60f2f00d4212da42b143bb9e1722734622e

Done.
