### ISSUE TITLE
Include akaze-eigen to Theia

### ISSUE THREAD

**Issue by green-zone** [sweeneychris/TheiaSfM#58]
Why not?
I really liked VisualSFM and Bundler (small sizes).
Just have not found a replacement for the SIFT
with a completely free license.

I compiled akaze-eigen on MinGW 32bit
I want to link it to Bundler + pmvs

**Comment by green-zone** [comment]
Ok, i found simple way:
https://code.google.com/archive/p/osm-bundler/source/default/source
osm-bundler/sandbox/surf/**surf2sift.py**

akaze-eigen (features) --> surf --> sift --> etc
Not fully tested and i need c++ realization **surf2sift** (as separate exe file)
I go do this.

**Comment by sweeneychris** [comment]
SURF is also patented and must be licensed.

I wrote the akaze-eigen library so it should be simple for me to integrate it into Theia. I just started a new job (postdoc at UW) so if you give me a few weeks I can probably integrate this into Theia

**Comment by green-zone** [comment]
It will be good integration.
In akaze-eigen surf used only for output file format, not? (It not use algoritms of surf)

**Comment by pmoulon** [comment]
It uses:
- M/SURF like descriptor if you choose the float based descriptor.
- or the M-LDB binary descriptor.
See here https://github.com/pablofdezalc/akaze/blob/master/src/lib/AKAZEConfig.h#L41

@sweeneychris Congrats for your new position at UW :+1:

**Comment by green-zone** [comment]
I do not know what license have M-LDB.
And Bundler need 256 integers keys as input. Conversion from float to int (i think) is not good idea.
I do not understand how i can do this well. (small  knowledges in c++ and in formats of descriptors)

It may be interesting:
I found **DAISY**: A Fast Local Descriptor for Dense Matching (BSD License)
 http://cvlab.epfl.ch/software/daisy

**Comment by pmoulon** [comment]
M-LDB have no license.
I think that using more modular SfM framework like TheiaSfM & OpenMVG is better to test any feature/descriptor combination.

DAISY is a framework to compute dense descriptor in an efficient way at a given scale, not a random scale. So you will have to compute the convolution at each slice of the scale space.
You can also use a GLOH like descriptor.

The new trends consists in using descriptor that are using image patches with projection matrix learned by deep learning methods.

**Comment by green-zone** [comment]
Ok, i look to RoboStruct https://github.com/robocyte/RoboStruct
It use OpenCV library. RoboStruct use YAPE-DAISY or AKAZE for features.
YAPE (Yet Another Point Extractor) http://cvlabwww.epfl.ch/~lepetit/
And posible export result to PMVS, Bundler or MeshLab projects.

RoboStruct provide binary program for Win64 and source code.
I need see him code for convertation or look directly to OpenCV

Now, i have collections of small programs from Bundler an akaze-eigen, and daisy
I need combine them to **small** workflow.
Or wait TheiaSFM combination with akaze-eigen :)

**Comment by sweeneychris** [comment]
Done. https://github.com/sweeneychris/TheiaSfM/commit/7770eb44166eb495333e9325f78b253f5bc4f548
