### ISSUE TITLE
Handling repetitive structures in theia

### ISSUE THREAD

**Issue by avanindra** [sweeneychris/TheiaSfM#60]
Hi,

I was wondering if you can give me hints or pointers for increasing robustness against scenes with repetitive structures. The global sfm pipeline works pretty reliably most of the cases , but occasionally I come across data with repetitive structures , in those cases , the global sfm is producing incorrect results , even quite worse than incremental sfm results . 

Regards

Avanindra

**Comment by sweeneychris** [comment]
It depends a bit on which position estimation solver you are using. Using the least unsquared deviations solver is usually quite robust. If you are using the nonlinear solver then you can increase `position_estimation_min_num_tracks_per_view` to 6 or 10, or adjust `position_estimation_robust_loss_width` to be 0.01 or smaller. Also, increasing the number of retriangulation iterations for global SfM should help, though this will increase the runtime by a lot.

You can also try to adjust the 1DSfM filter by adjusting these options: https://github.com/sweeneychris/TheiaSfM/blob/master/src/theia/sfm/reconstruction_estimator_options.h#L145   See the documentation here for an explanation of these params: https://github.com/sweeneychris/TheiaSfM/blob/master/src/theia/sfm/filter_view_pairs_from_relative_translation.h#L47

**Comment by sweeneychris** [comment]
Can we close the issue if this is solved?

**Comment by avanindra** [comment]
Yes , close the issue. I am getting good enough results for repetitive structures , to similar quality as incremental SFM.
