### ISSUE TITLE
reconstruction error with an external feature detector

### ISSUE THREAD

**Issue by edgarriba** [sweeneychris/TheiaSfM#62]
Hi @sweeneychris,

I'm trying to reconstruct a scene (fountain) with Theia using an external feature detector (AKAZE from OpenCV) but I haven't succeed with that. You can find the source code that I'm using [here](https://gist.github.com/edgarriba/38b3fa347107f0fbaf2e) with the error log which is a slightly modification of the sample you provide in [here](https://github.com/sweeneychris/TheiaSfM/blob/master/applications/build_reconstruction.cc#L334). I'm looking forward to hear any tip or fix. Thanks in advance!

**Comment by sweeneychris** [comment]
I am traveling this week so I will investigate this next week when I return to the office

**Comment by sweeneychris** [comment]
Actually I see the error immediately:

E0222 16:06:51.872550 29987 solver.cc:484] Terminating: Can't use SPARSE_NORMAL_CHOLESKY with SUITESPARSE because SuiteSparse was not enabled when Ceres was built.

You need to rebuild Ceres with SuiteSparse

**Comment by edgarriba** [comment]
tried that but I get the same error. Do I need CXSparse?

**Comment by sweeneychris** [comment]
Did you run make install in Ceres after adding suite sparse? Then you will
have to rebuild Theia as well.

**Comment by sweeneychris** [comment]
Did you resolve the Ceres dependency? If so, could we please close this issue?

**Comment by edgarriba** [comment]
I didn't. I compiled Ceres with Suitespare flag ON (even tried with cxspare and eigensparse), removed old Ceres and Theia from system and installed again but still getting the same log error with GLOBAL pipeline.

**Comment by sweeneychris** [comment]
If it is still saying Ceres was not built with SuiteSparse then something is wrong with your Ceres installation still. When you build Ceres I would make sure in the CMake step that it is indeed using SuiteSparse. Perhaps you should contact the Ceres authors to receive direct help?

**Comment by edgarriba** [comment]
yes, it's weird. I have used Ceres before and I haven't had such error. thanks!
