### ISSUE TITLE
Estimator RefineModel method never called

### ISSUE THREAD

**Issue by nosleduc** [sweeneychris/TheiaSfM#63]
Hi

I noticed that there is a method named RefineModel in the Estimator class.
I assume that this method is here to be called at the end of an ransac algorithm to refine the model from the inliers. It seems that this method is never called directly in theia.

Is it normal ?

**Comment by sweeneychris** [comment]
This method is not used as part of the SampleAndConsensus interface, but I made it available so that derived classes could easily call this. Also, it makes the user explicitly aware of the non-minimal case so that they can extend their own code easily.
