### ISSUE TITLE
Compile fails against latest eigen release

### ISSUE THREAD

**Issue by stickshift** [sweeneychris/TheiaSfM#64]
Complains about a missing internal class tridiagonal_qr_step. I had to downgrade eigen to get past it.

TheiaSfM-0.5/libraries/spectra/include/LinAlg/TridiagEigen.h:93:13: error: no matching function for call to 'tridiagonal_qr_step'
            Eigen::internal::tridiagonal_qr_step<Eigen::ColMajor>(maind, subd, start, end, evecs.data(), n);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by sweeneychris** [comment]
I believe this has been fixed already in the master branch. Can you confirm for your machine/configuration?

**Comment by stickshift** [comment]
Yup, you're right. I tested again with latest master branch and it worked
fine. Thanks!

Best,
Andy
