### ISSUE TITLE
Not initialized

### ISSUE THREAD

**Issue by cdcseacave** [sweeneychris/TheiaSfM#65]
I think in JenkinsTraubSolver::ApplyLinearShiftToKPolynomial the variable polynomial_at_root should be initialized to zero. Sorry if I'm mistaken.

**Comment by sweeneychris** [comment]
In this case, it does not matter -- prev_polynomial_at_root is only utilized after the 2nd iteration, and polynomial_at_root is set in the next line.

**Comment by cdcseacave** [comment]
thx
