### ISSUE TITLE
Tilde expansion in arguments

### ISSUE THREAD

**Issue by mrquincle** [sweeneychris/TheiaSfM#7]
A very small bug, arguments can not cope with `~` (although `$HOME` is fine). Relative paths are fine, just tilde expansion seems to have been overlooked.

```
./extract_features --input_imgs=~/some.jpg --img_output_dir=~/results --descriptor=SIFT
```
Results in:
```
F0222 19:41:21.850764 15771 extract_features.cc:79] Check failed: theia::GetFilepathsFromWildcard(FLAGS_input_imgs, &img_filepaths) 
*** Check failure stack trace: ***
    @     0x7f8c450c1c6c  (unknown)
    @     0x7f8c450c1bb8  (unknown)
    @     0x7f8c450c15ba  (unknown)
    @     0x7f8c450c4551  (unknown)
    @           0x41449d  main
    @     0x7f8c440beec5  (unknown)
    @           0x41498f  (unknown)
    @              (nil)  (unknown)
[1]    15771 abort      ./extract_features --input_imgs=~/some.jpg 
```
Same is going on for `img_output_dir`.

**Comment by Meekohi** [comment]
http://stackoverflow.com/questions/15991241/how-do-i-achieve-tilde-expansion-in-c probably needed for a fix.

**Comment by sweeneychris** [comment]
The filesystem part of Theia is handled with the STLPlus3 library... it seems they do not handle the tilde expansion either.

Rather than trying to patch STLPlus3 (and remain cross-platform) I will just add a warning when GetFilepathsFromWildcard fails that suggests not to use tildes.
