### ISSUE TITLE
Use weights in AlignPointCloudsUmeyama

### ISSUE THREAD

**Issue by nosleduc** [sweeneychris/TheiaSfM#74]
Is it possible to add weights on the matching with AlignPointCloudsUmeyama ?
I think the new formula will become:

ux replaced by  ux = sum(wi * xi)/sum(wi)
uy replaced by  uy = sum(wi * yi)/sum(wi)
sx_2 replaced by sx_2 = sum(wi * (xi -ux)^2)/sum(wi)
sy_2 replaced by sy_2 = sum(wi * (yi -uy)^2)/sum(wi)
sxy replaced by sxy = sum(wi * (yi - uy) * (xi - ux)')/sum(wi)

**Comment by sweeneychris** [comment]
That seems sensible. Can you submit a patch via Gerrit? It would be nice to simply add this as an additional method to the current align_point_clouds.h/cc  Also, please include a unit test to ensure the functionality is correct.

**Comment by nosleduc** [comment]
I will try to do it by the end of the week

**Comment by sweeneychris** [comment]
Done. Thanks! https://github.com/sweeneychris/TheiaSfM/commit/85df122f82de99759a944c098c9b97d6240a828f
