### ISSUE TITLE
Implement Guided Matching

### ISSUE THREAD

**Issue by sweeneychris** [sweeneychris/TheiaSfM#77]
Rajvi Shah's work has some nice proposals for guided matching. If we use this combined with the cascade hasher we should get some nice improvements in track length and quality.

http://arxiv.org/pdf/1512.06235.pdf

**Comment by daleydeng** [comment]
I have implement a guided matching based on this paper, and the key is to implement epipolar partitions for the candidate matching points and linear search with it. However I'm implement it with python.

The following is the core code:

import numpy as np
from pyclib.pptheia.matching import FeatureMatcher
from cvai.common import hstack
from cvai.math_ import Rt_center, project_xs, nullspace
from .match import match_knn_twoway

def _calc_epipolar_angles(xs0, xs1, relP):
    C = Rt_center(relP)
    xs1 = np.dot(xs1, relP[:,:3])
    az = C
    ax, ay = nullspace([az], 2)
    coord = hstack(ax, ay, az)
    new_xs0 = np.dot(xs0, coord)
    epi_angles0 = np.arctan2(new_xs0[:,1], new_xs0[:,0])

    new_xs1 = np.dot(xs1, coord)
    epi_angles1 = np.arctan2(new_xs1[:,1], new_xs1[:,0])
    return epi_angles0, epi_angles1

def _group_keys(epi_angles, delta, off, nr_th):
    grps = {}
    for ii, i in enumerate(epi_angles):
        gi = int((i+off)//delta)
        if gi not in grps:
            grps[gi] = []
        grps[gi].append(ii)

    del_gids = [k for k, v in grps.items() if len(v) < nr_th]
    for i in del_gids:
        del grps[i]
    return grps

def _guided_match_offset(epi_angles0, epi_angles1, descs0, descs1, delta, off, ratio, nr_th, meth='theia_bf'):
    grps0 = _group_keys(epi_angles0, delta, off, nr_th)
    grps1 = _group_keys(epi_angles1, delta, off, nr_th)
    common_gids = grps0.keys() & grps1.keys()
    out_ms = set()
    if meth == 'knn':
        for gid in common_gids:
            ids0, ids1 = grps0[gid], grps1[gid]
            gdescs0, gdescs1 = descs0[ids0], descs1[ids1]

            gms = match_knn_twoway(gdescs0, gdescs1, nr_th=0, ratio=ratio)
            if len(gms):
                out_ms |= set((ids0[int(i)], ids1[int(j)]) for i, j in gms)
    elif meth == 'theia_bf':
        matcher = FeatureMatcher(meth='bf', lowes_ratio=ratio, min_feature_nr=0, cache_capacity=len(common_gids)*2)
        mlist = []
        for gid in common_gids:
            ids0, ids1 = grps0[gid], grps1[gid]
            gdescs0, gdescs1 = descs0[ids0], descs1[ids1]

            n0, n1 = 'img0_'+str(gid), 'img1_'+str(gid)
            matcher.add_image(n0, gdescs0)
            matcher.add_image(n1, gdescs1)
            mlist.append((n0, n1))

        matcher.set_match_list(mlist)
        for i, j, gms in matcher.match_images():
            gid = int(i.split('_')[-1])
            ids0, ids1 = grps0[gid], grps1[gid]
            if not len(gms):
                continue

            ms = set((ids0[int(ii)], ids1[int(jj)]) for ii, jj in gms)
            out_ms |= ms

    return out_ms

def guided_matching(xs0, xs1, descs0, descs1, relP, id_mapping0=None, id_mapping1=None, delta=0.01, ratio=0.6, nr_th=20):

    descs0, descs1 = np.asarray(descs0), np.asarray(descs1)
    epi_angles0, epi_angles1 = _calc_epipolar_angles(xs0, xs1, relP)
    ms0 = _guided_match_offset(epi_angles0, epi_angles1, descs0, descs1, delta, 0, ratio=ratio, nr_th=nr_th)
    ms1 = _guided_match_offset(epi_angles0, epi_angles1, descs0, descs1, delta, delta/2, ratio=ratio, nr_th=nr_th)
    ms = ms0 | ms1
    if id_mapping0:
        ms = set((id_mapping0[i], j) for i, j in ms)
    if id_mapping1:
        ms = set((i, id_mapping1[j]) for i, j in ms)
    return ms

**Comment by daleydeng** [comment]
The results is as follows, with guided matching, we can use far more few tracks to do reconstruction, then use the guided matches to enhance the results.

After guided matching: 150k 3D points
![selection_075](https://cloud.githubusercontent.com/assets/770506/15501268/2ffb80de-21df-11e6-95db-60b321614016.png)

Before guided matching: 22k 3D points
![selection_076](https://cloud.githubusercontent.com/assets/770506/15501275/35d0ecc4-21df-11e6-9955-3e36f415a553.png)

**Comment by sweeneychris** [comment]
This looks awesome! I actually have a guided matching implementation under review right now: https://review.gerrithub.io/#/c/276526/   I will probably add the KD tree part of it in a later commit.

Is your theia python wrapper available online? I would be happy to post a link to it on the Theia website if you would like

**Comment by daleydeng** [comment]
Ok, I'll prepare for it, I only made the used parts in theia, I'll post it soon~

**Comment by sweeneychris** [comment]
Guided matching has now been fully implemented. The interface for 2-view guided matching is [here](https://github.com/sweeneychris/TheiaSfM/blob/master/src/theia/matching/guided_epipolar_matcher.h) and it could be easily incorporated into a "compute structure from known poses" system.

I'm going to close this issue since the feature is implemented. Feel free to open this or a new one if you have issues with the guided matching.
