### ISSUE TITLE
test build_1dsfm_reconstruction failed

### ISSUE THREAD

**Issue by jakexie** [sweeneychris/TheiaSfM#79]
**/home/super/program/TheiaSfM/buid/bin/build_1dsfm_reconstruction -   flagfile=/home/super/program/data_test/Tower_of_London/images/build_1dsfm_reconstruction_flags.txt
I0509 23:44:17.877241 12210 read_1dsfm.cc:375] Reading connected components.
E0509 23:44:17.877352 12210 read_1dsfm.cc:98] Cannot read the cc file from /home/super/program/data_test/Tower_of_London/images/*.jpg/cc.txt
F0509 23:44:17.877367 12210 build_1dsfm_reconstruction.cc:231] Check failed: Read1DSFM(FLAGS_1dsfm_dataset_directory, reconstruction.get(), view_graph.get()) Could not read 1dsfm dataset from /home/super/program/data_test/Tower_of_London/images/*.jpg
**

I'm a newbie of theiaSFM. when i run the build_1dsfm_reconstruction program , i got this error. 
 if somebody could help me , i shall be very grateful that!

**Comment by sweeneychris** [comment]
The error is listed in the output:

Cannot read the cc file from
/home/super/program/data_test/Tower_of_London/images/.jpg/cc.txt

You'll need to pass in the directory where the tower of London dataset is
located so theia can correctly find the cc.txt file (as well as the other
1dsfm files)

**Comment by jakexie** [comment]
@sweeneychris thank you. but l don't have the "cc.txt" in my 1dsfm files. May i generate it by myself?

**Comment by sweeneychris** [comment]
No, you will have to download a dataset from here: http://www.cs.cornell.edu/projects/1dsfm/

If you want to run SfM on a generic dataset (1dsfm is a specialized benchmark dataset), then please use the build_reconstruction.cc file instead. There are lots of instructions available in the files themselves and on the website www.theia-sfm.org

**Comment by jakexie** [comment]
thank you
