### ISSUE TITLE
eigen3 error

### ISSUE THREAD

**Issue by jakexie** [sweeneychris/TheiaSfM#80]
when  i run test "linear_rotation_estimator_test" "orientation_frommaximum_spanning_tree_test" "build_reconstruction" "build_1dsfm_reconstruction" , i get following error :
 $ ./linear_rotation_estimator_test --logtostderr
I0513 10:44:51.698424 25703 test_main.cc:46] Running tests with logs enabled.
[==========] Running 6 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 6 tests from EstimateRotationsLinearTest
[ RUN      ] EstimateRotationsLinearTest.SmallTestNoNoise
linear_rotation_estimator_test: /usr/include/eigen3/Eigen/src/Core/Block.h:141: Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Block(XprType&, Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Index, Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Index, Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Index, Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Index) [with XprType = Eigen::Matrix<double, -1, -1>; int BlockRows = -1; int BlockCols = -1; bool InnerPanel = false; Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Index = long int]: Assertion `a_startRow >= 0 && blockRows >= 0 && a_startRow <= xpr.rows() - blockRows && a_startCol >= 0 && blockCols >= 0 && a_startCol <= xpr.cols() - blockCols' failed.
Aborted

 $ ./orientations_from_maximum_spanning_tree_test 
[==========] Running 2 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 2 tests from OrientationsFromViewGraph
[ RUN      ] OrientationsFromViewGraph.SmallTest
orientations_from_maximum_spanning_tree_test: /usr/include/eigen3/Eigen/src/Core/Block.h:141: Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Block(XprType&, Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Index, Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Index, Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Index, Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Index) [with XprType = Eigen::Matrix<double, -1, -1>; int BlockRows = -1; int BlockCols = -1; bool InnerPanel = false; Eigen::Block<XprType, BlockRows, BlockCols, InnerPanel>::Index = long int]: Assertion `a_startRow >= 0 && blockRows >= 0 && a_startRow <= xpr.rows() - blockRows && a_startCol >= 0 && blockCols >= 0 && a_startCol <= xpr.cols() - blockCols' failed.
Aborted

**Comment by sweeneychris** [comment]
What version of Eigen are you using? If you use 3.2.8 do you still have
this error?

**Comment by jakexie** [comment]
the error has gone when i use eigen 3.2.8.
