### ISSUE TITLE
Ubuntu 16.04 Test Failures

### ISSUE THREAD

**Issue by headart** [sweeneychris/TheiaSfM#81]
Hey There,

I just installed a clean version of Ubuntu 16.04 but seem to be getting some test failures in the following areas:
	  4 - brute_force_feature_matcher_test (Failed)
	  5 - cascade_hashing_feature_matcher_test (Failed)
	 13 - normalized_graph_cut_test (SEGFAULT)
	 29 - estimate_relative_pose_test (Failed)

This is the output for the test 4
[==========] Running 6 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 6 tests from BruteForceFeatureMatcherTest
[ RUN      ] BruteForceFeatureMatcherTest.NoOptionsInCore
/home/jhm/dev/TheiaSfM/src/theia/matching/brute_force_feature_matcher_test.cc:84: Failure
      Expected: matches[0].correspondences.size()
      Which is: 0
To be equal to: kNumDescriptors
      Which is: 10
[  FAILED  ] BruteForceFeatureMatcherTest.NoOptionsInCore (1 ms)
[ RUN      ] BruteForceFeatureMatcherTest.RatioTestInCore
[       OK ] BruteForceFeatureMatcherTest.RatioTestInCore (0 ms)
[ RUN      ] BruteForceFeatureMatcherTest.SymmetricMatchesInCore
/home/jhm/dev/TheiaSfM/src/theia/matching/brute_force_feature_matcher_test.cc:163: Failure
      Expected: matches[0].correspondences.size()
      Which is: 0
To be equal to: 1
[  FAILED  ] BruteForceFeatureMatcherTest.SymmetricMatchesInCore (0 ms)
[ RUN      ] BruteForceFeatureMatcherTest.NoOptionsOutOfCore
/home/jhm/dev/TheiaSfM/src/theia/matching/brute_force_feature_matcher_test.cc:198: Failure
      Expected: matches[0].correspondences.size()
      Which is: 752276
To be equal to: kNumDescriptors
      Which is: 10
[  FAILED  ] BruteForceFeatureMatcherTest.NoOptionsOutOfCore (0 ms)
[ RUN      ] BruteForceFeatureMatcherTest.RatioTestOutOfCore
/home/jhm/dev/TheiaSfM/src/theia/matching/brute_force_feature_matcher_test.cc:236: Failure
      Expected: matches[0].correspondences.size()
      Which is: 752376
To be equal to: 0
[  FAILED  ] BruteForceFeatureMatcherTest.RatioTestOutOfCore (2 ms)
[ RUN      ] BruteForceFeatureMatcherTest.SymmetricMatchesOutOfCore
/home/jhm/dev/TheiaSfM/src/theia/matching/brute_force_feature_matcher_test.cc:277: Failure
      Expected: matches[0].correspondences.size()
      Which is: 752376
To be equal to: 1
[  FAILED  ] BruteForceFeatureMatcherTest.SymmetricMatchesOutOfCore (1 ms)
[----------] 6 tests from BruteForceFeatureMatcherTest (4 ms total)

[----------] Global test environment tear-down
[==========] 6 tests from 1 test case ran. (4 ms total)
[  PASSED  ] 1 test.
[  FAILED  ] 5 tests, listed below:
[  FAILED  ] BruteForceFeatureMatcherTest.NoOptionsInCore
[  FAILED  ] BruteForceFeatureMatcherTest.SymmetricMatchesInCore
[  FAILED  ] BruteForceFeatureMatcherTest.NoOptionsOutOfCore
[  FAILED  ] BruteForceFeatureMatcherTest.RatioTestOutOfCore
[  FAILED  ] BruteForceFeatureMatcherTest.SymmetricMatchesOutOfCore

 5 FAILED TESTS

I can also post the other test results if you'd like.

There where some other issues following make instructions as I had to build Ceres-Solver to get the cmake linking properly as well installing Xmu and Xi and the mesa packages for OpenGL.

**Comment by sweeneychris** [comment]
Thanks James. I think this commit should fix the matching unit test errors: https://github.com/sweeneychris/TheiaSfM/commit/4c7a904fd20512450892c579f018b9b75a33895f

I would not worry about the normalized graph cut error for now -- it is not used within the SfM pipelines at all

**Comment by headart** [comment]
Thanks for the quick reply Chris; that commit has fixed the issues I was having. 

I have noticed that **estimate_relative_pose_test** and **estimate_essential_matrix_test** occasionally fail but I'm guessing it is just my computers solution falling outside the test's tolerance.

Time to get on with my project and see how things pan out.

**Comment by sweeneychris** [comment]
@headart Yes, those tests (and all the estimate_*_test files) are RANSAC-based processes so it is probably a thresholding issue. If you happen to have time and can find better tolerance values that make the tests consistently pass, feel free to report them or submit a patch
