### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by antonilo** [sweeneychris/TheiaSfM#82]
Library at compilation issues the following error:

 error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
           if (yi>=ref.height()) yi = ref.height()-1; if (nyi>=ref.height()) nyi = ref.height()-1;
           ^~
And many other similar errors do to the not guarding if clause. Is there a problem with the flags given to the compiler?

**Comment by sweeneychris** [comment]
That code does not seem to be from within the Theia library. Could you copy/paste more of the compiler error so that I can diagnose it?

**Comment by antonilo** [comment]
The code is actually from the cimg library. I suspect the problem is that I have a g++ 6.01 that does not support anymore that indentation. The problem was solved removing the compiler flag -Werror in all CMakeLists.

Here is a more verbose compiler error:

`/home/tony/Documents/Scripts/TheiaSfM/libraries/cimg/CImg.h: In static member function ‘static long int cimg_library::cimg::type<long int>::max()’:
/home/tony/Documents/Scripts/TheiaSfM/libraries/cimg/CImg.h:2306:65: warning: left shift of negative value [-Wshift-negative-value]
       static long max() { return ~((long)(-1L<<(8*sizeof(long)-1))); }
                                                                 ^
/home/tony/Documents/Scripts/TheiaSfM/libraries/cimg/CImg.h: In member function ‘cimg_library::CImg<T>& cimg_library::CImg<T>::assign(const cimg_library::CImg<t>&, const char*)’:
/home/tony/Documents/Scripts/TheiaSfM/libraries/cimg/CImg.h:9886:13: error: this ‘while’ clause does not guard... [-Werror=misleading-indentation]
             while (*s>='0' && *s<='9') ++s; if (sep=='%') ++s;
             ^~~~~
/home/tony/Documents/Scripts/TheiaSfM/libraries/cimg/CImg.h:9886:45: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘while’
             while (*s>='0' && *s<='9') ++s; if (sep=='%') ++s;
                                             ^~
[  8%] Building CXX object src/theia/CMakeFiles/theia.dir/image/keypoint_detector/sift_detector.cc.o
/home/tony/Documents/Scripts/TheiaSfM/libraries/cimg/CImg.h: In member function ‘cimg_library::CImg<T>& cimg_library::CImg<T>::assign(const cimg_library::CImg<t>&, const char*)’:
/home/tony/Documents/Scripts/TheiaSfM/libraries/cimg/CImg.h:9886:13: error: this ‘while’ clause does not guard... [-Werror=misleading-indentation]
             while (*s>='0' && *s<='9') ++s; if (sep=='%') ++s;
             ^~~~~
/home/tony/Documents/Scripts/TheiaSfM/libraries/cimg/CImg.h:9886:45: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘while’
             while (*s>='0' && *s<='9') ++s; if (sep=='%') ++s;
                                             ^~
/home/tony/Documents/Scripts/TheiaSfM/libraries/cimg/CImg.h: In member function ‘cimg_library::CImg<T>& cimg_library::CImg<T>::assign(const cimg_library::CImg<t>&, const char*)’:
/home/tony/Documents/Scripts/TheiaSfM/libraries/cimg/CImg.h:9886:13: error: this ‘while’ clause does not guard... [-Werror=misleading-indentation]
             while (*s>='0' && *s<='9') ++s; if (sep=='%') ++s;
             ^~~~~
/home/tony/Documents/Scripts/TheiaSfM/libraries/cimg/CImg.h:9886:45: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘while’
             while (*s>='0' && *s<='9') ++s; if (sep=='%') ++s;
`

**Comment by sweeneychris** [comment]
I removed the offending lines from Theia's Cmake. Can you confirm that the master branch fixes this issue?

**Comment by antonilo** [comment]
That solved the problem. Thanks for the quick support.
