### ISSUE TITLE
Affine correspondence based reconstruction

### ISSUE THREAD

**Issue by daleydeng** [sweeneychris/TheiaSfM#83]
There is a new paper in CVPR16 discussed about this:

Theory and Practice of Structure-from-Motion using Affine Correspondences
Carolina Raposo and Joao P. Barreto

http://arthronav.isr.uc.pt/~carolina/files/CVPRsubm.pdf

And MODS metioned in my homepage provides a fast and good affine region extractor and matcher as an alternative for VLFEAT

MODS: Fast and Robust Method for Two-View Matching from http://cmp.felk.cvut.cz/wbs/ 
https://github.com/daleydeng/mods

**Comment by sweeneychris** [comment]
These are neat papers, but would be very difficult to incorporate into Theia. The whole pipeline is quite different from traditional point-based systems
