### ISSUE TITLE
Gomory-Hu tree for track generation

### ISSUE THREAD

**Issue by daleydeng** [sweeneychris/TheiaSfM#84]
I also read a paper using a simple enough gomory-hu tree graph algorithm for track generation from image matches which can keep longer track and filter out bad matches when in inconsistence case. I think this could be enhanced to replace the simple graph based strategy in  theia track generation. 

Svarm L, Simayijiang Z, Enqvist O, et al. Point track creation in unordered image collections using Gomory-Hu trees[C]// Pattern Recognition (ICPR), 2012 21st International Conference on. IEEE, 2012:2116-2119.

igraph (http://igraph.org/c/) has out-of-box gomory-hu-tree algorithm

**Comment by sweeneychris** [comment]
The idea is very interesting but the paper is lacking in experiments. For instance, what is the speed of this method? Does it improve reconstruction quality and/or reprojection errors? I would like to know answers to those sorts of questions before implementing this. Do you know of other SfM projects that currently use this method?

**Comment by daleydeng** [comment]
Noop, I haven't test it but I thought it is easy enough to implement in python, I'll test it when I have time and then notify you～

**Comment by daleydeng** [comment]
The python wrapper I implemented has some dependencies based on pyplusplus to deal with, when I finished I'll post it up~

**Comment by sweeneychris** [comment]
Since there are no plans to incorporate this work I am going to close this issue.  Feel free to open this issue again if you find the the method provides significant performance improvements.
