### ISSUE TITLE
Theia fails occasionally if run repeatedly on the same dataset

### ISSUE THREAD

**Issue by oleg-alexandrov** [sweeneychris/TheiaSfM#9]
Chris, I encountered the following problem. I have a dataset on which Theia succeeds 9 out of 10 tries, but every now and then it fails, giving a wildly incorrect reconstruction (and the incorrect reconstruction is quite different each time). At some point,  I even got Theia to crash (with a larger dataset though, and this was not repeatable), so I would suspect that the problem is more of a software bug rather than non-uniqueness coming from multiple threads combined the randomness in RANSCAC or such.

The dataset in question is just 10 images, and they are very decent as far as I see it. There is sufficient perspective change between images, but they are still close enough for feature matching to work quite reliably. The camera has more rotation than translation motion between the frames for this set, but that is not a problem at all for the incremental BA algorithm I tried. 

I ran Theia's match_descriptors function, and I get a lot of features and matches, so I think that is not the problem. 

I also tried your latest code and the two sets of flags in the TheiaSFM/applications directory, and I did tweak the flags as well, nothing helps. 

If you are interested and have the time to take a look at this, I can pass you the pictures.

**Comment by sweeneychris** [comment]
For only 10 images I do not think that it is an error in multithreading. I
suspect that it may be due to a bad starting position for the rotations
solver. I have noticed this on very rare occasions when running Theia on
datasets of 1000 images or more.

Are you using
--refine_relative_translations_after_rotation_estimation=true? Try enabling
that to false and see if the problem still persists.

Yes, if you can pass me along the dataset then perhaps I can investigate.

**Comment by oleg-alexandrov** [comment]
I set --refine_relative_translations_after_rotation_estimation=false and the problem is still there. I will send you a link with the location of the dataset.

**Comment by oleg-alexandrov** [comment]
Bringing the discussion back online, it was my dataset which was messed up, having too much rotation and almost no translation. I am having much better luck with a more carefully designed image acquisition strategy. Thank you for the nice tool!
