### ISSUE TITLE
Calibration matrices are ill formed.

### ISSUE THREAD

**Issue by mhsung** [sweeneychris/TheiaSfM#90]
I get the following error on my own dataset:
"Calibration matrices are ill formed. Cannot optimize epipolar constraints."
In this case, should I provide calibration data estimated from the other programs?

**Comment by sweeneychris** [comment]
Where is that error coming from? The log output should give you the exact line that this message comes from.

**Comment by mhsung** [comment]
It's in 'reconstruction_estimator_utils.cc:77'.

**Comment by sweeneychris** [comment]
This commit should remove that error: https://github.com/sweeneychris/TheiaSfM/commit/8001505b1bcb60e129108f3b6c6652681258567c

However, if the matrix could not be inverted then it probably means that your calibration matrix data is ill-formed. I would suggest investigating the calibration matrix to ensure it is sane.

**Comment by mhsung** [comment]
In 'build_reconstruction' application, is 'calibration_file' optional? Or, do I have to provide calibration file when there is no exif file?

**Comment by sweeneychris** [comment]
Yes, it is optional but recommended. If there is no EXIF information then it will try to guess the focal length but usually that is hard to do. I would recommend running create_calibration_file_from_exif first. That usually gets a decent focal length estimate.

**Comment by mhsung** [comment]
I see. Now I get the following error:

W0622 14:12:18.992434  9037 residual_block.cc:131] 

Error in evaluating the ResidualBlock.

There are two possible reasons. Either the CostFunction did not evaluate and fill all    
residual and jacobians that were requested or there was a non-finite value (nan/infinite)
generated during the or jacobian computation. 

Residual Block size: 2 parameter blocks x 3 residuals

For each parameter block, the value of the parameters are printed in the first column   
and the value of the jacobian under the corresponding residual. If a ParameterBlock was 
held constant then the corresponding jacobian is printed as 'Not Computed'. If an entry 
of the Jacobian/residual array was requested but was not written to by user code, it is 
indicated by 'Uninitialized'. This is an error. Residuals or Jacobian values evaluating 
to Inf or NaN is also an error.  

Residuals:              nan          nan          nan 

Parameter Block 0, size: 3

    -98.9886 |          nan          nan          nan 
    -34.4842 |          nan          nan          nan 
    -65.7497 |          nan          nan          nan 

Parameter Block 1, size: 3

     17.9024 |          nan          nan          nan 
     29.3365 |          nan          nan          nan 
    -7.66663 |          nan          nan          nan 


And before this, I also get tons of the following NaN message:

I0622 14:12:11.769176  9063 filter_view_pairs_from_relative_translation.cc:229] Edge (???, ???) has ordering diff of -??? and a projection of nan from nan nan nan


Would the ill-posed calibration be a possible reason of these errors?

**Comment by sweeneychris** [comment]
Yes.

**Comment by sweeneychris** [comment]
If you can send me the dataset I would be happy to take a look and dig deeper into the problem.

**Comment by mhsung** [comment]
Thank you. Now I'm re-running everything (including features and matches) with the estimated calibration matrix. I'll send the data to you by email.

**Comment by sweeneychris** [comment]
Closing this, as the issue was resolved via email.
