### ISSUE TITLE
Installation Could NOT find ImageMagick error

### ISSUE THREAD

**Issue by rwkrwk** [sweeneychris/TheiaSfM#91]
Installing Theia on ubuntu 16.04. Getting the following error. I am sure ImageMagick(7.0.2-1) is installed and both convert and mogrify commands are working.
`-- Check for ImageMagick
CMake Error at /usr/local/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find ImageMagick (missing: ImageMagick_convert_EXECUTABLE
  ImageMagick_mogrify_EXECUTABLE ImageMagick_convert_EXECUTABLE
  ImageMagick_mogrify_EXECUTABLE)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.6/Modules/FindImageMagick.cmake:268 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  libraries/cimg/CMakeLists.txt:44 (find_package)

-- Configuring incomplete, errors occurred!
`

**Comment by sweeneychris** [comment]
Sorry for the delayed response (I am currently attending CVPR). You should be able to manually specify the imagemagick path according to the docs: https://cmake.org/cmake/help/v3.0/module/FindImageMagick.html

Which version of CMake are you using? Perhaps try upgrading to a recent stable release

**Comment by rwkrwk** [comment]
Thanks for your response, i have cmake version 3.6.0 which is the most recent. Still having trouble, how can i specify the imagemagick path?

**Comment by sweeneychris** [comment]
set ImageMagick_LIBRARIES and ImageMagick_INCLUDE_DIRS. Otherwise, this sounds like a CMake error since I am using the internal CMake Find method for imagemagick so I would post this issue to their message boards

**Comment by rwkrwk** [comment]
So i successfully set the imagemagick path and it can now be found along with all other dependencies. But when i do the make step of the building process this is the output i get
![screenshot from 2016-07-05 15-54-26](https://cloud.githubusercontent.com/assets/20173389/16597870/1c7438de-42c9-11e6-882f-3a0dff82b7ac.png)

**Comment by sweeneychris** [comment]
This should fix it: https://review.gerrithub.io/#/c/282910/

**Comment by rwkrwk** [comment]
Thank you so much for the quick reply and all the help, works great.
