### ISSUE TITLE
VS2013 akaze.cpp compile error C2872

### ISSUE THREAD

**Issue by Just5D** [sweeneychris/TheiaSfM#94]
VS2013, eigen 3.2.7, akaze.cpp compile error C2872.
Error 1 error C2872: "RowMatrixXf": ambiguous symbol  ... \ libraries \ akaze \ src \ AKAZE.cpp 114 1 akaze.
Thanks!

**Comment by sweeneychris** [comment]
Could you submit a pull request to fix this (and other compiler issues you may have)? I do not have a windows machine to test it.

**Comment by Just5D** [comment]
int AKAZE::Create_Nonlinear_Scale_Space(const RowMatrixXf & img)  -to- 
int AKAZE::Create_Nonlinear_Scale_Space(const libAKAZE::RowMatrixXf & img)
done

**Comment by FishHe** [comment]
I have the same bug on VS2015 update3 win32 x64.

int AKAZE::Create_Nonlinear_Scale_Space(const RowMatrixXf & img) -to-
int AKAZE::Create_Nonlinear_Scale_Space(const libAKAZE::RowMatrixXf & img)

This answer works fine with this problem for the environment!
