### ISSUE TITLE
CMake error: glut-Xmu

### ISSUE THREAD

**Issue by hlzz** [sweeneychris/TheiaSfM#95]
Hi, I try to compile the library but encounter a cmake error. Here is my output message:

-- Found Eigen: /usr/include/eigen3 (found suitable version "3.2.5", minimum required is "3.2.0") 
-- Found Eigen version 3.2.5: /usr/include/eigen3
-- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
-- Found installed version of gflags: /usr/lib64/cmake/gflags
-- Detected broken gflags install in: /usr/lib64/cmake/gflags, version: 2.1.1 <= 2.1.2 which defines gflags_LIBRARIES = gflags which is not an imported CMake target, see: https://github.com/gflags/gflags/issues/110.  Attempting to fix by detecting correct gflags target.
-- Found valid gflags target: gflags-shared, updating gflags_LIBRARIES.
-- Detected gflags version: 2.1.1
-- Found Google Flags: /usr/include in namespace: gflags
-- Check for Google Log
-- Found Google Logging: /usr/include
-- Check for Ceres
-- Found required Ceres dependency: Eigen version 3.2.5 in /usr/include/eigen3
-- Found required Ceres dependency: Glog in /usr/include
-- Found Ceres version: 1.12.0 installed in: /usr/local with components: [LAPACK, SuiteSparse, SparseLinearAlgebraLibrary, CXSparse, SchurSpecializations, OpenMP]
-- Found Ceres: /usr/local/include;/usr/include/eigen3;/usr/include
-- A library with BLAS API found.
-- Found AMD library: /usr/local/lib/libamd.so
-- Found AMD header in: /usr/local/include
-- Found CAMD library: /usr/local/lib/libcamd.so
-- Found CAMD header in: /usr/local/include
-- Found COLAMD library: /usr/local/lib/libcolamd.so
-- Found COLAMD header in: /usr/local/include
-- Found CCOLAMD library: /usr/local/lib/libccolamd.so
-- Found CCOLAMD header in: /usr/local/include
-- Found CHOLMOD library: /usr/local/lib/libcholmod.so
-- Found CHOLMOD header in: /usr/local/include
-- Found SuiteSparseQR library: /usr/local/lib/libspqr.so
-- Found SuiteSparseQR header in: /usr/local/include
-- Found Intel Thread Building Blocks (TBB) library: /usr/lib64/libtbb.so, assuming SuiteSparseQR was compiled with TBB.
-- Found Intel Thread Building Blocks (TBB) Malloc library: /usr/lib64/libtbbmalloc.so
-- Found SuiteSparse_config library: /usr/local/lib/libsuitesparseconfig.so
-- Found SuiteSparse_config header in: /usr/local/include
-- Adding librt: /usr/lib64/librt.so to SuiteSparse_config libraries (required on Linux & Unix [not OSX] if SuiteSparse is compiled with timing).
-- Found METIS library: /usr/local/lib/libmetis.so.
-- Found SuiteSparse 4.5.3
-- Found Eigen: /usr/include/eigen3 (found version "3.2.5") 
-- Found Eigen version 3.2.5: /usr/include/eigen3
-- Building with OpenMP.
-- Building with OpenMP.
-- Check for ImageMagick
-- Found ImageMagick: 
-- A library with BLAS API found.
-- Could NOT find HDF5 (missing:  HDF5_LIBRARIES HDF5_INCLUDE_DIRS) 
CMake Warning at libraries/flann/CMakeLists.txt:77 (message):
  hdf5 library not found, some tests will not be run

-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_MAIN_LIBRARY) 
CMake Warning at libraries/flann/CMakeLists.txt:116 (message):
  gtest library not found, some tests will not be run

-- Install prefix: /usr/local
-- Build type: Release
-- Building C bindings: OFF
-- Building examples: OFF
-- Building tests: OFF
-- Building documentation: OFF
-- Building python bindings: OFF
-- Building matlab bindings: OFF
-- Building CUDA library: OFF
-- Using OpenMP support: ON
-- Using MPI support: OFF
-- CMAKE_CXX_FLAGS:  -std=c++11
-- Found Eigen version 3.2.5: /usr/include/eigen3
-- CMAKE_CXX_FLAGS:  -std=c++11
-- Default Install prefix: /usr/local/
-- Found Eigen version 3.2.5: /usr/include/eigen3
-- Found installed version of gflags: /usr/lib64/cmake/gflags
-- Detected broken gflags install in: /usr/lib64/cmake/gflags, version: 2.1.1 <= 2.1.2 which defines gflags_LIBRARIES = gflags which is not an imported CMake target, see: https://github.com/gflags/gflags/issues/110.  Attempting to fix by detecting correct gflags target.
-- Found valid gflags target: gflags-shared, updating gflags_LIBRARIES.
-- Detected gflags version: 2.1.1
-- Check for Google ceres-solver
-- Found required Ceres dependency: Eigen version 3.2.5 in /usr/include/eigen3
-- Found required Ceres dependency: Glog in /usr/include
-- Found Ceres version: 1.12.0 installed in: /usr/local with components: [LAPACK, SuiteSparse, SparseLinearAlgebraLibrary, CXSparse, SchurSpecializations, OpenMP]
-- Found Ceres headers in: /usr/local/include;/usr/include/eigen3;/usr/include;/usr/local/include;/usr/include/eigen3;/usr/include
-- A library with BLAS API found.
-- A library with BLAS API found.
-- A library with LAPACK API found.
-- Check for Optimo
-- Found optimo headers: /home/tianwei/Documents/Projects/TheiaSfM/libraries/optimo
-- Found GLUT: /usr/include
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
GLUT_Xmu_LIBRARY (ADVANCED)
    linked by target "view_reconstruction" in directory /home/tianwei/Documents/Projects/TheiaSfM/applications

-- Configuring incomplete, errors occurred!
See also "/home/tianwei/Documents/Projects/TheiaSfM/build/CMakeFiles/CMakeOutput.log".
See also "/home/tianwei/Documents/Projects/TheiaSfM/build/CMakeFiles/CMakeError.log".

So the error is about GLUT_Xmu_LIBRARY. What is that? I search the web for a while but have no clue. Thanks!

**Comment by sweeneychris** [comment]
Are you on Ubuntu? Sometimes this issue has happened for me as well and this has worked for me:

sudo apt-get install libxmu-dev libxi-dev

**Comment by hlzz** [comment]
No, I am using 'yum' and cannot find package libxmu-dev and libxi-dev

**Comment by hlzz** [comment]
And I have installed libxmu and libxi. They are called libXmu and libXi under yum. But it's not the '-dev' version

**Comment by hlzz** [comment]
oh! didn't realize that the development version under yum is called '-devel'. Problem fixed, thanks a lot!

**Comment by sweeneychris** [comment]
Glad I could help! Feel free to open another issue if you have more questions or run into problems
