### ISSUE TITLE
Consider OpenImageIO instead of CImg and EasyExif

### ISSUE THREAD

**Issue by sweeneychris** [sweeneychris/TheiaSfM#98]
https://github.com/OpenImageIO/oiio

**Comment by fabiencastan** [comment]
+1

**Comment by sweeneychris** [comment]
Done. OpenImagIO is now a required external library and CImg and EasyExif have been removed.

https://github.com/sweeneychris/TheiaSfM/commit/5eb2b96b65000b2a0fabe8f09f1daf20a065dcb1

**Comment by libing64** [comment]
@sweeneychris  Which version of OpenImageIO are you using?

**Comment by sweeneychris** [comment]
1.6 or newer works for me. The website has been updated to state this as well

**Comment by libing64** [comment]
@sweeneychris  Great  thanks.
