### ISSUE TITLE
Different results with the same dataset

### ISSUE THREAD

**Issue by mhsung** [sweeneychris/TheiaSfM#99]
Hi Chris,

I saw some cases that TheiaSfM gives different outputs for the same data, same parameters, and same machine. Could you point out where this randomness comes from?

**Comment by sweeneychris** [comment]
There are many areas where this comes from but the primary place is in RANSAC, which is a randomized algorithm used to maintain robustness to outliers. Every single SfM method will use RANSAC and so no method will produce the exact same output each time. However, if the input data is of sufficient quality, the solutions should be quite similar each time.

**Comment by mhsung** [comment]
I fixed the random seed in 'src/theia/util/random.cc' but still the output is different all the time when I run the same experiment. It is not a subtle change in binary files, but camera poses change very much. What would be other suspicious to check for the randomness?

**Comment by sweeneychris** [comment]
Search the code for anywhere Eigen's Random function is called such as in the nonlinear position estimator https://github.com/sweeneychris/TheiaSfM/blob/master/src/theia/sfm/global_pose_estimation/nonlinear_position_estimator.cc#L158

I also use the rand() function during cascade hashing feature matching, but I think that is the only place:
https://github.com/sweeneychris/TheiaSfM/blob/master/src/theia/matching/cascade_hasher.cc#L66

I can't recall other obvious points at the moment. As you can see from the GitHub issue tracker, adding a seed to the RANSAC module (and the random functions in general) is on my priority list

**Comment by sweeneychris** [comment]
As of the [latest commit](https://github.com/sweeneychris/TheiaSfM/commit/471b3e1483a6fe9c28ec0d574a39ac53fcb0f2b4) you can now specify a RandomNumberGenerator to the reconstruction builder class, which will control how random numbers are created. If you pass one that has been created with a seed then you should be able to get the same results every time. 

This is brand new, so please feel free to test it and let me know if it works for you.

**Comment by sweeneychris** [comment]
Closing this for now. Feel free to reopen this issue if you are still having issues.
